versionedRouter.js
Sending an apiVersion as a response header for destination transformations to check against in rudder-server for compatibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/176)
=> Api Version for transformer <-> backend compatibility

versionedRouter.js
This is crashing our influxdb due to huge number of distinct possible values
=> Remove groupedBy tag.

v0/destinations/am/transform.js
Events other than `track` might provide traits to Amplitude, e.g. if there's a (utm) campaign, we might populate utm props in traits for `page` view event. This allow us to work around these issue.
Previously, this guard cause the traits to be silently drop without any other option to populate it correctly in transformer.
=> fix: Remove event type guard that prevent traits from copying to user props

destTransformer.js, package-lock.json, package.json, util/cluster.js
Adds graceful shutdown when running in cluster mode (default in our docker images)
When the master receives SIGTERM, it passes on SIGTERM to workers.
Workers gracefully shut down the server using the library https://github.com/sebhildebrandt/http-graceful-shutdown
> Fix [#1]()
=> Added graceful shutdown

__tests__/data/ga_output.json, v0/destinations/ga/transform.js
While #522 is a step in the right direction, it does not solve the problem we have at #462 because it still default to a value. The problem we have is that `cid` always have a value, not what kind of value it is.
The reason we does not want `cid` to default any value because it causes double session in GA. GA will treat these value as opaque so if they see a value in `cid`, they will be grouped as different session.
If anyone wanted to default to a value, they already can use `disableMd5` to `false`, for `true` value, we want it to not default to any values, if not, there is no point for that option in the first place.
- #462
- #522
=> fix(ga): Do not fallback to userId for cid when disableMd5 is true, keep it undefined

v0/destinations/braze/transform.js
Aliases to identity property empty for earlier batches(after batch split)
When the identify requests are > 50, then batching actually takes place
Here when 56 identify requests were provided to a batch with all containing user_id identify information
It should've split into 2 batches one containing 50 and other containing remaining 6
But it was observed that only the remaining 6 were seen in the later batch but other 50 were missing.
This PR contains the fix that would enable us to see the missing 50 data.
https://www.notion.so/rudderstacks/acorns-BRAZE-9041e5652a604a599566dee82f65b621
> Fix [#1]() 
The fix would enable us to see the missing 50 data
=> braze batch identity fix for earlier batches(after split)

v0/destinations/salesforce/data/SFIdentifyConfig.json, v0/destinations/salesforce/data/SFIgnoreConfig.json
> We added CreatedDate as a standard field so that historical users can be added with a different CreatedDate than the current date. If CreatedDate is not passed then it will default to the timestamp of the event
> Fix [#1]()
=> added createdDate as a standard field for SFMC

Dockerfile
This is a minor change that solves a small inconvenience we've faced.
`EXPOSE` is adding metadata to the image, which although not required, can be useful is some cases.
https://docs.docker.com/engine/reference/builder/#expose
While using https://github.com/ory/dockertest, we faced the following:
The default way of running containers didn't work:
```go
resource, err := pool.Run("rudderlabs/rudder-transformer", "latest", []string{".."})
if err != nil {
log.Fatalf("Could not start resource: %s", err)
}
transformerPort := resource.GetPort("9090/tcp"))
```
That is because by default, `dockertest` does:
```go
docker run  -P rudderlabs/rudder-transformer
```
The command above maps all the exposed ports to random ports on the host. 
Since the image doesn't specify any **exposed** port, which …
=> Add EXPOSE instruction in Dockerfile

util/stats.js
Removes pid and transformerHostName as common tags from all the tags. This is to reduce the memory usage of influx.
> Fix [#1]()
=> Remove pid and transformerHostName tags from the stats

__tests__/data/customerio_input.json, __tests__/data/customerio_output.json, v0/destinations/customerio/transform.js
Previously we used to send device token to customer io only on the life cycle events which were sent by the Mobile SDK's, but this is resulting in a delay from sending it over to customer io, as the next life cycle event is sent on app launch/minimize from the moment the device token was handed over to RudderStack SDK's.
> Fix [#1]()
=> Fixed Device Token not sent to Customer io Immediately

v0/destinations/mp/data/MPIdentifyConfig.json
> `avatar` had been incorrectly written as `avator`. This fixes it.
> No related issues
=> Fix typo in MixPanel Identity Config

__tests__/data/am_output.json, __tests__/data/am_router_output.json, v0/destinations/am/transform.js
Removed duplicate fields `price`, `product_id`, `quantity`, `revenue` from `event_properties` and `city` and `country` from `user_properties`.
> Fix [#1]()
=> BugFix Amplitude: Removed duplicate fields from event_properties and user_properties

v0/destinations/mp/transform.js
> Allowing user traits set to NULL to pass through the transformer without omission.
> Fix [#1]()
=> Mixpanel: eliminate removeUndefinedAndNullValues function

versionedRouter.js
> After the destination transformation, the user ID sent in the response is reset to an empty string if it is falsy (including 0 and false). Otherwise, the server panics while trying to unmarshal the response as it only expects a string type for the user ID.
> N/A
=> Bug Fix: User ID is reset to empty string when it is falsy

v0/destinations/salesforce/transform.js
> Use contactId instead of leadId for leads converted to contacts.
> Abort lead updation if lead is deleted. Create a new one.
> Fix [#1]()
=> [Salesforce] :: Use contactId for converted lead

__tests__/data/facebook_pixel_input.json, __tests__/data/facebook_pixel_output.json, v0/destinations/facebook_pixel/transform.js
Facebook Pixel does not allow any other data type than `string` as `content_category`. 
1. Hence, we are converting all types of data into strings. 
2. In the case of arrays, without throwing errors, we are concatenating the elements with a comma (,) separator. 
3. For any other types of data ( example: objects ) we will throw an error.
> Fix [#1]()
=> fb_pixel:  param issue

__tests__/data/mp_output.json, __tests__/data/mp_router_output.json, v0/destinations/mp/transform.js
> Refactoring Screen and Page call from `Viewed a page/Viewed a screen` to ``Viewed a Page/Viewed a Screen`to make standardization across all device mode and cloud mode.
> Fix [#1]()
=> [Mixpanle] Standardizing event names for Page and Screen calls

__tests__/appsflyer_source.test.js, __tests__/data/appsflyer_source_output.json, v0/sources/appsflyer/transform.js
> Existing behavior of Appsflyer source - discard events from Appsflyer which are missing `customer_user_id` which are mapped to `userId` at rudderstack, this leads to loss of events which are missing the above identifier. As `customer_user_id` is an optional field we are on-boarding `anonymousId` support for AF source to mitigate the issue 
> Fix [#1]()
=> Appsflyer Bugfix - adding support for anonymousId in appsflyer source

__tests__/data/google_adwords_enhanced_conversions_input.json, __tests__/data/google_adwords_enhanced_conversions_output.json, __tests__/data/google_adwords_enhanced_conversions_proxy_input.json, __tests__/data/google_adwords_enhanced_conversions_router_input.json, v0/destinations/google_adwords_enhanced_conversions/data/trackConfig.json
Updated Google AdWords Enhanced Conversions track config to be consistent with [ordering e-commerce specification](https://www.rudderstack.com/docs/rudderstack-api/api-specification/rudderstack-ecommerce-events-specification/ordering/) and [identify event specification](https://www.rudderstack.com/docs/rudderstack-api/api-specification/rudderstack-spec/identify/).
`orderId` -> `order_id`
`currencyCode` -> `currency`
`countryCode` duplicate -> `country`
> Fix [#1]()
=> bugfix(google adwords enhanced conversions):updating track config

__tests__/data/mailchimp_input.json, __tests__/data/mailchimp_output.json, __tests__/data/mailchimp_router_input.json, __tests__/data/mailchimp_router_output.json, v0/destinations/mailchimp/transform.js
Adding support for backward compatibility, with adding merge_fields while updating a subscriber. The support for merge_fields is added by an open-source [here](https://github.com/rudderlabs/rudder-transformer/pull/1098/files) is the PR link.
> Fix [#1]()
=> bugfix(mailchimp): Adding support for backward compatibility.

__tests__/data/am_input.json, __tests__/data/am_output.json, v0/destinations/am/data/AmplitudeAliasConfig.json, v0/destinations/am/data/AmplitudeDefaultConfig.json, v0/destinations/am/data/AmplitudeGroupConfig.json, v0/destinations/am/data/AmplitudeIdentifyConfig.json, v0/destinations/am/data/AmplitudePageConfig.json, v0/destinations/am/data/AmplitudeScreenConfig.json, v0/destinations/am/transform.js, v0/destinations/am/utils.js
Amplitude support event_id as an incrementor whose value is help to differentiate among events. We were mapping it from context.traits, properties, etc. But as it is only related to `Amplitude` we should take it from `integrations.Amplitude`. We are implementing that here.
> Fix [#1]()
=> bugfix(Amplitude) :: Getting event_id from integrations.Amplitude

adapters/network.js
Axios don't work for large payloads. So made the maxContentLength and maxBodyLength configurable from env.
> Fix [#1]()
=> bugfix(GARL):: Making maxContentLength and maxBodyLength configurable for axios call.

__mocks__/data/salesforce/proxy_response.json, __mocks__/network.js, __tests__/data/proxy_input.json, __tests__/data/proxy_output.json, adapters/networkhandler/genericNetworkHandler.js, versionedRouter.js
The issue was that for Salesforce we were getting an unmarshal failure which compounded to panic because postgres was not allowing to insert `\u000` character
The reason for unmarshalling error was that the response from transformer was empty
When the status-code with `204` was being sent to `server`, the response body is empty even when from transformer the response body was being set.
Hence for now, all the `2xx` status, we'll be sending a `200` status to server
- Test-cases to see when we get a `204` status if we're indeed sending a JSON
- Change to send `200` for all `2xx` status we receive from destination(s)
> Fix [#1]()
=> Hotfix for fixing panic in server

__tests__/data/ga4_input.json, __tests__/data/ga4_output.json, v0/destinations/ga4/transform.js, v0/destinations/ga4/utils.js
> Allowing users to send custom properties to GA4.
> To add these custom properties to the payload, we have excluded(using EXCLUSION lists for every event) some fields(which are already mapped) and then added all other fields to the event payload(using the `extractCustomFields` function) before sending it to GA4.
> Fix [#1]()
=> feature(enhancement): GA4- allow custom dimension passthrough

__tests__/data/personalize_input.json, __tests__/data/personalize_output.json, v0/destinations/personalize/transform.js
putEvents will not convert every properties data to a string. Also backward compatibility is ensured by introducing new toggle button in webapp
> Fix [#1]()
=> bugfix(personalize): allowing non string properties to personalize

versionedRouter.js
As part of this [CFD](https://www.notion.so/rudderstacks/Duplicate-events-in-downstream-destinations-RudderStack-ad13926a1153441091aced26bb1b157d?d=f7c7d944be8a415da74c7cb8c950d96c) counter stats have been added to the transformer proxy request
- tf_proxy_input_count
- tf_proxy_dest_req_count
- tf_proxy_dest_resp_count
- tf_proxy_proc_ax_response_count
- tf_proxy_resp_handler_count
- tf_proxy_err_response_count
> All the above stats are prefixed with `transformer_` while checking in the grafana dashboard
> Fix [#1]()
=> fix(router): Adding counter stats to proxy request

__tests__/data/adobe_analytics_input.json, __tests__/data/adobe_analytics_output.json, v0/destinations/adobe_analytics/transform.js
The page and screen events do not have `event` field. Adobe analytics was expecting this and was generating error in transformer.
- while adding properties for merchandise events, if `products.propertyName` is mentioned, it was still finding in the root properties, instead of products array. Which is a bug
- here is the [statement](https://github.com/rudderlabs/rudder-transformer/blob/master/v0/destinations/adobe_analytics/transform.js#L300-L310), where we are forEach looping on Object.keys(adobeProdEvent) which adobeProdEvent is a string equal to "custom" so it turns into
c=3.3|u=3.3|s=3.3|t=3.3|o=3.3|m=3.3, which is not the case in device mode. ref: [here](https://github.com/rudderlabs/rudder-sdk-js/blob/e98f9c440aaefeefdcc8e4d8c624969045160519/integrations/AdobeAnalytics/util.js#L515) …
=> Bugfix(integration):Adobe Analytics Page and Screen Calls expecting event field

__tests__/data/intercom_output.json, __tests__/data/intercom_router_output.json, v0/destinations/intercom/data/INTERCOMIdentifyConfig.json
=> Updated Intercom signed_up_at field to send seconds instead of milliseconds

__tests__/data/facebook_pixel_input.json, __tests__/data/facebook_pixel_output.json, v0/destinations/facebook_pixel/transform.js
> **_Issue_:**
Facebook Pixel `custom_data` expects a string or number
According to Rudderstacks documentation of the [product searched](https://www.rudderstack.com/docs/rudderstack-api/api-specification/rudderstack-ecommerce-events-specification/browsing/#products-searched) event, the query should be a string / Object
So, [here](https://github.com/rudderlabs/rudder-transformer/blob/1537d3ec5d932e603a011a33c0fc53a43623b33d/v0/destinations/facebook_pixel/transform.js#L496) query should be a string or number.
**_Fix:_**
We are handling it inside the transformer by throwing an appropriate error.
> Fix [#1]()
=> bugfix(CFD): Facebook Pixel error handling

__tests__/data/dynamicConfig_input.json, __tests__/data/dynamicConfig_output.json, util/dynamicConfig.js
Added support for `event.` alias for `message.` in dynamic configuration values for destinations.
The `message.` notation in dynamic configuration values is valid since the event structure as seen by the transformer is below:
```
{
"message": {
"properties": {
"key1": "val1"
},
...
},
"destination": {
"Config": {
"someKey": "{{ message.properties.key1 || \"defaultVal\" }}"
...
}
}
}
```
Without this update, it can confuse the users when going through the examples in our [documentation](https://www.rudderstack.com/docs/user-guides/how-to-guides/dynamic-destination-configuration/). 
Everywhere in our documentation, an event object is accessed as `event.`.
Now the users can also specify dynamic configuration values as `{{ event.properties.somekey || "defaultVal" }}` which would be equivalent …
=> feat: support 'event' alias for 'message' in dynamic config

__tests__/data/shopify_source_input.json, __tests__/data/shopify_source_output.json, v0/sources/shopify/transform.js, v0/sources/shopify/util.js
This pr attempts to address the issue of identity resolution to downstream tools via Shopify connector. This transformation is used to transform Shopify server to server events pushed by webhooks, which currently might not have any user identifier if the user chooses to stay anonymous during the later stages of the journey where these events are generated.
The goal is to use use the `cart_token` available in such events and treat it as an `anonymousId` for these events.
To stitch these same events to the events collected by the tracking script, the tracking script will always check in cookies for the same `cart_token` whenever available the tracking script will shift anonymousId to `cart_token` and make a alias call for the same.
Essentially we user will be tracked by a common identifier …
=> bugfix(integrations): Shopify Identity Resolution Fix

__tests__/data/marketo_output.json, __tests__/data/marketo_router_output.json, __tests__/data/sanity/marketo_router_output.json, v0/destinations/marketo/transform.js
> Marketo - correct attribute to attribute
> Fix [#1]()
=> feat(integration): marketo - correct attribute to attributes

__tests__/data/refiner.json, __tests__/data/refiner_router.json, v0/destinations/refiner/utils.js
-> email value is conflicting with group email, now taking a user level email from context.traits
- [ ✅] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- [ ✅] "Ready for review" label attached to the PR and reviewers mentioned in a comment
=> fix: refiner destination group call email value

v0/destinations/am/transform.js
… discarding the event
> If userId and deviseId both are undefined, the event is just discarded instead of sending an error response back which is causing input output size mismatch. Corrected this by sending an error response along with the metadata.
> Fix [#1]()
=> fix(amplitude): send error response instead of discarding the event during batch processing

__tests__/data/pinterest_tag_output.json, cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, v0/destinations/pinterest_tag/utils.js
> Previously any user-defined event was defaulted to "custom" event, now, we are sending back the exact event name, if no mapping is found. This will show up as "unknown" event in Pinterest dashboard
> Fix [#1]()
=> feat(integration): user defined event support for pinterest conversions destination

util/errorNotifier/bugsnag.js, v0/destinations/adobe_analytics/transform.js, v0/destinations/af/transform.js, v0/destinations/attribution/transform.js, v0/destinations/customerio/transform.js, v0/destinations/delighted/util.js, v0/destinations/drip/util.js, v0/destinations/eventbridge/transform.js, v0/destinations/fb/transform.js, v0/destinations/gainsight_px/util.js, v0/destinations/googlepubsub/transform.js, v0/destinations/webengage/transform.js, v0/sources/appcenter/transform.js, v0/sources/appsflyer/transform.js, v0/sources/auth0/transform.js, v0/sources/braze/transform.js, v0/sources/canny/transform.js, v0/sources/customerio/transform.js, v0/sources/iterable/transform.js, v0/util/index.js
The changes to suppress all the errors from notifying Bugsnag that are manually thrown from the transformers.
- Replaced all the instances of `Error` with `CustomError`. We have to clean up all the `CustomError` throws later.
- Also, defaulted the status code to `400` in the `CustomError` constructor.
N/A
=> fix: suppress errors thrown from the transformers in bugsnag notifier

__tests__/data/pinterest_tag_output.json, cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, v0/destinations/pinterest_tag/utils.js
> we need to release it along with device mode. Reverting temporarily for a hotfix release in transformer
> Fix [#1]()
=> fix [integration] : Pinterest user defined event temporary revert

__tests__/data/am_batch_input.json, __tests__/data/am_batch_output.json, __tests__/data/am_output.json, __tests__/data/am_router_output.json, v0/destinations/am/config.js
- changed the BASE_URL value in config.js file for amplitude from **https://api.amplitude.com** to **https://api2.amplitude.com**
> Fix [#1]() 
- [ ✅] "Ready for review" label attached to the PR and reviewers mentioned in a comment
=> fix : amplitude api endpoint version update

__tests__/data/clevertap_deleteUsers_proxy_input.json, __tests__/data/clevertap_deleteUsers_proxy_output.json, __tests__/data/mp_deleteUsers_proxy_input.json, __tests__/data/mp_deleteUsers_proxy_output.json, v0/destinations/af/config.js, v0/destinations/clevertap/config.js, v0/destinations/clevertap/deleteUsers.js, v0/destinations/mp/config.js, v0/destinations/mp/deleteUsers.js
- as of now for existing destination if we want to delete users then we are doing it one by one. like for every user we are making user deletion request to destination which is impecting the performance of the api
- in this pr for mixpanel and clevertap destination we are making user deletion request in batch since they are supporting batch user deletion
- also, for a perticular user if we don't found required key(ex **userId**) then we will drop that perticular user and proceed for remaining users
- [ ✅] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- [ ✅] "Ready for review" label attached to the PR and reviewers mentioned in a comment
=> feature: batch user deletion support for mixpanel and clevertap

util/errorNotifier/bugsnag.js
Suppressed the CDK (v1) error types in the Bugsnag notifier to avoid noise.
N/A
=> fix: suppress cdk error types

__tests__/data/hs_input.json, __tests__/data/hs_router_input.json, v0/destinations/hs/util.js
Inside the `getHashFromArray` function we are setting properties to lowercase, which is causing mismatch with dashboard properties. So updated the code not to change whatever we are getting in properties.
> Fix [#1]()
=> fix(destination): do not update event properties to lowercase in hubspot

__tests__/data/ga4.json, v0/destinations/ga4/utils.js, v0/util/index.js
> Previously any array type value was being flattened as `arrayProperty[1]: "array value”` which was throwing error in the destination end as below:
```
{
"firstAttemptedAt": "2022-11-16T06:40:21.102Z",
"response": "{\"status\":400,\"message\":\"[GA4] Validation Server Response Handler:: Validation Error for ga4 of field path :events.params | NAME_INVALID-Event param [string_value: \\t \\\"Furniture\\\"] has invalid name [categoryLevels[0]]. Only alphanumeric characters and underscores are allowed.\",\"destinationResponse\":\"Event param [string_value: \\t \\\"Furniture\\\"] has invalid name [categoryLevels[0]]. Only alphanumeric characters and underscores are allowed.\",\"statTags\":{\"errorAt\":\"proxy\",\"destType\":\"GA4\",\"stage\":\"responseTransform\",\"scope\":\"api\",\"meta\":\"ab …
```
=> fix(destination): fix the flattening issue solve for ga4 

Dockerfile, Dockerfile-no-func, Dockerfile-ut-func, util/cluster.js
Using the number of CPUs can be problematic in several environments:
* locally, when running within docker M1 mac (10 cores), the number of workers creates a lot of CPU pressure causing integration tests to fail.
* on k8s environments, due to the number of CPUs detected (using the number of nodes, not pod requests/limits), the configuration is unpopular.
https://github.com/rudderlabs/rudder-server/pull/2702
=> chore: stop using cpu count for workers

__tests__/data/hs_output.json, v0/destinations/hs/HSTransform-v1.js
> Hub id is required to track the event successfully in Hubspot. Passing the hub id in legacy track API
> Fix [#1]()
=> fix(hubspot): legacy track api

.vscode/launch.json, benchmark/index.js
Refactor native handlers to use direct destination handler instead of versionedRouter.handleV0Destination
> Fix [#1]()
=> refactor: add router support to benchmarking script

__tests__/data/singular.json, v0/destinations/singular/config.js, v0/destinations/singular/util.js
> Allow sending ios, ipados, watchos or tvos in contextual properties 
> Fix [#1]()
=> feat(destination): singular- add support for other apple os

__tests__/data/persistiq.json, v0/destinations/persistiq/data/persistIqIdentifyConfig.json, v0/destinations/persistiq/transform.js
> Email was marked as a required field for creating and updating lead calls, which is not the case. It is only required on creating one.
This PR fixes that along with test cases.
> Fix [#1]()
=> fix: email not required for update call

src/v0/destinations/user/transform.js, src/v0/destinations/user/utils.js, test/__tests__/data/user.json
=> feat: new error types for user.com destination

src/v0/destinations/moengage/transform.js, src/v0/destinations/monday/transform.js, src/v0/destinations/monday/util.js, src/v0/destinations/monetate/transform.js, src/v0/destinations/mp/deleteUsers.js, src/v0/destinations/mp/transform.js, src/v0/destinations/mp/util.js, test/__tests__/data/moengage_output.json, test/__tests__/data/monday.json, test/__tests__/data/monetate_output.json, test/__tests__/data/mp_output.json, test/__tests__/deleteUsers/data/mp/handler_output.json
=> feat: new error types for destinations(mixpanel, monetate, monday, moengage, minio)

src/v0/destinations/signl4/transform.js, src/v0/destinations/singular/transform.js, src/v0/destinations/singular/util.js, src/v0/destinations/slack/transform.js, src/v0/destinations/snapchat_conversion/transform.js, src/v0/destinations/snapchat_custom_audience/networkHandler.js, src/v0/destinations/snapchat_custom_audience/transform.js, src/v0/destinations/snapchat_custom_audience/utils.js, test/__tests__/data/signl4.json, test/__tests__/data/signl4_router_output.json, test/__tests__/data/singular.json, test/__tests__/data/slack_output.json, test/__tests__/data/slack_router_output.json, test/__tests__/data/snapchat_conversion.json, test/__tests__/data/snapchat_conversion_router_output.json, test/__tests__/data/snapchat_custom_audience.json, test/__tests__/data/snapchat_custom_audience_proxy_output.json
=> feat: new error types for destinations (snapchat_custom_audience, snapchat_conversion, slack, singular, signl4)

jest.config.js, src/cdk/v2/handler.js, src/v0/destinations/am/transform.js, src/v0/destinations/wootric/transform.js, src/v0/util/errorTypes/base.js, src/v0/util/index.js, src/versionedRouter.js
Refactored router transform implementation.
It was missing two things:
- Bugsnag notifications (both at event level error handler and the global one)
- Translation of the handled error to the newly added error types
To send errors to Bugsnag with rich metadata, we have changed the signature of `processRouterDest` to accept a new argument, `reqMetadata`.
Some other minor updates:
- `flowType` to `feature` name change in CDK v2 flow
- The default error type is changed to `TransformationError`. It is functionally same as the previous logic.
N/A
=> feat: refactor router transform implementation

test/__tests__/deleteUsers/data/af/handler_output.json, test/__tests__/deleteUsers/data/am/handler_output.json, test/__tests__/deleteUsers/data/braze/handler_output.json, test/__tests__/deleteUsers/data/clevertap/handler_output.json, test/__tests__/deleteUsers/data/engage/handler_output.json, test/__tests__/deleteUsers/data/ga/handler_output.json, test/__tests__/deleteUsers/data/intercom/handler_output.json
=> fix: user deletion test cases

src/v0/destinations/kissmetrics/transform.js, src/v0/destinations/klaviyo/transform.js, src/v0/destinations/kochava/transform.js, src/v0/destinations/kustomer/transform.js, src/v0/destinations/leanplum/transform.js, src/v0/destinations/lytics/transform.js, src/v0/destinations/mailchimp/transform.js, src/v0/destinations/mailjet/transform.js, src/v0/destinations/mailmodo/transform.js, src/v0/destinations/marketo/transform.js, src/v0/destinations/marketo_bulk_upload/transform.js, src/v0/destinations/marketo_static_list/transform.js, src/v0/destinations/mautic/transform.js, src/v0/destinations/moengage/transform.js, src/v0/destinations/monday/transform.js, src/v0/destinations/monetate/transform.js, src/v0/destinations/mp/transform.js, src/v0/destinations/ometria/transform.js, src/v0/destinations/one_signal/transform.js, src/v0/destinations/pardot/transform.js, src/v0/destinations/persistiq/transform.js, src/v0/destinations/personalize/transform.js, src/v0/destinations/pinterest_tag/transform.js, src/v0/destinations/posthog/transform.js, src/v0/destinations/profitwell/transform.js, src/v0/destinations/refiner/transform.js, src/v0/destinations/rockerbox/transform.js, test/__tests__/data/mautic_router_output.json, test/__tests__/data/pinterest_tag_router_output.json
=> feat: router tranform refacor for destinations (batch - 3)

src/v0/destinations/fb_custom_audience/transform.js, src/v0/destinations/googlepubsub/transform.js, src/v0/destinations/googlesheets/transform.js, src/v0/destinations/heap/transform.js, src/v0/destinations/hs/transform.js, src/v0/destinations/indicative/transform.js, src/v0/destinations/intercom/transform.js, src/v0/destinations/iterable/transform.js, src/v0/destinations/june/transform.js, src/v0/destinations/keen/transform.js, test/__tests__/data/clickup_router_output.json
=> feat: refactor router transformer - 4

src/v0/destinations/active_campaign/transform.js, src/v0/destinations/clickup/util.js, src/v0/sources/canny/util.js, src/versionedRouter.js
Fixed all the final self-review issues.
> Fix [#1]()
=> fix: final review issues

src/v0/util/tags.js, src/versionedRouter.js
We are adding `workspaceId` as one of the stat-tags(wherever `destinationId` is being currently used in source-code)
> Fix [#1]()
=> chore: add workspaceId as stat-tag

buildspec.saas.yml
Fixed the Saas buildspec file for changes to the prod helm charts in the DevOps repo (ex: https://github.com/rudderlabs/rudder-devops/pull/4220).
So, now we are upgrading the version both for rudder-transformer and user-transformer services alike.
Also, removed quotes around the version number to avoid confusion.
N/A
=> chore(ci): fix the buildspec file for helm chart changes

src/v0/destinations/clevertap/config.js
> While validating the max batch size, that is, batch limit for user deletion for clever tap we found the limit was 100, not 1000. This PR mainly changes the limit number.
We found this number when we were testing for 1000 records it returned us with message "Max 100 are allowed"
> Fix [#1]()
=> fix(clevertap): correction for the max_batch_size value

test/__tests__/deleteUsers/data/clevertap/handler_input.json, test/__tests__/deleteUsers/data/clevertap/handler_output.json, test/__tests__/deleteUsers/data/clevertap/nw_client_data.json, test/__tests__/deleteUsers/data/engage/handler_input.json, test/__tests__/deleteUsers/data/engage/handler_output.json, test/__tests__/deleteUsers/data/engage/nw_client_data.json
> Added mock test cases for userDeletion
> Fix [#1]()
=> fix: user deletion handlers test cases

src/v0/destinations/clevertap/deleteUsers.js
As parallelizing all the batch deletion requests in Clevertap is resulting in hitting rate limits, the logic is updated to use a for-loop.
N/A
=> fix(destination): avoid parallel delete user requests in clevertap

src/v0/destinations/adobe_analytics/data/AACommonConfig.json, src/v0/destinations/adobe_analytics/transform.js, test/__tests__/data/adobe_analytics_input.json, test/__tests__/data/adobe_analytics_output.json
> We are fixing 2 issues in this PR
> 1. transactionID was being referenced from a wrong property name.
> 2. In our [docs](https://www.rudderstack.com/docs/destinations/streaming-destinations/adobe-analytics/e-commerce-events/#checkout-started:~:text=order_id-,purchaseID/transactionID%20(If%20purchaseId%20or%20transactionId%20is%20not%20present),-Cart%20Opened), we offer setting both purchaseID and transactionID from order_id. This was missing in our instrumentation. 
> Fix [#1]()
=> feat(integration): adobe_analytics-fix typo, add missing mapping

src/v0/destinations/impact_radius/transform.js, src/v0/destinations/impact_radius/util.js, test/__tests__/data/impact_radius.json
Suggested few changes relating to `checkConfigurationError` function (now renamed to `validateConfigFields`).
- Now throwing error in transform.js/ processEvent instead of inside `checkConfigurationError`.
- Now throwing error for all the missing fields at once.
> Fix [#1]()
=> feat: suggested changes to impact radius

src/versionedRouter.js
The default stat tag `implementation` was missing in the router transformation handler. Hence, added, and it defaults to `native`.
In the case of CDK v2, the tag is taken care of in its handler module.
N/A
=> fix: add missing implementation stat tag for router transformation

src/v0/destinations/salesforce/utils.js
The fix is based on the below alert
https://app.squadcast.com/incident/63aee14514525885099aaa23
We are reverting it, as there is a more graceful way of handling `invalid_grant` kind of errors in this block of source-code. Will be raising a fix PR soon enough
> Fix [#1]()
=> fix: revert salesforce fix for undefined access_token

src/v0/destinations/rockerbox/transform.js, test/__tests__/data/rockerbox.json
Updating `isDefinedAndNotNullAndNotEmpty` to `isDefinedAndNotNull` as integer values were ignored by it.
> Fix [#1]()
=> fix: rockerbox empty value check

src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, src/v0/destinations/pinterest_tag/utils.js, src/v0/util/index.js, test/__tests__/data/pinterest_tag_input.json, test/__tests__/data/pinterest_tag_output.json
> 
Pinterest implementation in CDK v2, where returning different value for
-  `em`, the value is `""`
-  `num_items` were missing if there was no product array
- in our JS implementation, we also saw that, if no gender parameter is present, it is returning undefined, so fixed that as well.
> Fix [#1]()
=> fix(CDK v2): editing CDK v2 for pinterest tag for num_items field

src/util/ivmFactory.js, test/__tests__/user_transformation.test.js
> while creation of isolate, make sure to release context in case of error
https://www.notion.so/rudderstacks/Debug-why-transformer-crashes-on-import-error-b35d693b74c6406f920a3c7ce0e48d21
> Fix [#1]()
=> fix(transformation): release isolate in case of error while creating

src/v0/sources/shopify/transform.js, test/__tests__/data/shopify_source_output.json
> We are including the `cart token`, `order token` and `checkout token` in the Context object as well.  This would allow to more easily find the most recent status of any particular cart or order.
> Fix [#1]()
=> feat: shopify - add cart token, order token and checkout token in the Context object

src/v0/destinations/klaviyo/transform.js, test/__tests__/data/klaviyo.json
Skip profile lookup call to check for existing user for rETL events
> Fix [#1]()
=> fix(klaviyo): skip profile lookup call for rETL events

src/util/stats.js
Adding instanceName tag to metrics (to have a unique dimension) so as to deploy a common statsd exporter to all transformer pods rather than sidecar to individual pod
> Fix [#1]()
=> chore: add instanceName tag to statsd metrics

src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, test/__tests__/data/pinterest_tag_input.json, test/__tests__/data/pinterest_tag_output.json
> Pinterest conversion in cdk V2 was not being able to calculate `num_items` for single product elements. `$sum` was not considering product array with single product, as an array. So we had to fix it.
> Fix [#1]()
=> fix(integration): pinterest conversion in cdk v2 returns correct num_items for single product array

src/v0/destinations/klaviyo/config.js, src/v0/destinations/klaviyo/transform.js, src/v0/destinations/klaviyo/util.js, test/__tests__/data/klaviyo.json, test/__tests__/data/klaviyo_router_output.json
Refactor subscribe user flow to stop subscribing user without consent.
- Remove `/members` endpoint request to add the user to list as it doesn't respect double op-in and ignores user consent
- [] Bug fix (non-breaking change that fixes an issue)
- [✅] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Fix [#1]() 
- [✅] Lint rules pass locally
- [✅] The code changed/added as part of this pull request has been covered with tests
- [✅] All tests related to the changed code pass in development
=> fix: refactor subscribe user flow to stop subscribing user without consent

src/cdk/v2/destinations/algolia/procWorkflow.yaml, test/__tests__/data/algolia_input.json, test/__tests__/data/algolia_output.json
=> fix(integration): algolia  in cdk v2 now errors out for non string event names

src/v0/util/index.js, src/versionedRouter.js
Previously we used to support refreshing of oauth token during delivery of event data to destination.
Now, we are trying to support refreshing of oauth token even during transformation as well
https://www.notion.so/rudderstacks/OAuth-Token-expiry-during-transformation-doesn-t-refresh-access-token-c2f5f269455248d0b413a60bcc2951c1
> Fix [#1]()
=> chore: support for refreshing token during transformation

src/v0/destinations/facebook_pixel/data/FBPIXELUserDataConfig.json, src/v0/destinations/facebook_pixel/transform.js, src/v0/destinations/facebook_pixel/utils.js, test/__tests__/data/facebook_pixel_input.json, test/__tests__/data/facebook_pixel_output.json, test/__tests__/data/facebook_pixel_router_input.json, test/__tests__/data/facebook_pixel_router_output.json
> Supporting `postCode` mapping to be in parity with standard Identify spec.
> Fix [#1]()
=> fix(fb pixel): zp mapping and external_id

package-lock.json, package.json, src/util/errorNotifier/bugsnag.js
Added deny paths list functionality to Bugsnag notifier to suppress unwanted errors from warehouse, user transformations etc.
N/A
=> feat: suppress errors from unwanted modules to bugsnag

src/v0/sources/customerio/mapping.json, test/__tests__/data/customerio_source_input.json, test/__tests__/data/customerio_source_output.json
Like the `campaign_id` for Campaigns, or `newsletter_id` for Broadcasts, the `transactional_message_id` is for messages sent via the Transactional Message API.
See: https://www.customer.io/docs/webhooks/#webhook-attributes
> Fix [#1]()
=> feat(customerio): allow for transactional messageid in incoming messages

src/v0/destinations/facebook_pixel/transform.js, test/__tests__/data/facebook_pixel_output.json, test/__tests__/data/facebook_pixel_router_output.json
> 
- actions_source parameter is required in [Facebook Pixel](https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/server-event#action-source)
- if action_source parameter is not present in the request. By default we will set it as '`other`'
> Fix [#1]()
=> fix(fb pixel): add default action source

src/v0/destinations/tiktok_ads_offline_events/transform.js
We are adding optional chaining for phones from user traits.
> Fix [#1]()
=> fix: add optional chaining for phone in tiktok_ads_offline_events

src/v0/destinations/fb_custom_audience/transform.js, test/__tests__/data/fb_custom_audience_router_rETL_input.json, test/__tests__/data/fb_custom_audience_router_rETL_output.json, test/__tests__/fb_custom_audience.test.js
> Check for rETL vdm sources if audience id not present in destination configs then in context.
> Fix [#1]()
=> feat: add audience id for retl sources from context

.github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml, .github/workflows/housekeeping.yml, .github/workflows/prepare-for-dev-deploy.yml, .github/workflows/prepare-for-prod-deploy.yml, .github/workflows/publish-new-release.yml, README.md, package.json
Added support for sending a message to the Slack releases channel whenever a new GitHub release is created.
N/A
=> chore(build): add slack notification support for releases

src/v0/destinations/clevertap/config.js, src/v0/destinations/clevertap/transform.js, test/__tests__/data/clevertap_input.json, test/__tests__/data/clevertap_output.json
> Adding support for an `overrideFields` field in traits, to allow any number of fields that are passed in the `overrideFields` object, to pass without destination transformation into Clevertap `profileData`.
> Fix [#1]()
=> feat: add override support in clevertap

.github/workflows/publish-new-release.yml
- Marked the Slack notification step as non-blocking in case of failures
- Fixed a warning in the Slack notification step
N/A
=> chore: fix slack notification step in publish workflow

src/v0/destinations/adobe_analytics/config.js, src/v0/destinations/adobe_analytics/transform.js, test/__tests__/data/adobe_analytics.json
- allow event names from config without forced lowercasing.
- disable lowercasing explicitly while hashing arrays
> Fix [#1]()
=> fix: allow event names without forced lowercasing, disable lowercasing

.gitignore, src/controllers/destination.ts, src/services/source/nativeIntegration.ts
Added missed stats to dest transformer controller also added stats for source transform failure
event counts, onboarded dist to .gitignore
=> fix: added missed stats to dest transform controllers

src/v0/sources/shopify/util.js
> Making "shopify-admin" as the default value for anonymousId 
> Fix [#1]()
=> fix: anonymous id default value 

sample.env, src/util/redisConnector.js, src/v0/sources/shopify/util.js, test/__tests__/data/redis/shopify_source.json
> We are changing the behaviour of default case of mapping the `anonymousId` as there are certain events for which `cartToken` is not present and so we are now checking there is `userId` or not present and mapping `userId` as `shopify-admin` if `userId` is not present. 
Added some metrics for data transaction failure between transformer and redis. 
Added `userName` in `redisConnector`
> Fix [#1]()
=> fix: shopify default check for anonymousId

.github/workflows/build-pr-artifacts.yml, .github/workflows/build-push-docker-image.yml, .github/workflows/draft-new-release.yml, .github/workflows/housekeeping.yml, .github/workflows/prepare-for-dev-deploy.yml, .github/workflows/prepare-for-prod-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml, .github/workflows/publish-new-release.yml, .github/workflows/report-code-coverage.yml, .github/workflows/test.yml
Replaced `local` with `gha` (GitHub Actions) cache in Docker build steps.
Also, refactored the workflows to move redundant steps into a workflow.
Additional changes:
- https://github.com/rudderlabs/rudder-transformer/pull/2069
N/A
=> chore(cicd): replace local with gha cache in build steps

src/v0/destinations/google_adwords_offline_conversions/networkHandler.js, test/__tests__/data/google_adwords_offline_conversions_proxy_input.json
In Google ads offline conversion, we are lower casing the custom variable before comparing it with the event properties. We are fixing this with this pr.
> Fix [#1]()
=> fix: check event properties without making them to lower case

src/v0/destinations/braze/util.js
Fix for router transform batching logic to correctly add metadata array to router response from transformer
> Fix [#1]()
=> fix: batch metatdata count

src/v0/destinations/facebook_pixel/transform.js, src/v0/destinations/facebook_pixel/utils.js, test/__tests__/data/facebook_pixel_output.json
> We are removing the property mapping that was mandatory in order to send the mapped properties here inside Other Standard events of out FB Pixel integration.
Removing this, will bring standard events in line with custom events, in terms of properties being sent along with the event.
> Fix [#1]()
=> feat: remove custom property dependency for fb pixel

src/cdk/v1/handler.js, src/services/destination/cdkV1Integration.ts, test/__tests__/integration/data_scenarios/cdk_v1/failure.json
Currently the error handling is not correct for CDKV1 destinations. Any data-validation or instrumentation errors are getting categorised as transformation errors(that are intended to tell us if the error is unhandled). With this PR, we are looking to fix it.
Task: https://www.notion.so/rudderstacks/Error-Handling-for-CDKV1-destinations-using-new-routes-d01a35e8cc684257a7b92c84cceb1c07?pvs=4
**Note**: This is happening for new routes only. For older routes, things are working well
> Fix [#1]()
=> fix(cdkv1): error handling for cdkv1 destinations

jest.config.js, src/util/error-extractor/index.js, src/util/error-extractor/index.ts, src/util/error-extractor/types.ts, src/util/redis/redisConnector.test.js, src/v0/destinations/facebook_pixel/networkHandler.js, test/__mocks__/data/facebook_pixel/proxy_response.json, test/__tests__/azure_synapse.test.js, test/__tests__/bq.test.js, test/__tests__/clickhouse.test.js, test/__tests__/data/facebook_pixel_proxy_input.json, test/__tests__/data/facebook_pixel_proxy_output.json, test/__tests__/marketo_bulk_upload.test.js, test/__tests__/mssql.test.js, test/__tests__/postgres.test.js, test/__tests__/rs.test.js, test/__tests__/s3_datalake.test.js, test/__tests__/snowflake.test.js, test/__tests__/warehouse.test.js
- made use of the typescript error extraction class
- updated logic to throw unhandled status code error(in a different way without using `UnHandledStatusCodeError` class)
- added test-cases for the unhandled status code case
- updated the jest configuration to support typescript in javascript
- updated couple of test-files to move from implicit declaration to explicit declaration
> Fix [#1]()
=> fix: error extraction migrated to typescript

.github/workflows/prepare-for-prod-deploy.yml
We are forcefully updating the docker image repository to `rudderstack/rudder-transformer` in deployment files on release
> Fix [#1]()
=> chore: update docker image repository in deployment yamls on release

src/v0/destinations/klaviyo/transform.js, src/v0/destinations/klaviyo/util.js, test/__tests__/data/klaviyo.json
Add check for `listId` before creating the payload for subscribe endpoint if the subscribe flag is true(user wants to subscribe the profile)
> Fix [#1]()
=> fix(klaviyo): add check for listId for subscribe

src/warehouse/util.js, test/__tests__/warehouse.test.js
> Getting for following error `RangeError · Invalid time value` for messagebird when the timestamp is coming as `-0001-11-30T00:00:00+0000`.
> Fix [#1]()
=> fix: error handling for valid timestamp

src/cdk/v2/destinations/optimizely_fullstack/procWorkflow.yaml, test/__tests__/data/optimizely_fullstack.json
> 
- Optimizely drops the event if empty project id sent in payload (e.g. project_id = ""). Project id is optional parameter.
- If empty project id is coming from webapp, `removeUndefinedAndNullValues` is not removing it from the payload sent to optimizely.
- There is one more utility `removeUndefinedNullEmptyExclBoolInt` that will remove empty values from the payload sent to optimizely.
> Fix [#1]()
=> feat(optimzely_fullstack): removed empty values from common payload

src/cdk/v2/destinations/bingads_audience/procWorkflow.yaml, test/__tests__/data/bingads_audience.json
> Previously if we would have sent single user data in list data, it was returning an object. But now, for all conditions it will return array
> Fix [#1]()
=> fix: bingads audience list data retuns array for single user

src/cdk/v2/destinations/algolia/procWorkflow.yaml, test/__tests__/data/algolia_router_input.json, test/__tests__/data/algolia_router_output.json
The native transformation for algolia is actually capturing the objectIds from either `properties.objectIds` or `properties.products[].objectId`.
But in the cdkv2 transformation, even though `properties.objectIds` is present since `properties.products` doesn't contain `objectId` inside any of it's elements & a splice is being done to extract `20` elements, the `TypeError` is being thrown which is preventing transformation
Through this PR, we want to change the behaviour such that when `properties.products` contains `objectId` prefer it. If for some reason we are not able to extract objectIds from `properties.products` then make use of `properties.objectIds`
> Fix [#1]()
=> fix(algolia): cdkv2 transformation

src/v0/destinations/mp/transform.js, src/v0/util/index.js, test/__tests__/data/mp_input.json, test/__tests__/data/mp_output.json
> For group call in mixpanel if [group key](https://github.com/rudderlabs/rudder-transformer/blob/c91dadc2cf3eaddceefc83e3b9b8f08529a7fd4e/src/v0/destinations/mp/transform.js#L301) is not provided then [processGroupEvents](https://github.com/rudderlabs/rudder-transformer/blob/c91dadc2cf3eaddceefc83e3b9b8f08529a7fd4e/src/v0/destinations/mp/transform.js#L288C7-L288C25) function is returning an empty array to caller function. Which in turn returns a response with "batchedRequest": [] with statusCode: 200 after transformation to server.
Instead of returning empty array, Added a check on group key and failed the event accordingly while doing the transformation.
> Fix [#1]()
=> fix: mixpanel group call

src/services/trackingPlan.ts
hv_request_size is histogram but used as couter.
Fixes this error: Counter metric hv_request_size failed with error TypeError: metric.inc is not a function. Value: 2223
=> fix: incorrect usage of histogram as counter

src/v0/destinations/facebook_pixel/data/FBPIXELUserDataConfig.json, test/__tests__/data/facebook_pixel_input.json, test/__tests__/data/facebook_pixel_output.json
For some reason the name property is being sent as false (boolean). That data-type does not have split method defined in Javascript. Which is causing this issue
Bugsnag: https://app.squadcast.com/incident/64991c6372ca037dfb591a1a
Notion: https://www.notion.so/rudderstacks/Bugsnag-Facebook-Pixel-name-is-sent-as-boolean-but-expected-to-be-string-4f3ce02a094c4996865c7d00d7b4a956?pvs=4
> Fix [#1]()
=> fix(facebook_pixel): name conversion to string

src/util/prometheus.js, src/v0/sources/shopify/util.js
Sending redis failure alert always. 
Reason: For redis failure alerts to work properly, we need to init the metric on server start. Instead of initing, sending the metric always. There shouldn't be any impact as such.
> Fix [#1]()
=> chore: send redis failure metric always

src/v0/destinations/facebook_pixel/transform.js, test/__tests__/data/facebook_pixel_output.json, test/__tests__/data/facebook_pixel_router_output.json
> Updating the graph API version used in the facebook pixel integration to the latest one, v17.0
> Fix [#1]()
=> chore: update facebook pixel graph api version to v17.0

.github/workflows/prepare-for-prod-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml
Parallelising at github action level for ut & dt image builds so that dt release doesn't get blocked
> Fix [#1]()
=> chore: ut dt release builds separation

src/v0/destinations/mp/util.js, src/v0/destinations/mp/util.test.js
refactor: combineBatchRequestsWithSameJobIds
implemented as combineBatchRequestsWithSameJobIds2
> Fix [#1]()
=> refactor: combine batch requests with same job ids

src/v0/destinations/mp/transform.js, test/__tests__/data/mp_input.json, test/__tests__/data/mp_output.json
> 
- Add the validation when previousId and userId are the same
- Mapping userId with `distinctId` and (previousId or anonymousId) with `alias` property
> Fix [#1]()
=> feat(mixpnel): update alias mapping and add validation

src/v0/destinations/marketo/util.js, test/__mocks__/data/marketo/response.json, test/__tests__/data/marketo_input.json, test/__tests__/data/marketo_output.json
> Solution for #2422 in which when `expires_in = 0` sec for get `auth_token` request
> Fix [#1]()
=> fix: handle marketo auth token response when expires_in is 0 sec 

src/v0/sources/shopify/config.js, src/v0/sources/shopify/shopify_redis.util.test.js, src/v0/sources/shopify/util.js
> Resolves INT-164
We are receiving `cart_update` event generated by rudderstack tracker before `rudderIdentifier` could reach us from tracker which is resulting in no redis mapping and we are assuming the event to be valid but since it is a rudderstack generated event it should not be a valid event and we should drop it.
To deal with such scenarios we are introducing some more check which will basically check the following conditions and if all true then will drop the `cart_update` event.
1. Nothing is retrieved from redis for particular cart_token.
2. `line_items` array is empty
3.  Difference between cart `updated_at` and `created_at` less than decided time limit ( currently 10 sec)
> Fix [#1]()
=> fix: valid cart_update event extra check

src/adapters/network.js, src/services/destination/nativeIntegration.ts
The `destType` was coming out to be empty even though we had information about the destination-type
> Fix [#1]()
=> fix(INT-296): add destType labels for proxy destinations

src/routes/index.ts
> Enable Swagger by Default, Remove `ENABLE_SWAGGER` Env.
> Fix [#1]()
=> chore: remove ENABLE_SWAGGER env

src/v0/destinations/salesforce/transform.js
When the external identifier is not present, we are throwing an error instead of inserting it automatically. This PR aims to fix it
> Fix [#1]()
=> fix: salesforce upsert when identifier is not present

src/v0/destinations/intercom/config.js, src/v0/destinations/intercom/data/INTERCOMTrackConfig.json, src/v0/destinations/intercom/transform.js, src/v0/destinations/intercom/util.js, src/v0/destinations/intercom/util.test.js, test/__tests__/data/intercom_input.json, test/__tests__/data/intercom_output.json
> Resolves INT-266
- Add flatten json utility for `metadata` in track call and `custom attributes` in identify call.
- Excludes the flattening of event metadata types such as **richLink** and **monetaryAmount**. Which are supported as JSON object in intercom
- properties are mapped with metadata and traits are mapped with custom attributes
> Fix [#1]()
=> fix(intercom): flatten metadata and custom attributes

src/v0/destinations/customerio/util.js, src/v0/destinations/customerio/util.test.js, test/__tests__/data/customerio_input.json, test/__tests__/data/customerio_output.json
> CustomerIo accepts either `id`, `email` or `cio_id` as identifiers but currently we were only sending `id` mapped to `userId` but now we are looking for `email` as well and if its available we are using it as identifier instead of dropping the event. 
> This is done for identify and merge calls and identified track and device events.
> Extended support to update identifiers using `cio_id` fetched from CustomerIO dashboard
> Fix [#1]()
=> feat(INT-162): adding email as fallback to userId

src/util/myAxios.js, src/util/prometheus.js, src/v0/destinations/braze/deleteUsers.js
> Introducing `endpointPath` label for `outgoing_request_latency`, so as to gain more visibility on the API endpoints with the most latency.
For now, Braze is introduced with this change.
> Fix [#1]()
=> chore(INT-377): introduce endpointPath label for outgoing_request_latency stat in Braze

src/cdk/v2/destinations/pinterest_tag/rtWorkflow.yaml
> We had added support for sending test events in Pinterest. We have fixed the router flow here.
> Fix [#1]()
=> fix: pinterest tag support test event rt flow

src/v0/destinations/braze/transform.js
- enable merge_user behaviour to merge anonymous user fields to the identified user.
- for more info refer [here](https://www.braze.com/docs/api/endpoints/user_data/post_user_identify/#request-parameters)
> Fix [#1]()
=> fix(braze): enable merge behaviour to stitch user data

src/v0/destinations/factorsai/transform.js, test/integrations/destinations/factorsai/data.ts
> Resolves INT-463
FactorsAI expect to see a type property in the JSON with the value page for all page events and currently our integration is not sending this value. We are fixing this here.
> Fix [#1]()
=> fix: missing type for page and group calls

src/cdk/v2/destinations/optimizely_fullstack/procWorkflow.yaml, test/__tests__/data/optimizely_fullstack.json
> Resolves INT-556
Fetching the datafile for secure environment with access token is supported using SDK only in optimizley. Removing the handling of secure environment in transformer
> Fix [#1]()
=> fix: remove secure environment for datafile call

src/v0/destinations/salesforce/transform.js, src/v0/destinations/salesforce/utils.js, test/__mocks__/data/salesforce/proxy_response.json, test/__tests__/data/salesforce_proxy_input.json
> Fix the type comparison logic of externalId to compare strings, in compliance to the string returned by Salesforce. We are also retrying errors related to row locking now.
> Fix [#1]()
=> fix: type issue in lookup via externalid, row lock error as retryable

src/v0/destinations/tiktok_ads/data/TikTokTrack.json
=> feat(INT-580): messageId to event_id mapping support

test/integrations/destinations/firehose/processor/data.ts
Migrating testcases of FIREHOSE to new format
> Fix [#1]()
=> refactor: migrate firehose to component tests

test/integrations/destinations/fb/processor/data.ts, test/integrations/destinations/fb/router/data.ts
Migrating testcases of FB to new format
> Fix [#1]()
=> refactor: migrate fb to component tests

test/integrations/destinations/heap/processor/data.ts, test/integrations/destinations/heap/router/data.ts
Migrating testcases of HEAP to new format
> Fix [#1]()
=> refactor.migrate heap to component tests

src/v0/destinations/twitter_ads/transform.js, test/__tests__/data/twitter_ads.json
> we seem to be hashing `twclid` though the api docs say hashing is not required : [https://developer.twitter.com/en/docs/twitter-ads-api/measurement/web-conversions/conversion-api#:~:text=Preparing%20Iden[…]onversion%20Events%C2%A0](https://developer.twitter.com/en/docs/twitter-ads-api/measurement/web-conversions/conversion-api#:~:text=Preparing%20Identifiers%20for%20Conversion%20Events%C2%A0)
> Fix [#1]()
=> fix: remove hashing on twclid for twitter ads

src/middleware.js
> PR https://github.com/rudderlabs/rudder-transformer/pull/2540 introduced lint & sonar issues on src/middleware.js, this PR is to fix those
> Fix [#1]()
=> chore: fix sonar and lint issues

src/v0/destinations/redis/transform.js, test/__tests__/data/redis_output.json
while preparing the event for profiles<>redis store
> Fix [#1]()
=> fix(redis): add destination_id in the key

src/v0/destinations/customerio/transform.js, test/__tests__/data/customerio_input.json
> Previously we were having a flag to check if datacenter is `EU` but now we are going with a drop down menu to select available datacenter from and falling back to previous flag in case new one is not available
> Fix [#1]()
=> fix(INT-523): replaced flag with dropdown for datacenter selection

src/v0/destinations/marketo/util.js, test/__mocks__/data/marketo_static_list/proxy_response.json, test/__tests__/data/marketo_static_list_proxy_input.json, test/__tests__/data/marketo_static_list_proxy_output.json
> We are not handling the `skipped` (code: 1015) and `removed` statuses properly due which for these even if the calls are successful we are returning as error 
> Fix [#1]()
=> fix(INT-339): marketo response handler to handle static list removed and skipped statuses

.github/workflows/prepare-for-prod-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
> Seperate build steps for ruddestack and rudderlabs repo for prod and staging builds.
> Fix [#1]()
=> fix: seperate build steps for ruddestack and rudderlabs repo

.github/workflows/prepare-for-prod-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
> As we depricated usage of rudderlabs org for transformer images, we are removing the concerned workflows 
> Fix [#1]()
=> chore: remove rudderlabs org from image workflows

src/v0/destinations/bqstream/transform.js, src/v0/destinations/bqstream/util.js, src/v0/destinations/bqstream/util.test.js, test/integrations/destinations/bqstream/router/data.ts
> resolves INT-389
Fixing event ordering issue for BQ stream.
Dividing events to different user journeys and keeping the order of the events intact.
original PR: https://github.com/rudderlabs/rudder-transformer/pull/2558
> Fix [#1]()
=> fix: bqstream event ordering fix

src/v0/destinations/mp/transform.js
> Add null/undefined safety check for properties.
> Fix [#1]()
=> fix(mixpanel incremental properties): add check for undefined properties

src/v0/destinations/personalize/scripts/create-trackingid.js
Organised code to use promises and async await for better clarity.
> Fix [#1]()
=> fix: use promise for prompts in personalize create tracking script

src/v0/destinations/hs/util.js, test/__tests__/data/hs_input.json, test/__tests__/data/hs_output.json
>Resolves INT-679
We are adding a validation for hubspotEvents which is the Event name mapping on the dashboard. If we are getting empty mappings for track events we are discarding that event.
> Fix [#1]()
=> fix(hubspot): add validation for hubspotEvents

src/v0/util/index.js, src/v0/util/index.test.js
> Resolves INT-596
- hasCircularReference: Added a new utility to identify circular references within the payload.
- flattenJson: In the flattenJson utility, Added the `hasCircularReference` check to identify and handle circular references within the payload.
> Fix [#1]()
=> feat: add circular reference check in flattern json

src/util/prometheus.js, src/v0/destinations/iterable/data/IterableTrackConfig.json, src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json, test/__tests__/data/iterable.json
As part of this hotfix, we are fixing the definition of couple of critical stats for tracking plan in the prometheus.js file to align with the stat fired from the service. The consequence of the issue is that we have critical P0 alerts which are not getting fired for the DM team.
Ticket: https://linear.app/rudderstack/issue/DAT-404/hotfix-for-the-user-transformer-service
> Fix [#1]()
=> fix(dm): updated the stats definition for the tracking plan service

src/v0/destinations/criteo_audience/networkHandler.js, test/__mocks__/data/criteo_audience/proxy_response.json, test/__tests__/data/criteo_audience_proxy_input.json, test/__tests__/data/criteo_audience_proxy_output.json
> #2685 continued
resolves INT-759
> Fix [#1]()
=> fix: criteo_aud auth_token expire code incorporated

src/v0/destinations/kafka/transform.js, test/__tests__/data/kafka_batch_input.json, test/__tests__/data/kafka_batch_output.json, test/__tests__/kafka.test.js
Resolves INT-392
- Kafka's final response wasn't containing the `statusCode` and `batched` values. This PR adds it.
- Old response structure :
`{ batchedRequest: [], metadata: [], destination: {}}`
- New Rsponse structure :
`{ batchedRequest: [], metadata: [], destination: {}, statusCode: "", batched: ""}`
> Fix [#1]()
=> fix(kafka): add status code & batched value in response structure

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/criteo_audience/networkHandler.js, test/__mocks__/data/criteo_audience/proxy_response.json, test/__tests__/data/criteo_audience_proxy_input.json, test/__tests__/data/criteo_audience_proxy_output.json
=> chore(release): pull hotfix-release/v1.44.1 into main

src/controllers/eventTest.ts, src/services/eventTest/eventTester.ts
In eventTester.ts file we were declaring some variables but not initializing those. With this fix, we are initializing such variables.
> Fix [#1]()
=> fix: create instance of transformedObj

src/v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json, src/v0/destinations/campaign_manager/transform.js, src/v0/destinations/campaign_manager/util.js, src/v0/destinations/campaign_manager/util.test.js, test/__tests__/data/campaign_manager.json, test/__tests__/data/campaign_manager_router_input.json, test/__tests__/data/campaign_manager_router_output.json
> added matchId check and timestamp conversion
> Fix [#1]()
=> fix: added matchId check and timestamp conversion

src/v0/destinations/facebook_conversions/utils.js
`appData.extinfo` is an array of strings. Setting empty string `""`, if at any index in `appData.extinfo`, value is undefined as it is not sent in the event. These values are not required but FB is expecting them as empty strings.
Note: `appData.extinfo` is being populated from config mapping. `metadata: { defaultValue: "" }` is not working, once setting empty string as default is supported, this can be removed
> Fix [#1]()
=> feat: setting empty string as default if app event params are not present

test/integrations/component.test.ts, test/integrations/testUtils.ts
Now we can use following commands while running component tests:
`npm run test:ts -- component  --destination=adobe_analytics`
`npm run test:ts -- component  --destination=adobe_analytics --feature=router`
`npm run test:ts -- component  --destination=adobe_analytics --feature=router --index=0`
> Fix [#1]()
=> feat: add support filtering component tests by feature and index

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/braze/transform.js, src/v0/destinations/mp/transform.js, src/v0/destinations/mp/util.js, src/v0/destinations/mp/util.test.js, src/v0/util/constant.js, src/v0/util/index.js, test/integrations/destinations/mp/router/data.ts
=> chore(release): pull hotfix-release/v1.46.1 into main

src/adapters/utils/networkUtils.js, src/v0/destinations/salesforce/utils.js, test/__mocks__/data/salesforce/proxy_response.json, test/__tests__/data/salesforce_proxy_input.json, test/__tests__/data/salesforce_proxy_output.json
> Resolves INT-852
We are getting multiple alerts over many days for `ECONNABORTED` error which is some network error form salesforce and should be retried from our end. 
This PR has a check to convert this to `retryable` error
> Fix [#1]()
=> fix: salesforce: handle ECONNABORTED error

CHANGELOG.md
=> chore: update changelog for pinterest custom event name support

CHANGELOG.md, package-lock.json, package.json, src/util/customTransformer-faas.js, src/util/openfaas/index.js, src/v0/util/index.js
=> chore(release): pull hotfix-release/v1.48.0 into main

src/v0/destinations/adobe_analytics/transform.js, test/__tests__/data/adobe_analytics.json
Resolves INT-980
Disallow null and undefined values from being passed to Adobe's XML payload
> Fix [#1]()
=> fix: add check to remove null and undefined properties before sending

src/v0/sources/shopify/util.js
> Fix the condition for `shopify_redis_no_val` metric ->  no data returned from redis for a key
> Fix [#1]()
=> fix: shopify redis metric when there is no data returned for a key

src/v0/destinations/am/transform.js, test/__tests__/data/am_output.json
> We introduced a change on 07/11/23 where in page calls were sent as `Viewed(single space)Page` instead of `Viewed(double space)Page` and similar for screen calls. Since this caused a breaking change we are reverting this fix
> Fix [#1]()
=> revert: fix: amplitude page and screen call containg double spaces

src/util/openfaas/index.js
We were getting notified for faas timed out alerts in the system because it was getting captured with status code 400 inspite of status code 504 timedout. The error itself is a valid error and doesn't need to raise an alert on.
The fix raises the error with code as well to allow the stat to capture the code and then we will make changes in alert to bypass this code i.e. `504`.
Fix DAT-508 https://linear.app/rudderstack/issue/DAT-508/python-transformations-high-internal-error-count
=> chore: capture correct status code on faas pod time out

src/v0/destinations/salesforce/networkHandler.js, src/v0/destinations/salesforce/utils.js, src/v0/destinations/salesforce_oauth/networkHandler.js, test/__tests__/facebook_conversions.test.js, test/integrations/destinations/salesforce/dataDelivery/data.ts
> Salesforce network handler was not sending `authorizationFlow` variable. We have added logic to set it. Also handled it specifically for salesforce ouath version, inside the `responseHandler` function
> Fix [#1]()
=> fix: salesforce transformer proxy response handling issue for authorization flow

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/config.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, test/__tests__/data/braze_input.json, test/__tests__/data/braze_output.json
Adding support for `properties` fields for Purchase events to Braze [ref](https://www.braze.com/docs/api/objects_filters/purchase_object/)
The `properties` field is mapped with all the extra fields perent in each of the `product` elements present in `Order Completed` event.
This change introduces additional data to be sent into Braze
Refer to linear ticket INT-1076 for further details
> Fix [#1]()
=> fix: add support for custom properties for braze purchase events

src/services/userTransform.ts
When sending transformation requests from DMT service, we found that in some of the responses, we are not getting the workspaceId back to the caller. This is generating stats with empty workspaceId's in it and therefore, raising this PR to fix it.
Fixes: DAT-677
> Fix [#1]()
=> fix(dm): add workspaceId in common metadata to be returned to the callers

src/v0/destinations/braze/transform.js
Add null check in populateCustomAttributesWithOperation
Found logs for this error:
Failure occurred during custom attributes operations TypeError: Cannot read properties of null (reading 'update')
so this change is to fix this error.
Fixes INT-1177
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: missing null check in braze populateCustomAttributesWithOperation

src/v0/destinations/active_campaign/transform.js, test/integrations/destinations/active_campaign/processor/data.ts
Whenever there are node errors like EAI_AGAIN, ECONNABORTED etc,. the error handler is not able to handle the error properly.
Through this PR we aim to fix it.
Resolves INT-1157
N/A
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: active_campaign error handler

src/v0/destinations/adobe_analytics/utils.js
Add string type check to `escapehtml()` in adobe analytics.
If the pull request is a **bug-fix**, **enhancement** or a **refactor**, please fill in the details on the changes made. **bug-fix**
escapehtml() fails for inputStrings of non string types
escapehtml() will ignore non string values.
N/A
N/A
N/A
N/A
N/A
<hr>
=> chore: add stringtype check to escapehtml in adobe

src/v0/util/errorTypes/filteredEventsError.js, src/v0/util/errorTypes/transformerProxyError.js, src/v0/util/index.js, src/v0/util/index.test.js, test/__tests__/data/braze_router.json
In `FilteredEventsError` , we are using `BaseError` from `src/v0/util/errorTypes/base.js`
And in `generateErrorObject` we are using `instanceof` on `BaseError` from `integrations-lib`. Hence `instanceof` condition is failing & no matter what specific errorCategory is provided in the error, it is getting converted to `transformation` errorCategory.
This PR aims to fix this inconsistency
Resolves INT-1187
- We have also fixed the import problem in `TransformerProxyError` class as well
- Used `?.` optional-chaining for evaluating if features contains filterCode feature …
=> fix: braze transformation error due to wrong import

CHANGELOG.md, package-lock.json, package.json, src/controllers/delivery.ts, src/features.json, src/services/destination/nativeIntegration.ts, src/services/destination/postTransformation.ts, src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/util.js, test/integrations/destinations/braze/dataDelivery/data.ts
=> chore(release): pull hotfix-release/v1.52.2 into main

src/v0/destinations/braze/transform.js, test/__tests__/data/braze_input.json, test/__tests__/data/braze_output.json
email validation for braze if integer
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: email validation for braze

jest.config.js, jest.config.typescript.js, jest.default.config.js, package-lock.json, package.json
fix: pr conflicts in back merge https://github.com/rudderlabs/rudder-transformer/pull/2983
N/A
N/A
N/A
N/A
<hr>
=> fix: pr conflicts in back merge

src/cdk/v2/destinations/ortto/procWorkflow.yaml, test/integrations/destinations/ortto/processor/data.ts
When there is no phone field provided we were previously sending `phn:phone ={}` which was resulting in error as ` empty phone value for phn::phone"`.
In this PR we have put a check that if no phone field is provided we won't map it and there won't be any phn:phone field getting delivered to ortto.
Resolves INT-1293
This change will result in successful delivery of jobs when there is no phone provided in the payload
We won't be mapping `phn:phone `field even there is nothing to map
N/A
N/A
N/A
<hr>
=> fix: ortto remove phn:phone field if no phone is there in payload

src/cdk/v2/destinations/the_trade_desk/utils.js, src/cdk/v2/destinations/the_trade_desk/utils.test.js, test/integrations/destinations/the_trade_desk/router/data.ts
Updated the **enrichTrackPayload** util to handle custom events 
Resolves INT-897
N/A
N/A
N/A
N/A
<hr>
=> fix: trade desk enrichTrackPayload  util

src/v0/destinations/am/transform.js, test/apitests/data_scenarios/destination/batch/failure_batch.json, test/integrations/destinations/am/batch/data.ts
- Converted the metadata in the output to an array for the Amplitude batch endpoint.
- Updated the test cases to replace "job_id" with "jobId" for consistency across all destinations.
Resolves INT-1383
N/A
N/A
N/A
N/A
<hr>
=> fix: amplitude batch output metadata

README.md
We recently moved docker org from `rudderlabs` to `rudderstack`. This PR adds warning about this change in docker image url. This will help avoid confusion similar to #3081
=> chore: add docker image change announcement in readme

src/v0/destinations/af/transform.js, test/integrations/destinations/af/processor/data.ts
send properties under eventValue at root level, driving this via a config to maintain backward compatibility.
Resolves INT-1431
N/A
N/A
N/A
N/A
<hr>
=> fix: add support of placing properties at root in af

src/v0/destinations/hs/util.js, src/v0/util/index.js, test/integrations/destinations/hs/processor/data.ts
convert to string from null in hs
Resolves INT-1531
N/A
N/A
N/A
N/A
<hr>
=> fix: convert to string from null in hs

src/v0/destinations/marketo_bulk_upload/transform.js, test/integrations/destinations/marketo_bulk_upload/processor/data.ts
A user was facing problem while sending null value and 0 as we were checking existence of a trait using if ( <trait-property>). Hence we are using isDefined util function that just omits undefined value.
Resolves INT-1677
N/A
N/A
N/A
N/A
<hr>
=> fix: marketo bulk upload zero and null value allowed

src/v0/destinations/adobe_analytics/transform.js, src/v0/util/index.js, src/v0/util/index.test.js
Added a util function to ease the process of validating parameters and conversion to string.
Added util to check for 
1. event mandatory ?
2. event exists ?
3. event exists & not object
4. lowercase conversion
N/A
N/A
N/A
N/A
<hr>
=> fix: event fix and added utility

src/util/prometheus.js, src/util/redis/redisConnector.test.js, src/util/redis/testData/shopify_source.json, src/v0/sources/shopify/shopify_redis.util.test.js, src/v0/sources/shopify/transform.js, src/v0/sources/shopify/util.js
Fixed labels not present in prometheus metrics related to
- shopify_redis*
- get_libraries_code_time
Resolves INT-1772
N/A
N/A
N/A
N/A
<hr>
=> fix: label not present in prometheus metrics

.github/workflows/dt-test-and-report-code-coverage.yml
Coverage report for js tests were not getting sent to codecov as `codecov_token` was not present. Through this PR, we are looking to fix it.
Resolves INT-772
N/A
N/A
N/A
N/A
<hr>
=> fix: upload js coverage to codecov

src/cdk/v2/destinations/movable_ink/procWorkflow.yaml, src/cdk/v2/destinations/movable_ink/utils.js, test/integrations/destinations/movable_ink/processor/validation.ts
Resolves INT-1737
N/A
N/A
N/A
N/A
<hr>
=> chore: add event validation for movable ink destination

.github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
Fix deployment conflicts.
N/A
N/A
N/A
N/A
<hr>
=> chore: fix deployment conflicts

src/cdk/v2/destinations/linkedin_ads/rtWorkflow.yaml, src/cdk/v2/destinations/linkedin_ads/utils.js
we were not handling the scenario where no successful events will be present. Hence raising the PR
N/A
N/A
N/A
N/A
<hr>
=> chore: no success should return empty array for linkedin ads

src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js, src/v0/destinations/marketo_bulk_upload/util.js
If any data fails ( warning or failure ), which eventually activates the fetch job status route, we do a line-by-line data type match to find the warnings beforehand to reduce dependency on the clumsy error response that Marketo sends.
In our previous implementation, we also considered the data with null values in this data matching operation, which led to unwanted failures for even those data points where the user chose not to send any data, rather sending a `null` value. 
That is why we are checking if the data that the user sent, is defined and not null, then only to perform the data type match check.
Resolves INT-1872
N/A
N/A
N/A
N/A
@coderabbitai …
=> fix: marketo bulk ignore null while checking data type mismatch

src/v0/util/index.js, src/v0/util/index.test.js
Solution of bugsnag error 
Resolves INT-1986
N/A
N/A
Change is `extractCustomField` to solve bugsnag error
N/A
<hr>
=> fix: adding check for reserved key words in extract custom fields 

src/util/openfaas/faasApi.js, src/util/openfaas/index.js, test/__tests__/user_transformation.test.js
We recently bought license for openfaas standard which brings in host of benefits like autoscaler and better dashboards. This allows us to save a lot of cost when deploying openfaas stack. This change allows your UT service to be pro compliant by:
1. Introducing more labels on the UT pods needed by the pro setup
2. Allowing to pass basic auth credentials in request being sent to gateway pods.
These changes are backward compatible.
Fixes DAT-1093
N/A
N/A
N/A
N/A
<hr>
=> chore: setup transformer code with openfaas pro deployment changes

src/v0/destinations/hs/HSTransform-v2.js, src/v0/destinations/hs/config.js, src/v0/destinations/hs/util.js, src/v0/destinations/hs/util.test.js, test/integrations/destinations/hs/network.ts, test/integrations/destinations/hs/router/data.ts
For Hubspot we are making a search call to fetch the already existing contacts, but we are making this call using only  identifier and not with the secondary property for that identifier.
Example for `email` as identifier: `hs_additonal_emails` is the secondary property, these both can not be duplicate.
Using only email property for search API we won't get the records having that `email` in `hs_additional_emails` hence when we try to create one record we get error for duplicate records.
This PR is to start supporting secondary property as well for searching criteria
Resolves INT-1879
N/A
N/A
N/A
N/A …
=> fix: hubspot: search for contact using secondary prop

src/v0/destinations/hs/util.js
Suppose we have `hs_additonal_emails` as `abc@e.com;cdf@e.com;k@w.com` and our email is `c@e.com` then `hs_additonal_emails.includes(email)` will return true which is wrong.
Hence now we are splitting the string into valid email emails separting them with `;` and after we get an array of list we are checking if a particular email is present in that list
N/A
N/A
N/A
N/A
<hr>
=> fix: hubspot: hs_additional_email comparision logic

src/v0/destinations/awin/utils.js
made the product_id mapping as it is existing in root level.
Ref: https://www.rudderstack.com/docs/destinations/streaming-destinations/awin/#supported-mappings:~:text=properties.order_id%0Aproperties.orderId%0Aproperties.orderReference,orderReference
N/A
N/A
N/A
N/A
<hr>
=> fix: awin product_id mapping backward compatible

src/v0/destinations/hs/HSTransform-v2.js, test/integrations/destinations/hs/processor/data.ts, test/integrations/destinations/hs/router/data.ts
As we are considering hs_object_id as an identifier field through integrations-info it is being added to traits. But we can't update this field as it is a read-only field. So moved, adding identifier field to traits when we are creating an object from the common section. And it is also not needed when we are updating the object. The identifier field is only used for getting the valid object id from Hubspot.
Resolves INT-1996
N/A
N/A
N/A
N/A
<hr>
=> feat: remove redundant data from traits in hubspot

src/cdk/v2/destinations/bloomreach/procWorkflow.yaml, src/cdk/v2/destinations/movable_ink/procWorkflow.yaml, test/integrations/destinations/bloomreach/processor/page.ts, test/integrations/destinations/bloomreach/processor/validation.ts, test/integrations/destinations/movable_ink/processor/identify.ts
Checking empty userId with `??` is giving wrong result for empty userId `userId= ""` in payload. Updated the `movable ink` and `bloomreach` destination to use `|| `operator to check for truthy values for userId.
Resolves INT-2047
N/A
N/A
N/A
N/A
<hr>
=> fix: handle empty userId (movable ink, bloomreach)

src/cdk/v2/destinations/algolia/procWorkflow.yaml, src/v0/destinations/algolia/config.js, src/v0/destinations/algolia/data/AlgoliaTrack.json, src/v0/destinations/algolia/transform.js, src/v0/destinations/algolia/util.js, test/integrations/destinations/algolia/processor/data.ts
Adding following supports :
- Conversion subTypes ([link](https://www.algolia.com/doc/rest-api/insights/#method-param-eventsubtype)). Subtype of the event. For conversion events either `addToCart`, or `purchase`. For all other events it should be omitted.
- adding `objectData`support ([link](https://www.algolia.com/doc/rest-api/insights/#method-param-objectdata-2))
- `currency` information ([link](https://www.algolia.com/doc/rest-api/insights/#method-param-currency))
- `price` information ([link](https://www.algolia.com/doc/rest-api/insights/#method-param-price))
Resolves INT-1649
N/A
N/A
N/A
N/A
<hr>
=> fix: algolia enhancement

src/cdk/v2/destinations/algolia/procWorkflow.yaml, src/v0/destinations/algolia/util.js, src/v0/destinations/algolia/util.test.js, test/integrations/destinations/algolia/processor/data.ts
ref: https://www.algolia.com/doc/rest-api/insights/#method-param-objectdata-2:~:text=currency-,%23,currency%20as%20ISO%2D4217%20currency%20code%2C%20such%20as%20USD%20or%20EUR.,-ObjectData
N/A
N/A
N/A
N/A
<hr>
=> fix: algolia add validation for currency fields

src/cdk/v2/destinations/reddit/procWorkflow.yaml, src/v0/destinations/facebook_offline_conversions/utils.js, src/v0/destinations/fb/transform.js, src/v0/destinations/google_adwords_enhanced_conversions/data/trackConfig.json, src/v0/destinations/google_adwords_enhanced_conversions/transform.js, src/v0/destinations/google_adwords_offline_conversions/utils.js, src/v0/destinations/impact/transform.js, src/v0/destinations/pinterest_tag/utils.js, src/v0/destinations/yahoo_dsp/util.js, test/integrations/destinations/facebook_offline_conversions/processor/data.ts, test/integrations/destinations/fb/processor/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/processor/data.ts, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts, test/integrations/destinations/impact/processor/data.ts, test/integrations/destinations/pinterest_tag/processor/data.ts, test/integrations/destinations/reddit/processor/data.ts, test/integrations/destinations/yahoo_dsp/processor/data.ts
Standardise hashing for all CAPI integrations.
By standardise we mean to do trimming of strings before hashing them so that they can be properly used in downstream conversions destinations.
List of integrations involved in this:
1. Pinterest
2. Reddit
3. Google ads enhanced conversions
4. Google ads offline conversions
5. Impact
6. Facebook
7. Facebook conversions
Resolves INT-2127
N/A
N/A
N/A
N/A
<hr>
=> fix: standardise hashing for all CAPI integrations

src/v0/destinations/tiktok_ads/data/TikTokTrackV2.json, src/v0/destinations/tiktok_ads/transformV2.js, test/integrations/destinations/tiktok_ads/processor/data.ts
tiktok_v2 remove default value for content-type for custom events.
We had a default value as it is recommended parameter from tiktok side for standard event but nothing says for custom event and we just got a use case where there should not be a default value
Resolves INT-2138
N/A
N/A
N/A
N/A
<hr>
=> fix: tiktok_v2 remove default value for content-type for custom events

src/util/customTransformer-faas.js, src/util/openfaas/faasApi.js, src/util/openfaas/index.js, test/__tests__/user_transformation.test.js
We are introducing a new reconcile step before we execute the fn first time from the perspective of user transformation service. This is done to sync the latest state of ut service to the openfaas-fn pods. Once the function gets added in the cache, we stop the reconciliation step and assume the function is up-to-date as the only way it could be added effectively in cache is when it was reconciled successfully.
Fixes DAT-1123
N/A
N/A
N/A
N/A
<hr>
=> chore: added reconcile fn for openfaas fn pods

src/v0/destinations/tiktok_ads/transformV2.js, test/integrations/destinations/tiktok_ads/processor/data.ts
=> fix: tiktok_v2 assigning value to undefined properties

src/cdk/v2/destinations/emarsys/utils.js, test/integrations/destinations/emarsys/processor/data.ts
Adding validation for eventsMapping config. If it is not at all configured, it is not coming as array
Resolves INT-2204
N/A
N/A
N/A
N/A
<hr>
=> fix: bugsnag error for emarsys track call

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/emarsys/utils.js, src/v0/destinations/tiktok_ads/transformV2.js, test/integrations/destinations/emarsys/processor/data.ts, test/integrations/destinations/tiktok_ads/processor/data.ts
=> chore(release): pull hotfix-release/v1.68.1 into main

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/emarsys/utils.js, src/v0/destinations/tiktok_ads/transformV2.js, test/integrations/destinations/emarsys/processor/data.ts, test/integrations/destinations/tiktok_ads/processor/data.ts
=> chore(release): pull main into develop post release v1.68.1

src/v0/destinations/splitio/data/EventConfig.json, src/v0/destinations/splitio/transform.js, test/integrations/destinations/splitio/processor/data.ts
Traffic type was being mapped from UI only, now, we have added mapping from the payload. The UI mapping will work as default traffic type if the payload field is missing.
Resolves INT-2200
N/A
N/A
N/A
N/A
<hr>
=> fix: allowing traffic type dynamically for split.io

src/v0/destinations/zendesk/transform.js, test/integrations/destinations/zendesk/processor/data.ts
Error : Cannot convert undefined or null to object
Resolves INT-2221
N/A
N/A
N/A
N/A
<hr>
=> fix: bugsnag issue fix for zendesk

src/util/prometheus.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js
This PR adds metrics for braze identify flow where errors are observed due missing `userId`, as braze returns 200 with an error message in response body we want to capture that as metrics
Resolves INT-2259
=> chore: add metrics for braze alias failures

src/v0/sources/auth0/mapping.json, test/integrations/sources/auth0/data.ts
The Auth0 event type was added to the transformed message at the top level, but that field gets stripped out when messages are exported to warehouse destinations (see [this documentation](https://www.rudderstack.com/docs/destinations/warehouse-destinations/faq/#why-am-i-not-able-to-see-the-properties-added-at-the-top-level-of-an-event-in-warehouse-destination)). Add this field to the context blob as well, so that it will be available when exported to warehouses.
N/A
No.
N/A
N/A
<hr>
=> feat(integrations/auth0): add Auth0 event type to event context

src/v0/destinations/singular/data/SINGULARAndroidEventConfig.json, src/v0/destinations/singular/data/SINGULARAndroidSessionConfig.json
> For Android requests, Singular requires either AIFA, ASID, or ANDI, in that order of preference. All 3 can be sent if available, and our servers will discard the ANDI per Google's data policies. If AIFA is not available, ASID should be sent. If ASID is not available, ANDI should be sent. If a given device ID is not available, the respective param should be sent with an empty value (rather than null, or some other value).
We are making these changes in our Singular destination integration. 
Resolves INT-2241
> We are making this change as currently the integration does not send Android events to Singular that are missing the ASID property.
N/A
N/A
N/A …
=> fix: mapping changes for aifa,andi and asid

src/v0/destinations/klaviyo/klaviyoUtil.test.js, src/v0/destinations/klaviyo/transform.js, src/v0/destinations/klaviyo/util.js
Adding subscribe flag default as true for traits properties object for vdm scenario
For RETL VDM flow adding subscribe as true for enabling subscription flow whenever listId is present
Resolves INT-578
N/A
N/A
N/A
N/A
<hr>
=> feat: add support for subscribing for RETL flow

src/cdk/v2/destinations/algolia/procWorkflow.yaml, test/integrations/destinations/algolia/processor/data.ts
Fix the discreoancy where top-level event.properties accepts queryId but nested event.properties.products expects queryID. 
Allowing both queryID, queryId to maintain consistency and backward compatibility as this is being used from beginning 
N/A
N/A
N/A
N/A
<hr>
=> fix: queryID aloglia discrepancy

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/util.js
This PR approaches to fix the `null` values handling during dedupe. When a property is set to as `null` it is unset from braze hence when we lookup it is not available. Hence we need to handle that scneario during deduplication
Resolves INT-2498
N/A
N/A
N/A
N/A
<hr>
=> fix: handle null values for braze dedupe

src/v0/destinations/sfmc/config.js, src/v0/destinations/sfmc/transform.js, test/integrations/destinations/sfmc/processor/data.ts
We are creating a different flow for rETL on the SFMC destination.
Resolves INT-1828
N/A
N/A
N/A
N/A
<hr>
=> feat: onboard sfmc with vdm for rETL

src/v0/util/facebookUtils/index.js, src/v0/util/facebookUtils/index.test.js
Resolves INT-2555
N/A
N/A
N/A
N/A
<hr>
=> fix: fixing facebook utils

src/v0/destinations/attentive_tag/transform.js, src/v0/destinations/attentive_tag/util.js, src/v0/destinations/attentive_tag/util.test.js, test/integrations/destinations/attentive_tag/processor/data.ts
Resolves INT-2549
N/A
N/A
N/A
N/A
<hr>
=> fix: attentive tag bugsnag issue

src/cdk/v2/destinations/the_trade_desk/transformRecord.js, test/integrations/destinations/the_trade_desk/router/data.ts
- Existing code is breaking the transformer <> server contract when field is null, undefined for any job.
- With this change we are aborting the whole job, If any field is null, undefined or empty, and respecting the transformer <> server contract.
Resolves INT-2538
N/A
N/A
N/A
N/A
<hr>
=> fix: handle trade desk null, undefined fields

.github/workflows/ut-tests.yml
We broke the UT tests when we made our images private. This test fixes the docker hub authorization issue but creating a regcred secret through docker credentials to be used for patching deployments and service accounts
Fixes DAT-1487
N/A
N/A
N/A
N/A
<hr>
=> fix: login using docker creds on the node to allow to pull the desired image

src/v0/destinations/klaviyo/transform.js, src/v0/destinations/klaviyo/transformV2.js, test/integrations/destinations/klaviyo/router/data.ts
This PR solves the jobs order issue for klaviyo
Resolves INT-1795
N/A
N/A
N/A
N/A
<hr>
=> fix: klaviyo jobs order

src/controllers/source.ts, src/services/source/__tests__/nativeIntegration.test.ts, src/services/source/__tests__/postTransformation.test.ts, src/services/source/nativeIntegration.ts, src/services/source/postTransformation.ts, src/types/index.ts, src/v0/util/index.js, test/apitests/data_scenarios/source/v1/successful.json, test/apitests/service.api.test.ts, test/integrations/sources/pipedream/data.ts, test/integrations/sources/segment/data.ts
Add support for headers to source transformation flows by exposing them in event context.
Resolves INT-2504
N/A
N/A
N/A
N/A
<hr>
=> feat: add support for headers to source transformation flows

src/v0/destinations/reddit/networkHandler.js, test/integrations/destinations/reddit/dataDelivery/business.ts, test/integrations/destinations/reddit/network.ts
reddit 403 error handling
N/A
N/A
N/A
N/A
<hr>
=> chore: handle other error use-cases in reddit

src/v0/destinations/reddit/networkHandler.js, test/integrations/destinations/reddit/dataDelivery/business.ts, test/integrations/destinations/reddit/network.ts
* fix: handle reddit responses in case of non 401 status
* chore: handle other error use-cases in reddit
* chore: fix test for reddit
* chore: add test
---------
N/A
N/A
N/A
N/A
<hr>
=> chore: handle other error use-cases in reddit (#3692)

src/v0/util/index.js, src/v0/util/index.test.js
added applyJSONStringTemplate for applying string templates using JSON template engine
Resolves INT-2560
N/A
N/A
N/A
N/A
<hr>
=> feat: add util for applying json string template

test/integrations/testUtils.ts
Initial condition fix
Resolves INT-2589
N/A
N/A
N/A
N/A
<hr>
=> chore: source integration script filter initial condition - 1

src/v0/destinations/salesforce/transform.js, test/integrations/destinations/salesforce/network.ts, test/integrations/destinations/salesforce/processor/data.ts, test/integrations/destinations/salesforce/router/data.ts
Resolves INT-2664
N/A
N/A
N/A
N/A
<hr>
=> fix: use destination definition name in place of string for custom object

src/cdk/v2/destinations/bluecore/utils.js
In Bluecore we were having validation which were resulting in `truthy` outcome for numeric values like `0`
This PR approaches to fix the same
Resolves INT-2722
Alert: https://rudderstack.grafana.net/a/grafana-oncall-app/alert-groups/I41S6Q2NG82DL?perpage=25&start=1&started_at=now-30d_now&status=0&status=1&team=TRBAJ7M5Y8MEJ
N/A
N/A
N/A
N/A
<hr>
=> fix: add correct validation for purchase events

src/warehouse/index.js
- Since we are doing `process.env.WH_POPULATE_SRC_DEST_INFO_IN_CONTEXT`, it is impossible to override it . 
- If we set some value, it comes as a string and it is true. If we don't set some value by default, it's true. So it's always true.
- ResolvesPIPE-1640
=> fix: populate source destination info env set properly

src/v0/destinations/snowpipe_streaming/transform.js, test/__tests__/warehouse.test.js
- A new integration for Snowpipe Streaming has been added, leveraging the existing Snowflake integration due to their similarity.
=> feat: snowpipe streaming

src/cdk/v2/destinations/zapier/procWorkflow.yaml, src/cdk/v2/destinations/zapier/utils.js, test/integrations/destinations/zapier/processor/data.ts
Mapping RS event to multiple Zap URLs
Resolves INT-2346
N/A
N/A
N/A
N/A
<hr>
=> feat: support for multiple zap urls

src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, test/apitests/data_scenarios/cdk_v2/failure.json, test/apitests/data_scenarios/cdk_v2/success.json, test/apitests/data_scenarios/destination/proc/batch_input_multiplex.json, test/apitests/data_scenarios/destination/proc/multiplex_partial_failure.json, test/apitests/data_scenarios/destination/proc/multiplex_success.json, test/apitests/data_scenarios/destination/router/failure_test.json, test/integrations/destinations/pinterest_tag/processor/data.ts, test/integrations/destinations/pinterest_tag/router/data.ts, test/integrations/destinations/pinterest_tag/step/data.ts
We are adding missing mapping of ecomm events with single product
Resolves INT-2743
N/A
N/A
N/A
N/A
<hr>
=> fix: add missing field for pinterest_tag single product events

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, src/v0/destinations/google_adwords_enhanced_conversions/transform.js, src/v0/util/index.js, src/v0/util/index.test.js, test/apitests/data_scenarios/cdk_v2/failure.json, test/apitests/data_scenarios/cdk_v2/success.json, test/apitests/data_scenarios/destination/proc/batch_input_multiplex.json, test/apitests/data_scenarios/destination/proc/multiplex_partial_failure.json, test/apitests/data_scenarios/destination/proc/multiplex_success.json, test/apitests/data_scenarios/destination/router/failure_test.json, test/integrations/destinations/google_adwords_enhanced_conversions/processor/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/router/data.ts, test/integrations/destinations/pinterest_tag/processor/data.ts, test/integrations/destinations/pinterest_tag/router/data.ts, test/integrations/destinations/pinterest_tag/step/data.ts
=> chore(release): pull hotfix-release/v1.83.2 into main

src/v0/destinations/salesforce/utils.js, test/integrations/destinations/salesforce/dataDelivery/business.ts, test/integrations/destinations/salesforce/dataDelivery/data.ts, test/integrations/destinations/salesforce/dataDelivery/other.ts
For salesforce when the salesforce server is busy or unavailable we were throwing retriable which was being failed eventually by retrying  3 times.
Now, we are throwing 429 status code appropriately.
Resolves INT-2847
N/A
N/A
N/A
N/A
<hr>
=> fix: adding throttled status code for server unavailable error in salesforce

src/v0/destinations/google_adwords_remarketing_lists/config.js, src/v0/destinations/google_adwords_remarketing_lists/recordTransform.js, src/v0/destinations/google_adwords_remarketing_lists/transform.js, src/v0/destinations/google_adwords_remarketing_lists/util.js, src/v0/destinations/google_adwords_remarketing_lists/util.test.js, test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/record.ts
Moved userSchema to connection config in GARL vdmv2
Resolves INT-2898
N/A
N/A
N/A
N/A
<hr>
=> feat: moved userSchema to connection config in GARL vdmv2

src/v0/destinations/iterable/config.js, src/v0/destinations/iterable/transform.js, src/v0/destinations/iterable/util.js, test/integrations/destinations/iterable/processor/aliasTestData.ts, test/integrations/destinations/iterable/processor/identifyTestData.ts, test/integrations/destinations/iterable/processor/pageScreenTestData.ts, test/integrations/destinations/iterable/processor/trackTestData.ts, test/integrations/destinations/iterable/router/data.ts
Implemented European data center & EU based APIs
Resolves INT-2606
UI: 
N/A
N/A
N/A
N/A
<hr>
=> feat: iterable EUDC

src/v0/destinations/google_adwords_remarketing_lists/recordTransform.js, test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/record.ts
Now getting consent related fields from connection config from retl for GARL
N/A
N/A
N/A
N/A
<hr>
=> feat: now getting consent related fields from connection config from retl for GARL

src/v0/destinations/gainsight_px/config.js, src/v0/destinations/gainsight_px/config.test.js, src/v0/destinations/gainsight_px/transform.js, src/v0/destinations/gainsight_px/util.js
Extended datacenter support to eu/us2 region, apart from us.
Resolves INT-2845
N/A
N/A
N/A
N/A
<hr>
=> feat: added support to eu/us2 datacenter for gainsight px destination

src/v0/destinations/iterable/deleteUsers.js, test/integrations/destinations/iterable/deleteUsers/data.ts, test/integrations/destinations/iterable/network.ts
Added EUDC delete users API support
Resolves INT-2606
DOC: https://support.iterable.com/hc/en-us/articles/360032290032-Deleting-Users
N/A
N/A
N/A
N/A
<hr>
=> feat: iterable EUDC deleteUsers

package-lock.json, package.json, src/v0/destinations/airship/transform.js, src/v0/destinations/airship/utils.js, test/integrations/destinations/airship/processor/data.ts
ref: https://docs.airship.com/api/ua/#operation-api-custom-events-post
Our present implementation did not ensure that the session ID was converted to UUID format. Hence we have introduced that fix. 
Resolves INT-2910
N/A
N/A
N/A
N/A
<hr>
=> fix: adding uuid transformation for airship

src/v0/sources/adjust/transform.js, src/v0/sources/adjust/utils.js, src/v0/sources/adjust/utils.test.js, test/integrations/sources/adjust/data.ts, test/integrations/testUtils.ts
Resolves INT-2873
N/A
N/A
N/A
N/A
<hr>
=> fix: handling invalid timestamp for adjust source

src/controllers/source.ts
We have got bugsnag error :
Adding logger to get more info
Resolves INT-2873
N/A
N/A
N/A
N/A
<hr>
=> fix: adding logger for undefined source event

src/v0/util/facebookUtils/networkHandler.js, test/integrations/destinations/facebook_pixel/dataDelivery/business.ts, test/integrations/destinations/facebook_pixel/dataDelivery/data.ts, test/integrations/destinations/facebook_pixel/dataDelivery/oauth.ts, test/integrations/destinations/facebook_pixel/dataDelivery/other.ts, test/integrations/destinations/facebook_pixel/network.ts, test/integrations/destinations/fb/dataDelivery/data.ts, test/integrations/destinations/fb/dataDelivery/other.ts, test/integrations/destinations/fb/network.ts, test/integrations/destinations/fb_custom_audience/dataDelivery/data.ts, test/integrations/destinations/fb_custom_audience/network.ts
For codes mentioned here, in default case, we will set message as `error_user_msg` instead of `message`
https://developers.facebook.com/docs/graph-api/guides/error-handling/
Resolves INT-2969
N/A
N/A
N/A
N/A
<hr>
=> chore: update default case handling in facebook destinations

.github/workflows/prepare-for-staging-deploy.yml
When release cut happens, new version need to be deployed in staging. As part of automated PR's, `repository` also should get updated
N/A
N/A
N/A
N/A
<hr>
=> chore: update repo name for staging deployment also

.github/workflows/dt-test-and-report-code-coverage.yml, src/v0/destinations/google_adwords_offline_conversions/transform.js, src/v0/destinations/google_adwords_offline_conversions/utils.js, src/v0/destinations/google_adwords_offline_conversions/utils.test.js, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
We are doing the following changes:
1. We can pass only one of gclid, wbraid and gbraid. If all three are available we are considering gclid. If both wbraid and gbraid are available without gclid we are throwing error.
2. We don't need to pass userIdentifier if any click ids are available. But if we send userIdentifiers along with gclid then `Google ads` is accepting that. So we are not changing that behaviour, we just stopped throwing errors.
Resolves INT-2942
N/A
N/A
N/A
N/A
<hr>
=> fix: remove redundant ids and userIdentifier when gbraid or wbraid are there

src/cdk/v2/destinations/reddit/rtWorkflow.yaml, src/cdk/v2/destinations/reddit/utils.js, src/v0/destinations/reddit/networkHandler.js, src/v1/destinations/reddit/networkHandler.js, test/integrations/destinations/reddit/dataDelivery/business.ts, test/integrations/destinations/reddit/dataDelivery/oauth.ts, test/integrations/destinations/reddit/network.ts, test/integrations/destinations/reddit/router/data.ts
This PR fixes failure of entire batch because of some error in any one event. We are utilising dontBatch to send the event one by one after the failure of the batch.
Resolves INT-2994
N/A
N/A
N/A
N/A
<hr>
=> fix: handling partial error in a batch for reddit destination

src/v0/destinations/branch/data/eventMapping.js, src/v0/destinations/branch/transform.js, test/integrations/destinations/branch/processor/data.ts
We are not setting the category properly for such events which are mapped to default events. For example let's say we have the following mapping:
Rudderstack Event -> Branch Event
Item Viewed -> VIEW_ITEM
As `Item Viewed` is not on the list of [different mappings](https://github.com/rudderlabs/rudder-transformer/blob/9d6a0027189d19b7c0c4e18be755c2bd9a733d87/src/v0/destinations/branch/data/eventMapping.js#L77) on Rudderstak we are setting the category name as custom. But later when we get the correct event name from the destination config we are not updating the category to the respective category.
Resolves INT-2997
N/A
N/A
N/A
N/A …
=> fix: use correct endpoint for custom events

package-lock.json, package.json, src/v0/destinations/hs/HSTransform-v2.js, test/integrations/destinations/hs/processor/data.ts, test/integrations/destinations/hs/router/data.ts
Add email validation in HS, that will reject invalid email at transformation level itself.
Package used: https://www.npmjs.com/package/validator
Resolves INT-3086
Yes
These invalid emails like regular strings will not pass the destination transformer, hence they will not go through to HS and get rejected there. There could be some event volume drop.
https://www.npmjs.com/package/validator
N/A
N/A
<hr>
=> fix: add email validation in HS

src/util/dynamicConfig.js, src/util/dynamicConfig.test.js, src/v0/destinations/af/deleteUsers.js, src/v0/destinations/airship/transform.js, src/v0/destinations/clickup/util.js
Fix regex issues
Resolves INT-3054
N/A
N/A
N/A
N/A
<hr>
=> fix: sonar issues in regex expressions

src/v0/destinations/google_adwords_offline_conversions/data/TrackAddStoreConversionsConfig.json, src/v0/destinations/google_adwords_offline_conversions/transform.js, src/v0/destinations/google_adwords_offline_conversions/utils.js, src/v0/util/index.js, src/v0/util/index.test.js, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts
We are refactoring the code to allocate all the logic related to identifier in one place. We also added a validation to check if provided value is greater than 0 or not. As we are mapping that to `transaction_amount_micros` after [multiplying with 1,000,000](https://groups.google.com/g/adwords-scripts/c/mSl5bxSkwec/m/Rnq85eP7AgAJ) and it can't be less than 1000 as per the [doc](https://developers.google.com/google-ads/api/reference/rpc/v18/TransactionAttribute#:~:text=30%2B03%3A00%22-,transaction_amount_micros,-double).
Resolves INT-3085 INT-3020
N/A
N/A
N/A
N/A
<hr>
=> fix: refactor code and add validation for values

src/util/openfaas/index.js
This PR includes a simple statuscode check extension to include 502 status code from upstream openfaas gateway server to retry the request. Currently, an exception is thrown and the rudder-server doesn't retry causing the transient failure to be sticky and permanent.
This results in dataloss for our customers. This change prevents that.
Resolves DAT-1900
N/A
N/A
N/A
N/A
<hr>
=> fix: extend statuscode check to 502 to retry the request

package-lock.json, package.json, src/v0/destinations/klaviyo/util.js, test/integrations/destinations/klaviyo/processor/screenTestDataV2.ts, test/integrations/destinations/klaviyo/processor/trackTestDataV2.ts, test/integrations/destinations/klaviyo/router/dataV2.ts
We have a popular widely used library [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) here to validate the phone number being passed to Klaviyo, as Klaviyo rejects events with phone number not in the [E.164](https://en.wikipedia.org/wiki/E.164) standard. Klaviyo [Reference](https://developers.klaviyo.com/en/v2024-06-15/reference/events_api_overview#receiving-a-400).
As a precaution, the phone number is first sanitized ( i.e remove spaces, dashes etc ) and then the library is used on it.
Resolves INT-3180
The events which were having the phone numbers in incorrect format and would earlier hit the klaviyo APIs and then get rejected, …
=> fix: add phone e164 format validation for klaviyo

src/types/index.ts, src/v0/destinations/customerio_audience/type.ts, src/v0/destinations/customerio_audience/utils.ts
=> chore: simplify types and generalise existing types

CHANGELOG.md, package-lock.json, package.json, src/sources/mailjet/transform.js, test/integrations/sources/mailjet/data.ts
=> chore(release): pull hotfix-release/v1.91.5 into main

src/v0/util/facebookUtils/networkHandler.js, test/integrations/destinations/fb_custom_audience/dataDelivery/data.ts, test/integrations/destinations/fb_custom_audience/network.ts
Add 2655 error handling to fb error handler at proxy for below error code
`"response": {
"message": "(#2655) Marketing Messaging TOS not accepted",
"type": "OAuthException",
"code": 2655,
"fbtrace_id": "XX....XX"
},`
Resolves INT-3350
N/A
N/A
N/A
N/A
<hr>
=> fix: add 2655 error handling to fb error handler at proxy

src/adapters/networkHandlerFactory.js, src/v0/destinations/am/networkHandler.js, test/integrations/destinations/am/dataDelivery/data.ts, test/integrations/destinations/am/network.ts
Resolves INT-3215
N/A
N/A
N/A
N/A
<hr>
=> chore: onboard am to proxy

src/v0/destinations/customerio/util.js, src/v0/destinations/customerio/util.test.js, test/integrations/destinations/customerio/processor/data.ts
This commit fixes an issue where userIds containing forward slashes were not properly encoded
in CustomerIO destination URLs.
Changes:
- Added encodePathParameter function to encode forward slashes in userIds
- Updated defaultResponseBuilder to use encodePathParameter for userId
- Added unit tests for encodePathParameter using table test format
- Added unit tests for defaultResponseBuilder with userIds containing slashes
- Added component tests to verify end-to-end functionality
This ensures that CustomerIO API calls work correctly when userIds contain forward slashes.
Resolves INT-3470
N/A
N/A
N/A
N/A
<hr>
=> fix: encode userId with forward slashes in CustomerIO URLs

src/v0/destinations/iterable/config.js, src/v0/destinations/iterable/util.js, src/v0/destinations/iterable/util.test.js
Update Iterable destination to use a single 4MB request size limit for both identify and track operations, and a 1,000 items per request limit for catalog operations.
- Replace separate batch size limits with a single MAX_BODY_SIZE_IN_BYTES constant
- Add CATALOG_MAX_ITEMS_PER_REQUEST constant for catalog operations
- Add INITIAL_CHUNK_SIZE constant to replace hard-coded values
- Simplify catalog batching logic only to respect item count limit
- Add tests to verify batching behavior
Resolves INT-3475
N/A
N/A
N/A
N/A
<hr>
=> refactor(iterable): update api limits and batching logic

src/services/source/__tests__/nativeIntegration.test.ts, src/services/source/nativeIntegration.ts
Added validation in sourceTransformRoutine to ensure sourceEvents is an array. If not, it throws a TransformationError with message 'Invalid source events'.
Updated the corresponding test to properly handle async error testing by using await expect().rejects.toThrow() instead of expect().toThrow().
This validation prevents unexpected errors when processing non-array inputs and provides a clear error message for debugging.
https://rudderstack.grafana.net/a/grafana-irm-app/alert-groups/ITHVQNPJT22EA
Resolves INT-3457
N/A
N/A
N/A
N/A
<hr>
=> feat: add validation for sourceEvents array type

.eslintignore, src/v0/destinations/marketo_static_list/transform.js, src/v0/destinations/marketo_static_list/transform.test.js
This fix ensures that the processMetadataForRouter function in marketo_static_list always returns metadata as an array, which is required by the router. Previously, it was not ensuring that the metadata was always an array, which could cause issues with the router transform.
Resolves INT-3458
N/A
N/A
N/A
N/A
<hr>
=> fix: ensure marketo_static_list metadata is always an array

src/cdk/v2/destinations/userpilot/procWorkflow.yaml, test/integrations/destinations/userpilot/processor/data.ts
This pull request includes updates to the `procWorkflow.yaml` file and improvements to the test data in `data.ts` for better handling of user and event tracking in the Userpilot integration. The most important changes include adding comments for API documentation, updating the response body format, and enhancing the test data structure.
Documentation and comments:
* Added comments to provide links to the central API documentation and descriptions for the Identify, Track, and Group APIs in `procWorkflow.yaml`. 
Response formatting:
* Changed the response body format from `$.context.payload` to `$.context.payload.JSON` in `procWorkflow.yaml` to ensure the payload is correctly formatted as JSON.
Put down any required details on the broader aspect of your changes. If there …
=> fix: userpilot response structure

package-lock.json, package.json
Resolves INT-3567
N/A
N/A
N/A
N/A
<hr>
=> chore: update integrations-lib to 0.2.31

src/v0/destinations/google_adwords_offline_conversions/utils.js, src/v0/destinations/google_adwords_offline_conversions/utils.test.js
This pull request includes a minor improvement to the `getAddConversionPayload` function in the `src/v0/destinations/google_adwords_offline_conversions/utils.js` file. The change enhances the validation logic for the `phone` field before applying the `sha256` hash.
Validation improvement:
* Updated the condition for hashing the `phone` field to include a check for whether it is a string (`isString(phone)`), ensuring that non-string values are not processed incorrectly.
Resolves INT-3641
N/A
N/A
N/A
N/A
<hr>
=> chore: add string check for phone in gaoc

src/index.ts, src/middleware.js, src/middleware.test.js
Instead of performing `JSON.stringify` we are using precalculated raw payload sizes for capturing metrics:
- `transformer_http_request_size`: using `ctx.request.rawBody` provided by [koa-bodyparser](https://github.com/koajs/bodyparser?tab=readme-ov-file#raw-body)
- `transformer_http_response_size`: using `ctx.response.length` provided by [koa](https://github.com/koajs/koa/blob/master/docs/api/response.md#responselength-1)
This has a positive impact on server's performance and cpu utilization, especially while dealing with larger payloads
=> chore: payload size middleware performance improvement

src/v0/destinations/mp/transform.js, test/integrations/destinations/mp/processor/data.ts, test/integrations/destinations/mp/router/data.ts
**Summary:**
This PR adds `Content-Type` headers to the `/engage` and `/group` API requests.
**Reason:**
Mixpanel recommends explicitly setting the `Content-Type` for these endpoints to avoid unexpected errors. This change ensures that `transformerProxy` can correctly interpret and forward the content with the appropriate headers.
`engage` api
https://developer.mixpanel.com/reference/profile-set
`/group` api
https://developer.mixpanel.com/reference/group-set-property
Resolves INT-3639
N/A
N/A
N/A
N/A
<hr>
=> chore: mp add content type header to all apis

src/v0/destinations/salesforce/utils.js, src/v0/destinations/twitter_ads/transform.js, src/v0/destinations/twitter_ads/util.js, src/v0/destinations/twitter_ads/utils.test.js, src/v0/destinations/x_audience/utils.js, test/integrations/destinations/salesforce/processor/data.ts, test/integrations/destinations/twitter_ads/processor/data.ts, test/integrations/destinations/twitter_ads/router/data.ts, test/integrations/destinations/x_audience/processor/data.ts, test/integrations/destinations/x_audience/router/data.ts
Check for the OAuth secrets field; if any required field is absent, throw an OAuth error.
We made this change for the following destinations:
* salesforce
* x_audience
* twitter_ads
Resolves INT-3607
N/A
N/A
N/A
N/A
<hr>
=> fix: handle empty oauth secret for multiple destination

package-lock.json, package.json, src/middlewares/destTransformCompactedPayloadV1.ts, src/middlewares/routerTransformCompactedPayloadV1.ts, src/util/dynamicConfigParser.ts
Introduces deep freeze functionality to compaction middlewares to prevent accidental mutation of destination configuration objects during event processing.
- **Updated package dependencies**: Upgraded `@rudderstack/integrations-lib` from `^0.2.32` to `^0.2.34` to access the `deepFreeze` utility
- **Enhanced middleware protection**: Added `deepFreeze` to destination config in both compaction middlewares:
- `destTransformCompactedPayloadV1.ts`
- `routerTransformCompactedPayloadV1.ts`
- **Optimized dynamic config parser**: Replaced `lodash/cloneDeep` with native `structuredClone` for better performance
- **Added path validation**: Enhanced regex pattern with comprehensive documentation for dot-notation path validation
Resolves INT-3632
- **Thread safety**: Prevents accidental mutation of …
=> chore: introduce deep freeze to compaction middlewares

package-lock.json, package.json, src/v0/destinations/iterable/deleteUsers.js
We are removing promise.all from the Iterable deleteUser so that all the requests can be processed sequentially.
N/A
N/A
N/A
N/A
<hr>
=> chore: remove promise.all from iterable delete users to process calls synchronously

src/cdk/v2/destinations/bloomreach_catalog/rtWorkflow.yaml, src/cdk/v2/destinations/bloomreach_catalog/transformRecord.ts, src/services/source/nativeIntegration.ts, src/v0/destinations/customerio_audience/transform.ts, src/v0/destinations/fb_custom_audience/recordTransform.js, src/v0/destinations/fb_custom_audience/transform.js, src/v0/destinations/google_adwords_offline_conversions/transform.js, src/v0/destinations/google_adwords_remarketing_lists/recordTransform.js, src/v0/destinations/google_adwords_remarketing_lists/transform.js, src/v0/destinations/iterable/transform.js, src/v0/destinations/mailchimp/transform.js, src/v0/destinations/mp/transform.js, src/v0/util/index.test.js, test/integrations/destinations/mailchimp/router/data.ts
This pull request focuses on improving batch processing efficiency across various destination integrations - which are using high batch numbers - by introducing asynchronous utilities (`forEachInBatches`, `mapInBatches`, `groupByInBatches`, and `reduceInBatches`) from the `@rudderstack/integrations-lib`. 
* **Bloomreach Catalog Integration:**
- Updated `processRecordInputs` to use `await forEachInBatches` for processing inputs asynchronously in batches.
- Modified the workflow YAML file to call `processRecordInputs` as an asynchronous function.
* **Facebook Custom Audience Integration:**
- Refactored `processRecordEventArray`, `preparePayload`, and related methods to utilize `mapInBatches`, `forEachInBatches`, and `groupByInBatches` for concurrent processing. …
=> chore: add safe batch processing to avoid blocking in highly batched destinations

package-lock.json, package.json, sonar-project.properties, src/util/cluster.js, src/util/metricsAggregator.js, src/util/worker.js, test/__tests__/metricsAggregator.test.js
There were a number of issues with the current metrics aggregator implementation that this pull request is fixing:
- If the running request didn't complete for whatever reason, aggregator was being stuck not trying to aggregate anymore. Now we are using a configurable `METRICS_AGGREGATOR_REQUEST_TIMEOUT_SECONDS=10`, after which a new aggregation request will be allowed.
- In case of worker errors the aggregator's state could become corrupted, since it could associate old responses with newer requests. Now we're using a requestId so that aggregator ignores responses for previous request ids.
- A lot of error conditions were being unhandled, e.g. an error while sending to a worker or the aggregator thread, or trying to send to a disconnected worker.
- Worker thread wasn't being monitored …
=> fix: metrics aggregator stops collecting metrics

src/v0/destinations/snapchat_conversion/transformV3.js, src/v0/destinations/snapchat_conversion/utilsV3.js, test/integrations/destinations/snapchat_conversion/processor/dataV3.ts, test/integrations/destinations/snapchat_conversion/router/dataV3.ts
Fix the logic of populating extInfo, setting an empty string for null values, apart from dropping the entire extInfo and use advertiser_tracking_enabled.
Resolves INT-3910
N/A
N/A
N/A
N/A
<hr>
=> fix: add mapping of advertiser_tracking_enabled and enable extInfo with empty string

src/cdk/v2/utils.ts
This pull request includes a small change to the `getErrorInfo` function in `src/cdk/v2/utils.ts`. The change removes a logging statement that previously logged workflow step execution errors.
=> chore: remove logger for cdk service

src/v0/destinations/adobe_analytics/networkHandler.js
This pull request includes an update to the `responseHandler` function in `src/v0/destinations/adobe_analytics/networkHandler.js` to improve error handling for non-string responses.
* Added a check to verify if the `response` is a string. If not, it returns an error message along with the original `destinationResponse` object, ensuring better handling of unexpected response types.
Resolves INT-3941
=> fix: response parsing for adobe analytics

src/v0/destinations/am/networkHandler.js, test/integrations/destinations/am/dataDelivery/data.ts
Enhanced the AM network handler to properly handle both  and  in the response when a 429 status is received. Previously, the code only checked for , but now it also checks for  and throws appropriate retryable errors when either is present.
Resolves https://linear.app/rudderstack/issue/INT-3215/amplitude-post-proxy-migration-analysis
**Reason**: The AM destination API can return both  and  in the response when rate limits are exceeded. The previous implementation only handled , which could lead to missed throttling scenarios.
**Changes**:
- Added support for  in the response handler
- Created a helper function  to check if either object has throttled items
- Updated the condition to check both  and 
- Updated test data to remove  entries to match the new logic
N/A
N/A
N/A
@coderabbitai …
=> fix: handle throttled_devices in AM network handler response

src/util/prometheus.js
Remove 13 unused Marketo bulk upload metrics that were defined but not collected in the transformer service.
Resolves INT-3978
During metrics analysis, it was discovered that several Marketo bulk upload metrics were defined in the Prometheus configuration but never actually collected or used in the codebase. These metrics were likely created for one-time implementation purposes but are no longer needed.
- Removed 13 unused Marketo bulk upload metrics from :
- 
- 
- 
- 
- 
- 
- 
- 
- 
- 
- 
- 
- 
- 
**No breaking changes.** These metrics were never collected, so removing their definitions has no impact on functionality. Only the actively used Marketo metrics remain:
- 
- 
- 
N/A
N/A
**Performance Improvement:** Reduces Prometheus metric cardinality by removing 13 unused metric definitions, …
=> refactor: remove unused marketo bulk upload metrics

.github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/publish-new-release.yml, .github/workflows/slack-notify.yml
Added Slack notification functionality to the UT deployment workflow to notify the Control Plane team when DevOps PRs are created.
Resolves INT-3976
This PR implements Slack notifications for UT deployment as requested in the Linear issue. The changes include:
- **Modified UT deployment workflow**: Added PR URL capture for all three types of DevOps PRs (shared, hosted, dedicated transformers)
- **Added Slack notification step**: New step that sends a notification with PR links to the Control Plane team
- **Updated Slack action security**: Updated all Slack actions to use specific commit hash for security
N/A - Uses existing Slack action with security update
N/A
- Uses  to prevent notification failures from blocking deployment
- Captures PR URLs using  for direct linking
- Requires  secret …
=> chore: add slack notification for UT deployment PRs

.github/workflows/prepare-for-prod-ut-deploy.yml
Fixed GitHub CLI compatibility issue in the prepare-for-prod-ut-deploy.yml workflow by replacing the --json flag with grep for extracting PR URLs.
N/A - Bug fix for workflow compatibility
The --json flag is not available for write operations like gh pr create in older versions of GitHub CLI, causing workflow failures. This fix ensures compatibility across different GitHub CLI versions.
**Change**: Replaced gh pr create --fill --json url --jq '.url' with gh pr create --fill | grep -o 'https://github.com/[^/]*/[^/]*/pull/[0-9]*'
**Reason**: The --json flag is only available for read operations (like gh release view) but not for write operations (like gh pr create) in older GitHub CLI versions.
N/A
N/A
The new approach uses grep with regex to extract PR URLs, which is more compatible but …
=> fix: replace --json flag with grep for gh pr create compatibility

src/services/userTransform.ts, src/util/ivmFactory.js
This PR fixes the issue with reporting metrics generated when transformBatch is used.
Resolves OBS-828
Currently, there are two issues with the UT response when transformBatch is used:
- Newly added events in UT do not contain a messageId. As a result, these events are not tracked in reporting metrics.
- When UT fails, all input events are incorrectly marked as filtered. This causes rudder-transformer to return N + 1 events (where N is the number of input events marked as filtered, plus one additional event indicating the UT failure). However, the expected behavior is to return only a single event—the failed UT event—without any filtered events.
N/A
N/A
N/A
N/A
<hr>
=> fix: transformBatch reporting metrics issue

src/v0/destinations/splitio/config.js, src/v0/destinations/splitio/transform.js, test/integrations/destinations/splitio/processor/data.ts, test/integrations/destinations/splitio/router/data.ts
Added endpoint path details to Split.io destination configuration to support the top 15 destinations initiative. This change adds the `endpointPath` field to the configuration categories and ensures it's included in the response transformation.
Resolves INT-4102
This change is part of the initiative to add endpoint path details for the top 15 destinations in RudderStack. The `endpointPath` field provides additional metadata about the API endpoint being used, which can be useful for monitoring, debugging, and analytics purposes.
- Added `endpointPath: '/events'` to the EVENT configuration category in Split.io config
- Updated the transform function to include `endpointPath` in the response object
- Updated test data files to include the new `endpointPath` field in expected outputs
N/A
N/A …
=> feat(splitio): add endpoint path details

src/v0/destinations/mp/transform.js, src/v0/destinations/mp/util.js, test/integrations/destinations/mp/processor/data.ts, test/integrations/destinations/mp/router/data.ts
This PR adds the `endpointPath` field to Mixpanel destination transformer responses to provide additional endpoint information.
- **transform.js**: Refactored `setImportCredentials` to return endpoint details with path information
- **util.js**: Updated batched request configuration to include `endpointPath`
- **Test files**: Updated test data to reflect the new response structure with `endpointPath`
- Added `endpointPath` field to transformer responses for better endpoint identification
- Maintained backward compatibility while enhancing response structure
- Updated all relevant test cases to match the new response format
- All existing tests have been updated to include the new `endpointPath` field
- No breaking changes to existing functionality
=> feat(mp): add endpointPath to transformer responses

.github/workflows/allure-test-reporter.yml, .github/workflows/commitlint.yml, .github/workflows/dt-test-and-report-code-coverage.yml, .github/workflows/publish-new-release.yml, .github/workflows/ut-tests.yml, .github/workflows/verify-server-start.yml, .github/workflows/verify.yml, .npmrc, Dockerfile, Dockerfile-ut-func, package.json, scripts/skipPrepareScript.js
Introduced `.npmrc` with ignore-scripts=true to prevent lifecycle hooks. The rest of the changes are to accommodate `isolated-vm` manual build as well as Dockerfile adjustments to manually call `npm run prepare` which builds `isolated-vm` from source.
=> chore: disable lifecycle hooks

src/v0/destinations/google_adwords_remarketing_lists/config.js, src/v0/destinations/google_adwords_remarketing_lists/util.js, src/v0/destinations/google_adwords_remarketing_lists/util.test.js, test/integrations/destinations/google_adwords_remarketing_lists/processor/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts
This PR adds the  property to the Google AdWords Remarketing Lists destination response configuration.
- **config.js**: Added  constant and exported it
- **util.js**: Updated  function to include  in the response
- **util.test.js**: Updated test expectations to include 
- **Test data files**: Updated all processor and router test data files to include  in expected responses
The  property provides better traceability and debugging capabilities by clearly identifying the specific API endpoint being used in the response object. This change ensures consistency with other destinations that include endpoint paths in their responses.
- All existing tests pass
- Test data has been updated to reflect the new  property
- No breaking changes to existing functionality
- …
=> feat: add endpointPath to Google AdWords Remarketing Lists destination

src/v0/destinations/braze/config.js, src/v0/destinations/braze/identityResolutionUtils.test.ts, src/v0/destinations/braze/identityResolutionUtils.ts, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, test/integrations/destinations/braze/processor/data.ts, test/integrations/destinations/braze/router/data.ts, test/integrations/destinations/braze/router/identityResolution.ts
Enhanced Braze destination endpoint functions to return both the full endpoint URL and the path component for better debugging and monitoring capabilities.
Resolves https://linear.app/rudderstack/issue/INT-4102/add-endpoint-path-details-in-rudder-transformer-for-top-15
Modified endpoint functions (identify, track, subscription group, and alias merge) to return structured objects containing both the complete endpoint URL and the path component. This improves debugging capabilities and provides better visibility into which specific Braze API endpoints are being called.
The endpoint functions now return objects with `endpoint` and `path` properties instead of just the URL string. This is a non-breaking change as the `endpoint` property contains the same URL that was previously returned.
N/A …
=> feat: add endpoint path to Braze response objects
