src/v0/destinations/mp/config.js, src/v0/destinations/mp/deleteUsers.js, test/deleteUsers/data/mp/handler_input.json, test/deleteUsers/data/mp/handler_output.json, test/deleteUsers/data/mp/nw_client_data.json
Reverts rudderlabs/rudder-transformer#2200
=> feat: mixpanel deletion api 

src/util/prometheus.js
=> feat: auto register missing metrics

src/cdk/v2/destinations/bingads_audience/config.js, src/cdk/v2/destinations/bingads_audience/procWorkflow.yaml, test/__tests__/bingads_audience.test.js, test/__tests__/data/bingads_audience.json
Onboard bingads_audience destination (CDK)
> Fix [#1]()
=> feat: onboard bingads audience destination (CDK)

CODEOWNERS
=> chore(transformation): updating code owners for user transformer folder, tests

src/v0/destinations/hs/util.js, test/__tests__/data/hs_input.json, test/__tests__/data/hs_output.json
- Added a fix for handling the error when properties are not sent in hubspot.
- added three test cases for the same.
> Fix [#1]()
=> fix: hubspot bugsnag error

src/util/eventValidation.js, src/util/utils.js, test/__tests__/trackingPlan.test.js, test/__tests__/util.utils.test.js
> format tracking plan validation error object
> Fix [#1]()
=> chore: format tracking plan validation error object

test/__tests__/data/braze_input.json, test/__tests__/data/braze_output.json
> increase test converage braze 
> Fix [#1]()
=> chore: increase test converage

src/util/redis/redisConnector.js
> Making changes to incorporate tls auth for redis-cluster
> Fix [#1]()
=> chore: add tls object for redis

src/util/eventValidation.js, test/__tests__/eventValidation.test.js
=> fix(trackingplan): correct drop event status for tracking plan events

src/warehouse/index.js, test/__tests__/data/warehouse/integration_options_events.js, test/__tests__/warehouse.test.js
> Added skipUsersTable in integrations options to allow skipping users events if set.
> Fix [#1]()
=> chore: skip users event when skipUsersTable is set to true

test/__tests__/data/marketo_static_list_proxy_input.json, test/__tests__/data/marketo_static_list_proxy_output.json
> Fixing Marketo Static List Test Cases
> Fix [#1]()
=> fix: marketo static list test cases

src/features.json, src/v0/destinations/twitter_ads/data/TwitterAdsTrackConfig.json, test/__tests__/data/twitter_ads.json
> add twitter ads in features.json for router transform
> Fix [#1]()
=> fix: add twitter ads in features.json

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/config.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, test/__tests__/data/braze_output.json, test/__tests__/data/braze_router_input.json, test/__tests__/data/braze_router_output.json
> Updated router batching in braze to support subscription calls
> Fix [#1]()
=> feat: braze router batching update

src/v0/destinations/gainsight_px/transform.js, test/__tests__/data/gainsight_px_input.json, test/__tests__/data/gainsight_px_output.json
> gainsight _px remove null custom attributes from identify call
> Fix [#1]()
=> fix: gainsight_px null value

.github/workflows/prepare-for-prod-deploy.yml
> Move hosted prod to githubactions
- Create a separate pull request for hosted transformer this will help when there is a custom build running on hosted. In such cases, having a separate pull request can help us make a decision on whether we should deploy the changes on the hosted transformer as well.
- Cloned the devops repo in a separate step
- Extracting clone repo base branch in a separate and creating hosted transformer branch from base branch
> Fix [#1]()
=> feat: move hosted prod to githubactions

src/services/destination/cdkV2Integration.ts, src/services/destination/nativeIntegration.ts, src/services/destination/postTransformation.ts
> Update the logic to capture router success/failure metrics
> Fix [#1]()
=> feat: capture router success/failure metrics

.github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml, .github/workflows/publish-new-release.yml, .github/workflows/report-code-coverage.yml
=> chore: use PAT in workflows for token

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 1.32.3

src/cdk/v2/destinations/optimizely_fullstack/procWorkflow.yaml, test/__tests__/data/optimizely_fullstack.json
> Remove sending empty attributes array to optimizely.
> Fix [#1]()
=> fix(optimizely): remove empty attributes array for identify call

src/v0/destinations/factorsai/config.js, src/v0/destinations/factorsai/data/FactorsAIGroupConfig.json, src/v0/destinations/factorsai/data/FactorsAIPageConfig.json, src/v0/destinations/factorsai/transform.js, test/integrations/destinations/factorsai/data.js
>  factorsAI page and group call support
> Fix [#1]()
=> feat: factorsAI page and group call support

package-lock.json, package.json, src/cdk/v2/destinations/bingads_audience/procWorkflow.yaml, test/__tests__/data/bingads_audience.json
add support for all audience actions in bingads
=> feat: add support for all audience actions in bingads

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/iterable/data/IterableIdentifyConfig.json, src/v0/destinations/iterable/data/IterableRegisterDeviceTokenConfig.json, src/v0/destinations/iterable/util.js, src/v0/destinations/mp/transform.js, src/v0/util/index.js, test/__tests__/data/iterable_input.json, test/__tests__/data/iterable_output.json, test/__tests__/data/marketo_router_output.json, test/__tests__/data/mp_input.json, test/__tests__/data/mp_output.json, test/__tests__/data/optimizely_fullstack.json, test/integrations/destinations/zendesk/processor/data.js, test/integrations/destinations/zendesk/router/data.js
=> chore(release): pull hotfix-release/v1.34.0 into main

.github/workflows/prepare-for-prod-deploy.yml
> Add UT tag for Hosted User Transformer
> Fix [#1]()
=> chore: add UT tag for hosted user transformer

src/v0/destinations/stormly/config.js, src/v0/destinations/stormly/data/StormlyGroupConfig.json, src/v0/destinations/stormly/data/StormlyIdentifyConfig.json, src/v0/destinations/stormly/data/StormlyTrackConfig.json, src/v0/destinations/stormly/transform.js, test/__tests__/data/stormly.json, test/__tests__/data/stormly_router_input.json, test/__tests__/data/stormly_router_output.json, test/__tests__/stormly.test.js
=> feat(new integration): stormly cloud mode destination

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/mp/transform.js, src/v0/util/index.js, test/__tests__/data/iterable_input.json, test/__tests__/data/marketo_router_output.json, test/__tests__/data/mp_input.json, test/__tests__/data/mp_output.json, test/__tests__/data/optimizely_fullstack.json, test/integrations/destinations/zendesk/processor/data.js, test/integrations/destinations/zendesk/router/data.js
=> fix: resolve develop main conflict

.github/workflows/prepare-for-prod-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
rudder-devops shared-services directory structure got updated to make it more self-explanatory, so the changes to upgrade the version in relevant files
https://www.notion.so/rudderstacks/Transformer-helm-charts-review-9af1cb7131a34453ab6448d5669cfb94
Corresponding devops PR https://github.com/rudderlabs/rudder-devops/pull/6926
> Fix [#1]()
=> chore: update release actions w.r.t latest devops directory structure

src/cdk/v2/destinations/autopilot/procWorkflow.yaml, test/__tests__/autopilot-cdk.test.ts, test/__tests__/data/autopilot_cdk_output.json
=> refactor: migrate autopilot to cdkv2

src/v0/destinations/iterable/transform.js, test/__tests__/data/iterable_router_output.json
=> fix(iterable): fix metadata format while batching

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/iterable/transform.js, test/__tests__/data/iterable_router_output.json
=> chore(release): pull hotfix-release/v1.34.1 into main

src/v0/destinations/am/transform.js, test/__tests__/data/facebook_pixel_output.json
=> chore: update test for fb pixel

src/util/openfaas/index.js
=> chore(transformation): configure min pods for faas functions

CHANGELOG.md
Removed unnecessary changelog entry
> Fix [#1]()
=> chore: remove unnecessary changelog entry

CHANGELOG.md, package-lock.json, package.json, src/util/openfaas/index.js, src/v0/destinations/iterable/data/IterableIdentifyConfig.json, src/v0/destinations/iterable/data/IterableRegisterDeviceTokenConfig.json, src/v0/destinations/iterable/transform.js, src/v0/destinations/iterable/util.js, src/v0/destinations/iterable/util.test.js, test/__tests__/data/iterable_input.json
=> chore(release): pull hotfix-release/v1.35.1 into main

src/v0/destinations/mp/transform.js
Do refactor to processAndChunkEvents
> Fix [#1]()
=> refactor: processAndChunkEvents

.github/workflows/prepare-for-prod-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml
Fixed the directory traversal issues & minor ones in production deployment github action.
Raised to `main` branch for production release process via github actions for next release.
> Fix [#1]()
=> chore: fixed the directory traversal issues in github action

src/controllers/destination.ts, src/controllers/regulation.ts, src/util/prometheus.js
> Adding latency metric for router transform destinations like MP.
> Fix [#1]()
=> chore: added router specific destinations latency metric

CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull hotfix-release/v1.35.3 into main

src/v0/destinations/mp/transform.js, test/__tests__/data/mp_output.json
> Reverting https://github.com/rudderlabs/rudder-transformer/pull/2395
> Fix [#1]()
=> fix: revert mixpanel alias id ordering

src/constants/destinationCanonicalNames.js, src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, test/__tests__/data/braze_input.json, test/__tests__/data/braze_output.json
> Raising a new PR against hotfix branch.
Prev PR: https://github.com/rudderlabs/rudder-transformer/pull/2357
> Fix [#1]()
=> fix: add changes for braze app id

src/v0/destinations/braze/util.js
=> fix:  stat labels

src/v0/destinations/tiktok_ads/config.js, test/__tests__/data/tiktok_ads_output.json, test/__tests__/data/tiktok_ads_router_output.json
> update tiktok ads api version to 1.3
> Fix [#1]()
=> chore: update tiktok ads api version to 1.3

src/util/prometheus.js, src/util/utils.js
=> chore(transformation): set to default dns servers

src/v0/destinations/iterable/transform.js, test/__tests__/data/iterable_router.json
=> fix(iterable): batching order issue

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js, src/v0/destinations/klaviyo/util.js, src/v0/destinations/mp/deleteUsers.js, src/v0/destinations/salesforce/transform.js, src/v0/destinations/salesforce/utils.js
tags for missed destinations for latency metric
=> chore: tags for missed destinations for latency metric

.github/workflows/publish-new-release.yml
> continue on git action failure to next steps
> Fix [#1]()
=> fix: continue on git action failure to next steps

src/warehouse/util.js
> Throw instrumentation error for missing recordId. Default raw error response is creating unnecessary genetic transformation error in transformer
> Fix [#1]()
=> chore: update error type for getRecordIDForExtract util

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, test/__tests__/data/braze_output.json
Braze purchase events require the price value to be float. This commit is purposed to solve that
=> fix(INT-256): handling non float price input for braze purchase events

src/v0/destinations/tiktok_ads/data/TikTokTrack.json, test/__tests__/data/tiktok_ads_input.json
=> fix(tiktok_ads): format productId to string data type

src/cdk/v1/heap/mapping/track.yaml, test/__tests__/data/heap_output.json
> Fix timestamp mapping for heap destination
> Fix [#1]()
=> fix: heap timestamp mapping

CHANGELOG.md
=> chore: update changelog entry for heap and tiktok

test/integrations/destinations/af/processor/data.ts, test/integrations/destinations/af/router/data.ts
=> refactor(INT-231): migrate af to component tests

.github/workflows/report-code-coverage.yml
> Bump [sonarcloud-github-action](https://github.com/SonarSource/sonarcloud-github-action/releases) from 1.8 to 2.0.0
> Fix [#1]()
=> chore(deps): bump sonarcloud-github-action from 1.8 to 2.0.0

src/cdk/v2/destinations/optimizely_fullstack/procWorkflow.yaml
=> fix: optimizely get datafile call

test/__tests__/data/customerio_input.json, test/__tests__/data/customerio_output.json
>Some test cases failed after merging #2420 .
Fixing the same test cases in this PR
> Fix [#1]()
=> chore: fix customerIo test cases

CHANGELOG.md
=> chore: remove changelog hotfix

src/v0/destinations/june/data/JunePageConfig.json
=> fix: pr conflicts

package-lock.json, package.json, src/controllers/destination.ts, src/services/destination/nativeIntegration.ts, src/v0/destinations/iterable/transform.js, src/v0/destinations/iterable/util.js, src/v0/destinations/iterable/util.test.js, test/__tests__/data/iterable_router.json, test/__tests__/iterable.test.js
=> fix(iterable): batch job order

src/v0/destinations/klaviyo/transform.js, src/v0/util/index.js, src/v0/util/index.test.js, src/v0/util/testdata/flattenJson.json, test/__tests__/data/klaviyo.json
Resolved INT-418
> flatten properties if flattenProperties setting enabled from UI
> Fix [#1]()
=> fix(klaviyo): flatten properties if flattenProperties setting enabled from UI

src/adapters/network.js, src/util/myAxios.js
add timeout for all the axios calls
https://linear.app/rudderstack/issue/INT-419/add-timeout-to-axios-calls
=> chore: add timeout for all the axios calls

src/v0/destinations/june/data/JuneGroupConfig.json
=> chore: removed duplicate context key from june group config

src/v0/destinations/posthog/transform.js
- open source contribution ([here](https://github.com/rudderlabs/rudder-transformer/pull/1599/files) is the pr against master)
> Fix [#1]()
=> feat(posthog): support timestamp mapping from properties

src/v0/destinations/braze/util.js
> Fix braze undefined alias name.
>
> Fix [#1]()
=> chore: bugsnag fixes

src/util/prometheus.js, src/v0/destinations/braze/networkHandler.js
- Added partial failure metric for braze
> Fix [#1]()
=> chore: introduced braze partial failure metric

CHANGELOG.md, package-lock.json, package.json, src/util/openfaas/index.js
=> chore(release): pull hotfix-release/v1.39.1 into main

CHANGELOG.md, package-lock.json, package.json, src/util/openfaas/index.js
=> chore(release): pull main into develop post release v1.39.1

test/__tests__/data/clevertap_router_input.json, test/__tests__/data/clevertap_router_output.json
> Resolves INT-450
> Fix [#1]()
=> test: add test for clevertap batching error

src/v0/destinations/google_adwords_remarketing_lists/transform.js, test/__tests__/data/google_adwords_remarketing_lists_input.json, test/__tests__/data/google_adwords_remarketing_lists_output.json
> blank audience support in google ads
> Fix [#1]()
=> feat: blank audience support in google ads

src/constants/destinationCanonicalNames.js, test/__tests__/data/ga4.json
=> chore: add support of ga4 display name

test/__tests__/criteo_audience.test.js, test/__tests__/data/criteo_audience.json
>  Resolves INT-439
> Adding test cases for Criteo Audience  Batching through mockeing as previously they were not there
> Fix [#1]()
=> chore: added batch test cases for criteo audience

src/adapters/network.js, src/util/prometheus.js
Metric for response status code for outgoing request.
=> chore: outgoing request response status code metric

src/v0/destinations/google_adwords_remarketing_lists/transform.js, test/__tests__/data/google_adwords_remarketing_lists_input.json, test/__tests__/data/google_adwords_remarketing_lists_output.json
> retl audience support google ads
> Fix [#1]()
=> feat: retl audience support google ads

src/v0/util/index.js
=> chore(INT-507): added support of type conversion for multiplication operation

src/v0/destinations/iterable/util.js
- added check to convert only lower case if event type is string
> Fix [#1]()
=> fix(iterable): squadcast alert

src/v0/destinations/ga4/config.js, src/v0/destinations/ga4/data/GA4CampaignDetailsConfig.json, test/__tests__/data/ga4.json
=> feat(ga4): added support of campaign_details event

src/cdk/v2/destinations/eloqua/config.js, src/cdk/v2/destinations/eloqua/procWorkflow.yaml, src/cdk/v2/destinations/eloqua/utils.js, test/__tests__/data/eloqua.json, test/__tests__/eloqua-cdk.test.ts
> eloqua new destination cdkv2
> Fix [#1]()
=> feat: eloqua new destination cdkv2

src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
=> fix(gaoc): custom variables issue

CHANGELOG.md, src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js, src/v0/destinations/marketo_bulk_upload/util.js
resolves INT-157
> fixing code smells
> Fix [#1]()
=> fix(marketo-bulk-upload): sonar issues

src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
=> fix(google_ads_offline_conversions): partial failure status code issue

src/cdk/v2/bindings/default.js, src/cdk/v2/destinations/optimizely_fullstack/procWorkflow.yaml, test/__tests__/data/optimizely_fullstack.json
> Add destination response for failed datafile lookup call.
> Fix [#1]()
=> fix: update datafile lookup error message

src/v0/destinations/marketo_bulk_upload/fileUpload.js
> solving the function import issue
> Fix [#1]()
=> fix: marketo bulk upload import issue

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/marketo_bulk_upload/fileUpload.js
=> chore(release): pull hotfix-release/v1.40.2 into main

src/v0/destinations/intercom/networkHandler.js, test/__mocks__/data/intercom/proxy_response.json, test/__mocks__/network.js, test/__tests__/data/intercom_proxy_input.json, test/__tests__/data/intercom_proxy_output.json, test/__tests__/proxy.test.ts
Resolves INT-287
- Onboard Intercom to transformer Proxy
- It handles the `408` status code from the Intercom and retries in that case
> Fix [#1]()
=> feat: onboard intercom to transformer proxy

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/marketo_bulk_upload/fileUpload.js
=> chore(release): pull main into develop post release v1.40.2

src/v0/destinations/hs/util.js, test/__tests__/data/hs_output.json
> Resolves INT-508 
Improve error message for mapping related configuration error in Hubspot
> Fix [#1]()
=> chore: improve error message for HS

src/v0/destinations/adobe_analytics/transform.js, src/v0/destinations/branch/transform.js, src/v0/destinations/fb/transform.js
=> fix(bugsnag): alerts

src/v0/destinations/klaviyo/transform.js, src/v0/destinations/klaviyo/util.js, test/__tests__/data/klaviyo.json
> add support for updating profile properties through track call
> Fix [#1]()
=> feat: add support for updating profile properties through track call

src/v0/destinations/iterable/data/IterableTrackConfig.json, src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json, test/__tests__/data/iterable.json
- Added support of id parameter for update events
> Fix [#1]()
=> fix(INT-591): added support of id parameter for update events

test/integrations/destinations/iterable/processor/data.ts, test/integrations/destinations/iterable/router/data.ts
Migrating testcases of ITERABLE to new format
> Fix [#1]()
=> refactor: migrate iterable to component tests

test/integrations/destinations/kissmetrics/processor/data.ts, test/integrations/destinations/kissmetrics/router/data.ts
Migrating testcases of KISSMETRICS to new format
> Fix [#1]()
=> refactor: migrate kissmetrics to component tests

test/integrations/destinations/kafka/batch/data.ts, test/integrations/destinations/kafka/processor/data.ts
Migrating testcases of KAFKA to new format
> Fix [#1]()
=> refactor: migrate kafka to component tests

test/integrations/destinations/indicative/processor/data.ts, test/integrations/destinations/indicative/router/data.ts
Migrating testcases of INDICATIVE to new format
> Fix [#1]()
=> refactor: migrate indicative to component tests

test/integrations/destinations/impact/processor/data.ts, test/integrations/destinations/impact/router/data.ts
Migrating testcases of IMPCAT to new format
> Fix [#1]()
=> refactor: migrate impact to component tests

test/integrations/destinations/googlesheets/processor/data.ts, test/integrations/destinations/googlesheets/router/data.ts
Migrating testcases of FB to new format
> Fix [#1]()
=> refactor: migrate google sheets to component tests

test/integrations/destinations/googlepubsub/processor/data.ts
Migrating testcases of FB to new format
> Fix [#1]()
=> refactor: migrate google pubsub to component tests

test/integrations/destinations/google_cloud_function/data.ts
Migrating testcases of GCF to new format
> Fix [#1]()
=> refactor: migrate google cloud function to component tests

src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json
=> fix(iterable): updated mappings

package-lock.json, package.json, src/index.ts, src/middleware.js
=> feat: added profiling endpoints to fetch profiles

src/v0/destinations/google_adwords_enhanced_conversions/config.js, src/v0/destinations/google_adwords_offline_conversions/config.js, src/v0/destinations/google_adwords_offline_conversions/utils.test.js, src/v0/destinations/google_adwords_remarketing_lists/config.js, test/__mocks__/data/google_adwords_offline_conversion/response.json, test/__mocks__/data/google_adwords_remarketing_lists/proxy_response.json, test/__tests__/data/google_adwords_enhanced_conversions_output.json, test/__tests__/data/google_adwords_enhanced_conversions_proxy_input.json, test/__tests__/data/google_adwords_enhanced_conversions_router_output.json, test/__tests__/data/google_adwords_offline_conversions.json, test/__tests__/data/google_adwords_offline_conversions_proxy_input.json, test/__tests__/data/google_adwords_offline_conversions_proxy_output.json, test/__tests__/data/google_adwords_offline_conversions_router_output.json, test/__tests__/data/google_adwords_remarketing_lists_output.json, test/__tests__/data/google_adwords_remarketing_lists_proxy_input.json, test/__tests__/data/google_adwords_remarketing_lists_router_output.json, test/__tests__/google_adwords_offline_conversions.test.js
> Resolves INT-394
> [INT-394] google ads v14 upgrade
> Fix [#1]()
=> feat: google ads v14 upgrade

src/controllers/misc.ts, src/index.ts, src/middleware.js, src/routes/misc.ts, src/services/misc.ts
=> fix: pyroscope endpoints

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/redis/transform.js, test/__tests__/data/redis_output.json
=> chore(release): pull hotfix-release/v1.41.1 into main

src/v0/destinations/marketo/util.js, test/__mocks__/data/marketo_static_list/proxy_response.json, test/__tests__/data/marketo_static_list_proxy_input.json, test/__tests__/data/marketo_static_list_proxy_output.json
Reverts rudderlabs/rudder-transformer#2606
=> Revert "fix(INT-339): marketo response handler to handle static list removed and skipped statuses"

src/v0/destinations/slack/transform.js, test/__tests__/data/slack_input.json, test/__tests__/data/slack_output.json
> change name of slack config properties
> Fix [#1]()
=> fix: change name of slack properties

src/v0/destinations/campaign_manager/networkHandler.js
> Resolves INT-679
> Fix [#1]()
=> fix: add optional chaining for error message in network handler of Intercom

src/v0/destinations/iterable/data/IterableTrackConfig.json, src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json, test/__tests__/data/iterable.json
=> fix(iterable): event id mapping

.github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml
=> chore: update release owners

.github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml, CHANGELOG.md, package-lock.json, package.json, src/util/prometheus.js, src/v0/destinations/iterable/data/IterableTrackConfig.json, src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json, test/__tests__/data/iterable.json
=> chore(release): pull hotfix-release/v1.43.1 into main

src/v0/destinations/adj/transform.js, test/integrations/destinations/adj/processor/data.ts
> Resolves INT-478
We got a [bugsnag alert](https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/6515b49d98041000080ccfe2?filters[error.status]=for_review&filters[event.since]=30d&filters[app.release_stage]=production) when there is no message.properties present.
This PR fixes that and uses optional chaining at desired places as well
> Fix [#1]()
=> fix: refactor adjust using optional chaining

src/v0/destinations/google_adwords_offline_conversions/transform.js, src/v0/destinations/google_adwords_offline_conversions/utils.js, test/__tests__/data/google_adwords_offline_conversions.json, test/__tests__/data/google_adwords_offline_conversions_router_output.json
>Resolves INT-505
> Fix [#1]()
=> chore: update error messages of GAOC

src/v0/destinations/ga4/transform.js, src/v0/destinations/ga4/utils.js, src/v0/destinations/ga4/utils.test.js
=> feat(ga4): added support of filter user traits

CHANGELOG.md, src/v0/destinations/clevertap/transform.js, test/__tests__/data/clevertap_input.json, test/__tests__/data/clevertap_output.json
> Resolves INT-751
fix clevertap issue finding traits in context
> Fix [#1]()
=> fix: add optional chaining for traits

CHANGELOG.md, src/util/openfaas/index.js
=> feat: geolocation support for python transformations

CHANGELOG.md, package-lock.json, package.json, src/util/openfaas/index.js, src/v0/destinations/clevertap/transform.js, src/v0/destinations/ga4/transform.js, src/v0/destinations/ga4/utils.js, src/v0/destinations/ga4/utils.test.js, test/__tests__/data/clevertap_input.json, test/__tests__/data/clevertap_output.json, test/integrations/testUtils.ts
> #2682 continued
> Fix [#1]()
=> fix: main into develop conflicts

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/criteo_audience/networkHandler.js, test/__mocks__/data/criteo_audience/proxy_response.json, test/__tests__/data/criteo_audience_proxy_input.json, test/__tests__/data/criteo_audience_proxy_output.json
=> fix: merge conflict dev main

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/criteo_audience/networkHandler.js, test/__mocks__/data/criteo_audience/proxy_response.json, test/__tests__/data/criteo_audience_proxy_input.json, test/__tests__/data/criteo_audience_proxy_output.json
Please do a merge commit
> Fix [#1]()
=> fix: main -> develop conflict

src/v0/destinations/klaviyo/transform.js, test/__tests__/data/klaviyo_router.json
=> fix(klaviyo): sending error field at root level for suppress events

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/clevertap/transform.js, test/__tests__/clevertap.test.js
=> chore(release): pull hotfix-release/v1.45.1 into main

src/v0/util/index.js, test/__tests__/data/facebook_pixel_input.json, test/__tests__/data/facebook_pixel_output.json
> solving code error: "gender.toUpperCase is not a function"
resolve INT-841
> Fix [#1]()
=> fix: fix getFbGenderVal function

.github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml, .github/workflows/prepare-for-prod-rollback.yml
=> chore: add chandu to github workflows

CHANGELOG.md, package-lock.json, package.json, src/services/userTransform.ts, src/types/index.ts
=> chore(release): pull hotfix-release/v1.45.2 into main

CHANGELOG.md, package-lock.json, package.json, src/types/index.ts
=> chore(release): pull hotfix-release/v1.45.3 into main

src/services/userTransform.ts, src/types/index.ts
=> chore: resolve pr conflicts

.github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml
=> chore: add mihir to release workflow

.github/workflows/prepare-for-prod-deploy.yml, .github/workflows/prepare-for-prod-rollback.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
=> fix: fixed hub not found error in helm charts

github-release.config.js, package.json
> update duplicate verions in github release
> Fix [#1]()
=> fix: update duplicate verions in github release

src/v0/destinations/braze/transform.js
=> chore: braze response added in error message

src/v0/destinations/mp/config.js, src/v0/destinations/mp/transform.js, src/v0/destinations/mp/util.js, src/v0/destinations/mp/util.test.js, src/v0/util/constant.js, src/v0/util/index.js, test/integrations/destinations/mp/router/data.ts
> Add gzip support compatibility with server using **X-Feature-Gzip-Support header**.
> Fix [#1]()
=> chore: add gzip support compatibility

src/v0/destinations/salesforce/utils.js
Fixes [this](https://app.squadcast.com/incident/652fe48c3202f1137fadf85f)
> Fix [#1]()
=> fix: bugsnag error for salesforce

src/v0/destinations/snapchat_conversion/transform.js, test/__tests__/data/snapchat_conversion.json
> Resolved RUD-852
> Fix [#1]()
=> fix: deduplication key issue

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/snapchat_conversion/transform.js, test/__tests__/data/snapchat_conversion.json
=> chore(release): pull hotfix-release/v1.46.3 into main

src/v0/destinations/hs/HSTransform-v1.js, src/v0/destinations/hs/HSTransform-v2.js, src/v0/destinations/hs/transform.js, src/v0/destinations/hs/util.js, test/__mocks__/data/hs/response.json, test/__tests__/data/hs_router_rETL_input.json, test/__tests__/data/hs_router_rETL_output.json
=> fix(hs): time stamp and contact not found issue

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/hs/HSTransform-v1.js, src/v0/destinations/hs/HSTransform-v2.js, src/v0/destinations/hs/transform.js, src/v0/destinations/hs/util.js, test/__mocks__/data/hs/response.json, test/__tests__/data/hs_router_rETL_input.json, test/__tests__/data/hs_router_rETL_output.json
=> chore(release): pull hotfix-release/v1.46.4 into main

src/v0/destinations/hs/util.js
=> fix(hubspot): property mismatch

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/hs/util.js
=> chore(release): pull hotfix-release/v1.46.5 into main

src/v0/destinations/google_adwords_offline_conversions/helper.js, src/v0/destinations/google_adwords_offline_conversions/helper.test.js, src/v0/destinations/google_adwords_offline_conversions/transform.js, src/v0/destinations/google_adwords_offline_conversions/utils.js, test/integrations/destinations/google_adwords_offline_conversions/mocks.ts, test/integrations/destinations/google_adwords_offline_conversions/network.ts, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
Changes only applicable for GAOC tests
- move timestamp conversion logic to helper & use the helper object
- include common mock logic
- add mocks for all relevant test-cases
- clean-up unnecessary imports
Resolves INT-886
> Fix [#1]()
=> fix: add timestamp conversion mock

.github/workflows/draft-new-release.yml
> add yashasvibajpai and sanpj2292 to release workflow actors
> Fix [#1]()
=> chore: add yashasvibajpai and sanpj2292 to release workflow actors

src/v0/destinations/freshmarketer/config.js, src/v0/destinations/freshmarketer/utils.js, src/v0/destinations/freshsales/config.js, test/__tests__/data/freshmarketer.json, test/__tests__/data/freshmarketer_router_input.json, test/__tests__/data/freshmarketer_router_output.json, test/__tests__/data/freshsales.json, test/__tests__/data/freshsales_router_input.json, test/__tests__/data/freshsales_router_output.json
Resolves INT-658
> Allow support for full url from UI in freshsales and freshmarketer
> Fix [#1]()
=> fix: allow support for full url from UI in freshsales and freshmarketer

src/features.json
> resolves INT-883
> Fix [#1]()
=> feat: onboard one signal to router transform

.github/workflows/create-hotfix-branch.yml
> There is a missing <'> due which we are unable to create a hotfix branch
> Fix [#1]()
=> fix: update create-hotfix-branch.yml

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/am/transform.js, test/__tests__/data/am_output.json
=> chore(release): pull hotfix-release/v1.49.1 into main

src/legacy/router.js, src/v0/destinations/facebook_conversions/transform.js, src/v0/destinations/facebook_conversions/utils.js, src/v0/sources/appcenter/transform.js
> Imported the error classes from integrations lib for missing integrations.
> Fix [#1]()
=> chore: add error import from lib for missing integrations

CHANGELOG.md, src/services/source/nativeIntegration.ts
fix: source transform error stat
=> fix: source transform error stat

CHANGELOG.md, src/v0/destinations/snapchat_conversion/data/OrderCompletedConfig.json, test/integrations/destinations/snapchat_conversion/processor/data.ts
> snapchat_conversion category mapping
> Fix [#1]()
=> fix: snapchat_conversion category mapping

test/__tests__/facebook_conversions.test.js
Add date mock to fix timestamp validation in tests
> Fix [#1]()
=> chore: add date mock to fix timestamp validation in tests

src/features.json
> updated transformerProxyV1 name
> Fix [#1]()
=> fix: updated transformerProxyV1 name

test/integrations/destinations/webhook/processor/data.ts, test/integrations/destinations/webhook/router/data.ts
onboard webhook to component tests
=> feat: onboard webhook to component tests

src/services/destination/postTransformation.ts
> removed type post tranformerhandler
> Fix [#1]()
=> fix: removed type post tranformerhandler

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/salesforce/utils.js, src/v0/destinations/salesforce_oauth/networkHandler.js, test/__tests__/facebook_conversions.test.js, test/integrations/destinations/salesforce/dataDelivery/data.ts
=> chore(release): pull hotfix-release/v1.50.1 into main

.github/pull_request_template.md, CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/salesforce/utils.js, src/v0/destinations/salesforce_oauth/networkHandler.js, test/integrations/destinations/salesforce/dataDelivery/data.ts
> To fix conflicts for back merge PR https://github.com/rudderlabs/rudder-transformer/pull/2875
> Fix [#1]()
=> chore(release): pull main into develop post release v1.50.1 

src/cdk/v2/destinations/tiktok_audience/rtWorkflow.yaml
Remove logs in tiktok_audience
> Fix [#1]()
=> chore: remove logging in tiktok_audience

src/services/destination/postTransformation.ts, src/v0/destinations/marketo/config.js, test/__tests__/data/marketo_input.json
- Adding backward compatibility for the marketo feature
- Cleanup of Post Transformation Class
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: marketo backward compatibility

src/v0/destinations/adobe_analytics/transform.js, test/integrations/destinations/adobe_analytics/processor/data.ts
When the message doesn't contain an event field there is no meaningful process we can do considering it as an instrumentation error.
Fixes bugsnag error when the event is not present in the message.
Fixes INT-1173
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: adobe_analytics event field check

src/v0/destinations/klaviyo/transform.js, test/__tests__/data/klaviyo.json
- This PR add checks for removing empty properties object from the payload to avoid sending it to klaviyo
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: add check to remove empty properties object from payload

src/v0/sources/mailjet/transform.js, test/__tests__/data/mailjet_source.json
Add check to check if event contains email or not before applying md5
mailjet code uses md5 method to hash email for using it as userId when actual userId is not found in the event and when email doesn't exists then md5 throwing an error so added check before calling md5 method.
Fixes: https://app.squadcast.com/incident/657089f16d02d29a7787a239
Fixes INT-1174
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: mailjet source transformation by adding email exists check

src/v0/destinations/tiktok_ads/transform.js, test/integrations/destinations/tiktok_ads/processor/data.ts
Resolve INT-1150
We are allowing custom events to sent to tiktok ads. ( [Tiktok ads](https://ads.tiktok.com/help/article/standard-events-parameters?lang=en) )
We want a smooth transition for customers wanting this functionality without disturbing existing functionality.
Hence we are introducing a new config flag `sendCustomEvents`
**enhancement** 
N/A
N/A
N/A
N/A
N/A
<hr>
=> feat: tiktok_ads: add support for custom events

CHANGELOG.md, src/util/trackingPlan.js
=> fix(dm): dropped support of useClones for trackingplans cache

src/v0/destinations/marketo_static_list/transform.js, test/integrations/destinations/marketo_static_list/router/data.ts
Lower event type to fix issues in case of `audienceList` event type.
audienceList or Record or AudienceList will not work for event type.
They will work for their respective lowercase counterpart
N/A
N/A
N/A
N/A
N/A
<hr>
=> chore: add lowercase check to MSL for event type audiencelist

src/services/destination/postTransformation.ts, test/integrations/destinations/braze/dataDelivery/data.ts, test/integrations/destinations/braze/network.ts
updated error response of v1 proxy when error is thrown
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: updated error response of v1 proxy

src/cdk/v2/destinations/reddit/procWorkflow.yaml
- This PR add check for undefined eventsMapping field value
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix(reddit): add undefined check for eventsMapping field

src/features.json
supportTransformerProxyV1 set to false
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: supportTransformerProxyV1 set to false

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/util.js
Braze addition of non-billable attributes for dedup
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: braze dedup for adding non-billable attributes

src/controllers/delivery.ts, src/services/destination/nativeIntegration.ts, src/services/destination/postTransformation.ts, test/integrations/destinations/braze/dataDelivery/data.ts
Correct status-code and error message is being sent in transformer proxy response
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: inclusion of right status-code & error details in proxy response

CHANGELOG.md, package-lock.json, package.json, src/controllers/delivery.ts, src/features.json, src/services/destination/nativeIntegration.ts, src/services/destination/postTransformation.ts, src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/util.js, test/integrations/destinations/braze/dataDelivery/data.ts
=> chore(release): pull main into develop post release v1.52.2

src/v0/destinations/tiktok_ads/transform.js, test/integrations/destinations/tiktok_ads/processor/data.ts
#2926 moved here for hotfix release
For custom events we are lowering their event name but we should retain the message event case as these are case sensitive at tiktok side
N/A
N/A
N/A
N/A
N/A
<hr>
=> fix: tiktok remove lowercasing for custom events

src/v0/destinations/factorsai/data/FactorsAIGroupConfig.json, src/v0/destinations/factorsai/data/FactorsAIIdentifyConfig.json, src/v0/destinations/factorsai/data/FactorsAITrackConfig.json, src/v0/destinations/factorsai/transform.js, test/integrations/destinations/factorsai/data.ts
We want to pass ip details for factorsAI.
Added a function that will populate ip details , if in `context we don't get IP details` then we will populate this from `message.request_ip.`
N/A
N/A
N/A
N/A
N/A
<hr>
=> feat: pass ip details for factorsAI

src/features.json
- In this pr we are moving intercom to routerTransform
- In order to do this only one change is needed in `features.json` file as in intercom `transform.js` file we are using common utility `processRouterDest` function
- router test cases are already added before in component tests
Resolves INT-780
- Move intercom to routerTransform
N/A
N/A
N/A
N/A
<hr>
- [ ✅] My code follows the style guidelines of this project
- [ ✅] **No breaking changes are being introduced.**
- [✅ ] All related docs linked with the PR?
- [ ✅] All changes manually tested?
- [❌ ] Any documentation changes needed with this change?
- [ ✅] Is the PR limited to 10 file changes?
- [ ✅] Is the PR limited to one linear task?
- [ ✅] Are relevant unit and component test-cases added?
- [✅ ] Is the type of change in the PR title …
=> feat: move intercom to routerTransform

src/v0/destinations/active_campaign/transform.js, src/v0/destinations/af/deleteUsers.js, src/v0/destinations/am/deleteUsers.js, src/v0/destinations/ga/deleteUsers.js, src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js, src/v0/destinations/google_adwords_offline_conversions/networkHandler.js, src/v0/destinations/google_adwords_offline_conversions/utils.js, src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js, src/v0/destinations/intercom/deleteUsers.js, src/v0/destinations/marketo/util.js, src/v0/destinations/monday/util.js
Resolves INT-590
We are adding endpoint labels to facilitate us in monitoring the latency of various api endpoints.
N/A
N/A
N/A
N/A
N/A
<hr>
=> chore: add endpoint labels

src/v0/destinations/google_adwords_enhanced_conversions/config.js, test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/network.ts, test/integrations/destinations/google_adwords_enhanced_conversions/processor/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/router/data.ts
upgrading GAEC to v15 from v14
Resolves INT-976
Google has updated its version to v14. According to the release notes we do not find any breaking changes being introduced. So we are upgrading the version.
Previously we used v14 and from now on we will use v15
N/A
N/A
N/A
<hr>
=> fix: version upgrade of gaec from 14 to 15

src/features.json, test/apitests/service.api.test.ts
Added regulation destinations to features.json
Right now regulation destinations are hardcoded in the rudder server it requires raising PR in the rudder-server repo and we need to wait for their release so in this change we are bringing that to features.json
Resolves INT-1336
New capability to /features endpoint
N/A
N/A
N/A
<hr>
=> feat: add regulation to features.json

CHANGELOG.md, src/v0/destinations/klaviyo/transform.js, test/integrations/destinations/klaviyo/network.ts, test/integrations/destinations/klaviyo/processor/data.ts
If message.event for track call is sent as non-string then it will result in transformation issue that we do not handle as we operate on it assuming it would be string
Resolves INT-1353
Putting a check for event to be string before doing operations on it
N/A
N/A
N/A
N/A
<hr>
=> fix: klaviyo: Event validation to be string before operating on it

src/v0/destinations/mp/transform.js, test/integrations/destinations/mp/processor/data.ts
Correction of error-message to avoid false-positive alerts from getting triggered
Resolves INT-951
N/A
N/A
N/A
N/A
<hr>
=> fix: mixpanel alias simplified merge error message

.github/workflows/prepare-for-dev-deploy.yml, .github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml
Importing the correct **code-coverage** file for deployments as the previous one is replaced 
Minor Change no ticket
N/A
N/A
N/A
N/A
<hr>
=> fix: add valid code coverage file in workflows

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/tiktok_ads/util.js, test/integrations/destinations/tiktok_ads/processor/data.ts
=> chore(release): pull hotfix-release/v1.54.1 into main

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/marketo_bulk_upload/fileUpload.js, src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js, src/v0/destinations/marketo_bulk_upload/poll.js, src/v0/destinations/marketo_bulk_upload/util.js, test/__tests__/data/marketo_bulk_upload_jobStatus_output.json
=> chore(release): pull hotfix-release/v1.54.2 into main

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/hs/config.js
=> chore(release): pull hotfix-release/v1.54.3 into main

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/reddit/procWorkflow.yaml, test/integrations/destinations/reddit/processor/data.ts, test/integrations/destinations/reddit/router/data.ts
=> chore(release): pull hotfix-release/v1.54.4 into main

src/v0/destinations/intercom/config.js, src/v0/destinations/intercom/data/INTERCOMGroupConfig.json, src/v0/destinations/intercom/data/INTERCOMIdentifyConfig.json, src/v0/destinations/intercom/data/INTERCOMTrackConfig.json, src/v0/destinations/intercom/transform.js, src/v0/destinations/intercom/util.js, src/v0/destinations/intercom/util.test.js, test/integrations/destinations/intercom/processor/data.ts, test/integrations/destinations/intercom/router/data.ts
- Raised pr to restore intercom js code. we need this code till next config-schema release (which is tomorrow), so that hosted will work as expected
N/A
N/A
N/A
N/A
<hr>
=> chore: restore intercom js code

test/integrations/testUtils.ts
enable batch response schema check
https://linear.app/rudderstack/issue/INT-1298/enhance-component-test-suite-to-do-server-contract-validations-for
Adding contract validations for batch endpoint.
N/A
N/A
N/A
N/A
<hr>
=> chore: enable batch response schema check

src/v0/destinations/am/transform.js, src/v0/destinations/am/util.test.js, src/v0/destinations/am/utils.js, test/integrations/destinations/am/processor/data.ts
For amplitude when there is no name present in page or screen calls and user has configured to use user defined template for event name and there is no event coming in it results in error from amplitude side.
We have introduced a check to catch this type of erros
Resolves INT-1564
N/A
N/A
N/A
N/A
<hr>
=> fix: amplitude: Error handling for missing event type

src/v0/destinations/tiktok_ads/transformV2.js, test/integrations/destinations/tiktok_ads/processor/data.ts
Tiktok ads v2 error handling for missing properties.
Bugsnag error -> https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/65ca9a321803670008ffa9d2?filters%5Berror.status%5D=open&filters%5Bevent.since%5D=30d
Resolves INT-1587
N/A
N/A
N/A
N/A
<hr>
=> fix: tiktok ads v2 error handling

src/v0/destinations/ga4/networkHandler.js
=> fix(ga4): failures not considered with 200 status in events tab

src/v0/destinations/tiktok_ads_offline_events/config.js, test/integrations/destinations/tiktok_ads_offline_events/processor/data.ts
Adding support for all Standard event supported by tiktok_ads_offline. [Tiktok Docs](https://ads.tiktok.com/help/article/about-offline-conversions?lang=en)
Currently we support only 4 standard events out of 14 standard events that tiktok supports.
in this PR I have added support for the remaining 10 events ones as well.
Resolves INT-1554
N/A
N/A
N/A
N/A
<hr>
=> feat: tiktok_offline_events added support for all Standard  events

test/integrations/destinations/ga4/dataDelivery/data.ts, test/integrations/destinations/ga4/network.ts
1. Onboard GA4 proxy tests
Resolves INT-1593
N/A
N/A
N/A
N/A
<hr>
=> chore: onboard ga4 proxy tests

src/v0/destinations/af/deleteUsers.js, src/v0/destinations/am/deleteUsers.js, src/v0/destinations/braze/deleteUsers.js, src/v0/destinations/clevertap/deleteUsers.js, src/v0/destinations/custify/deleteUsers.js, src/v0/destinations/engage/deleteUsers.js, src/v0/destinations/intercom/deleteUsers.js, src/v0/destinations/iterable/deleteUsers.js, src/v0/destinations/mp/deleteUsers.js, src/v0/destinations/sendgrid/deleteUsers.js, src/v0/destinations/sprig/deleteUsers.js, src/v0/util/tags.js
1. Added status code stat tag for user deletion
N/A
N/A
N/A
N/A
<hr>
=> chore: added statuscode stat for user deletion

src/cdk/v2/destinations/reddit/procWorkflow.yaml, test/integrations/destinations/reddit/processor/data.ts
reddit supports 2 fields for revenue one is for cents (whole numbers) and other is for dollars (decimal numbers) but we have a bug for mapping revenue to cents.
https://ads-api.reddit.com/docs/v2/#tag/Conversions/paths/~1api~1v2.0~1conversions~1events~1%7Baccount_id%7D/post
Resolves INT-1645
N/A
N/A
N/A
N/A
<hr>
=> fix: reddit revenue mapping for floating point values

src/cdk/v2/destinations/rakuten/data/propertiesMapping.json, test/integrations/destinations/rakuten/processor/transformationFailure.ts
Syncing properties mapping to standard rudderstack spec
Resolves INT-1675
N/A
N/A
N/A
N/A
<hr>
=> fix: rakuten: sync property mapping sourcekeys to rudderstack standard spec

src/util/prometheus.js
Add missing source label to shopify prometheus stat
Resolves INT-1694
N/A
N/A
N/A
N/A
<hr>
=> chore: add missing prometheus label for shopify stat

src/cdk/v2/destinations/algolia/procWorkflow.yaml, test/integrations/destinations/algolia/processor/data.ts
added check for objectIds or filters to be non empty
Resolves INT-1650
N/A
N/A
N/A
N/A
<hr>
=> fix(algolia): added check for objectIds or filters to be non empty

src/v0/destinations/branch/transform.js, src/v0/destinations/branch/utils.js, src/v0/destinations/branch/utils.test.js, test/integrations/destinations/branch/processor/data.ts
- Add a support to override the default event name mapping defined in eventMapping.js using eventsMapping configured in UI
Resolves INT-1667
https://github.com/rudderlabs/rudder-integrations-config/pull/1238
N/A
N/A
N/A
N/A
<hr>
=> feat: add event mapping support for branch destination

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/branch/transform.js, src/v0/destinations/branch/utils.js, src/v0/destinations/branch/utils.test.js, src/v0/destinations/marketo_bulk_upload/transform.js, test/integrations/destinations/branch/processor/data.ts, test/integrations/destinations/marketo_bulk_upload/processor/data.ts
=> chore(release): pull hotfix-release/v1.57.0 into main

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/am/transform.js, src/v0/destinations/am/util.test.js, src/v0/destinations/am/utils.js
=> chore(release): pull hotfix-release/v1.57.1 into main

github-release.config.js, package.json
release fix feat, bug order
N/A
N/A
N/A
N/A
<hr>
=> fix: release fix feat, bug order

github-release.config.js, package.json
=> fix: release action git

src/v0/destinations/clevertap/data/CleverTapIdentify.json, test/integrations/destinations/clevertap/processor/data.ts
Discussed here: https://linear.app/rudderstack/issue/INT-1744/generic-mapping-issues-for-emails
Resolves INT-1744
N/A
N/A
N/A
N/A
<hr>
=> fix: email mapping for clevertap

src/v1/destinations/campaign_manager/networkHandler.js, test/integrations/destinations/campaign_manager/dataDelivery/oauth.ts, test/integrations/destinations/campaign_manager/dataDelivery/other.ts
send proper status to server in cm360
Resolves INT-1509
N/A
N/A
N/A
N/A
<hr>
=> fix: send proper status to server in cm360

src/v1/destinations/algolia/networkHandler.js
=> fix: fixed 500 status for algolia dontBatch

.github/workflows/prepare-for-staging-deploy.yml
Update the file path for staging deployment file
Resolves INT-1851
N/A
N/A
N/A
N/A
<hr>
=> fix: update correct staging deployment file

src/cdk/v2/destinations/ninetailed/data/contextMapping.json, test/integrations/destinations/ninetailed/commonConfig.ts, test/integrations/destinations/ninetailed/processor/identify.ts
ninetailed: add default value for context.location as {} ie empty object
Resolves INT-1861
N/A
N/A
N/A
N/A
<hr>
=> feat: ninetailed: add default value for context.location as {}

src/cdk/v2/destinations/heap/procWorkflow.yaml, test/integrations/destinations/heap/processor/data.ts
make userId as required for track and identify call
Resolves INT-1857
N/A
N/A
N/A
N/A
<hr>
=> fix: heap: make userId as required for track and identify call

src/v0/sources/shopify/transform.js
`invalid_shopify_event` metric is sending `event` label which is not mentioned in `prometheus.js`. Through this PR. we are aiming to correct the implementation
Resolves INT-1862
N/A
N/A
N/A
N/A
<hr>
=> fix: shopify invalid_event metric prometheus label

.github/dependabot.yml
Improve dependabot workflow to track multiple dependencies
Resolves INT-1625
N/A
N/A
N/A
N/A
<hr>
=> chore: adding more package systems to dependabot

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/heap/procWorkflow.yaml, src/cdk/v2/destinations/ninetailed/data/contextMapping.json, src/features.json, src/v0/destinations/tiktok_ads/transform.js, src/v0/destinations/tiktok_ads/transformV2.js, test/integrations/destinations/heap/processor/data.ts, test/integrations/destinations/ninetailed/commonConfig.ts, test/integrations/destinations/ninetailed/processor/identify.ts, test/integrations/destinations/tiktok_ads/processor/data.ts
=> chore(release): pull hotfix-release/v1.60.0 into main

.github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
The deployment file paths for config-be-rudder-transformer was not correct.
Resolves INT-1914
N/A
N/A
N/A
N/A
<hr>
=> fix: deployment file paths

src/util/prometheus.js, src/v0/destinations/mp/transform.js, src/v0/destinations/mp/util.js
Adding batch size for each endpoint of `Mixpanel` destination
Resolves INT-1878
We are capturing this to get the info about how much each endpoint is packing.
N/A
N/A
N/A
N/A
<hr>
=> chore: add mixpanel batch size metrics

src/cdk/v2/destinations/fullstory/procWorkflow.yaml, test/integrations/destinations/fullstory/processor/data.ts
Fixed userId mapping, now mapping to uid instead of id
Resolves INT-1837
N/A
N/A
N/A
N/A
<hr>
=> fix: fixed userId mapping, now mapping to uid instead of id

src/v0/destinations/azure_datalake/transform.js, src/v0/destinations/azure_synapse/transform.js, src/v0/destinations/bq/transform.js, src/v0/destinations/clickhouse/transform.js, src/v0/destinations/deltalake/transform.js, src/v0/destinations/gcs_datalake/transform.js, src/v0/destinations/mssql/transform.js, src/v0/destinations/postgres/transform.js, src/v0/destinations/rs/transform.js, src/v0/destinations/s3_datalake/transform.js, src/v0/destinations/snowflake/transform.js, src/warehouse/index.js, test/__tests__/data/warehouse/dest_config_scenarios.js, test/__tests__/warehouse.test.js
Adding the ability to skip users table and tracks tables by looking at the destination config settings.
Applies to Warehouse only.
Fixes PIPE-137
N/A
N/A
N/A
N/A
<hr>
=> chore: skip users and tracks tables with destConfig

.github/workflows/prepare-for-staging-deploy.yml
Merge conflict occurred when we accidentally removed a line-break(present in `main`) in our previous conflict fix.
N/A
N/A
N/A
N/A
<hr>
=> fix: merge conflict with main

src/cdk/v2/destinations/fullstory/procWorkflow.yaml, test/integrations/destinations/fullstory/processor/data.ts
Reverting the following changes https://github.com/rudderlabs/rudder-transformer/pull/3192
N/A
N/A
N/A
N/A
<hr>
=> chore: revert "fix: fixed userId mapping, now mapping to uid instead of id"

.github/workflows/publish-new-release.yml, CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/fullstory/procWorkflow.yaml, test/integrations/destinations/fullstory/processor/data.ts
=> chore(release): pull hotfix-release/v1.61.1 into main

package-lock.json, package.json
Resolves package and other high vulnerabilities
Resolves INT-1846
N/A
N/A
N/A
N/A
<hr>
=> chore: resolves high packag vulnerabilities

src/util/openfaas/index.js
This PR adds cost tracking labels to the openfaas fn pods
Resolves IDP-395
N/A
N/A
N/A
N/A
<hr>
=> chore: add cost tracking labels to openfaas fn pods

src/v0/destinations/awin/transform.js, src/v0/destinations/awin/utils.js, src/v0/destinations/awin/utils.test.js, test/integrations/destinations/awin/data.ts
Adding product level tracking for track events.
ref : https://wiki.awin.com/index.php/Advertiser_Tracking_Guide/Product_Level_Tracking#PLT_Via_Conversion_Pixel
Resolves INT-1757
N/A
N/A
N/A
N/A
<hr>
=> feat: adding product level tracking for awin

src/util/utils.js
Resolves DAT-466
N/A
N/A
N/A
N/A
<hr>
=> chore: add logs on dns errors

src/v0/destinations/monday/util.js, test/integrations/destinations/monday/processor/data.ts, test/integrations/destinations/monday/router/data.ts
send group_id as string in  monday destination
Resolves INT-2020
N/A
N/A
N/A
N/A
<hr>
=> fix: send group_id as string in  monday destination

src/v0/destinations/twitter_ads/transform.js, test/integrations/destinations/twitter_ads/router/data.ts
fixed twitter_ads logger
N/A
N/A
N/A
N/A
<hr>
=> fix: twitter_ads logger

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/twitter_ads/transform.js, test/integrations/destinations/twitter_ads/router/data.ts
=> chore(release): pull hotfix-release/v1.62.2 into main

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/hs/HSTransform-v2.js, test/integrations/destinations/hs/processor/data.ts, test/integrations/destinations/hs/router/data.ts
=> chore(release): pull hotfix-release/v1.63.0 into main

src/v0/destinations/facebook_conversions/utils.js, test/integrations/destinations/facebook_conversions/processor/data.ts
Send content_ids as a string if there is only one value
N/A
N/A
N/A
N/A
<hr>
=> fix: send content_ids as a string if there is only one value

src/v0/destinations/awin/transform.js, src/v0/destinations/awin/utils.js, src/v0/destinations/awin/utils.test.js, test/integrations/destinations/awin/data.ts
Adding custom property support for awin at the transaction level.
Ref: https://wiki.awin.com/index.php/Advertiser_Tracking_Guide/Product_Level_Tracking#PLT_Via_Conversion_Pixel
Resolves INT-1757
N/A
N/A
N/A
N/A
<hr>
=> feat: custom property support AWIN

src/cdk/v2/destinations/ortto/procWorkflow.yaml, test/integrations/destinations/ortto/processor/data.ts
The logic to check for multiple mappings was not working properly.
When there were multiple mappings, due to an issue in logic it was picking only the last mapping by default even though the event points to an earlier mapping(as per array index)
Resolves INT-2069
N/A
N/A
N/A
N/A
<hr>
=> fix: multiple event mappings in ortto

src/cdk/v2/destinations/emarsys/config.js, src/cdk/v2/destinations/emarsys/procWorkflow.yaml, src/cdk/v2/destinations/emarsys/rtWorkflow.yaml, src/cdk/v2/destinations/emarsys/utils.js, src/cdk/v2/destinations/emarsys/utils.test.js, src/constants/destinationCanonicalNames.js, src/features.json, src/services/destination/nativeIntegration.ts, src/v0/destinations/emarsys/deleteUsers.js, src/v0/util/deleteUserUtils.js, src/v1/destinations/emarsys/networkHandler.js, test/integrations/destinations/emarsys/dataDelivery/data.ts, test/integrations/destinations/emarsys/deleteUsers/data.ts, test/integrations/destinations/emarsys/network.ts, test/integrations/destinations/emarsys/processor/data.ts, test/integrations/destinations/emarsys/router/data.ts
onboard emarsys
---------
N/A
N/A
N/A
N/A
<hr>
=> feat: onboard emarsys destination  (#3318)

src/v0/destinations/fb_custom_audience/transform.js, src/v0/destinations/fb_custom_audience/util.js, test/integrations/destinations/fb_custom_audience/processor/data.ts
Adding app secret support
Resolves INT-2075
N/A
N/A
N/A
N/A
<hr>
=> feat: facebook custom audience app secret support

src/v0/destinations/google_adwords_offline_conversions/transform.js, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
As per the transformation contract, we need to send destination in transformed payload. While batching for store sales conversions in Google Adwords Offline Conversions, we are not sending destination information. Through this PR we are trying to fix this.
Resolves INT-2126
N/A
N/A
N/A
N/A
<hr>
=> fix: gaoc store sales batching transform contract

src/cdk/v2/destinations/ortto/procWorkflow.yaml, test/integrations/destinations/ortto/processor/data.ts, test/integrations/destinations/ortto/router/data.ts
We are removing the default values of gdpr, emailConsent and smsConsent.
Resolves INT-2161
N/A
N/A
N/A
N/A
<hr>
=> fix: remove default traits from ortto

src/v0/destinations/slack/util.js, test/integrations/destinations/slack/processor/data.ts
We are not checking whether traits are null or undefined so we added a check before considering it as an object.
Resolves INT-2149
N/A
N/A
N/A
N/A
<hr>
=> fix: add validation for null/undefined traits in slack

src/v0/destinations/facebook_conversions/transform.js, src/v0/destinations/facebook_pixel/transform.js, src/v0/destinations/facebook_pixel/utils.js, src/v0/destinations/facebook_pixel/utils.test.js, test/integrations/destinations/facebook_conversions/processor/data.ts, test/integrations/destinations/facebook_pixel/processor/validationTestData.ts
We are validating if the event is within 7 days or not. But we need to increase that to 62 days if the `action_source` is `physical_store`.
Resolves INT-2133
N/A
N/A
N/A
N/A
<hr>
=> fix: update validation of event duration

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/ortto/procWorkflow.yaml, src/v0/destinations/af/transform.js, src/v0/destinations/facebook_conversions/transform.js, src/v0/destinations/facebook_pixel/transform.js, src/v0/destinations/facebook_pixel/utils.js, src/v0/destinations/facebook_pixel/utils.test.js, src/v0/destinations/google_adwords_offline_conversions/transform.js, src/v0/destinations/slack/util.js, test/integrations/destinations/af/processor/data.ts, test/integrations/destinations/facebook_conversions/processor/data.ts, test/integrations/destinations/facebook_pixel/processor/validationTestData.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts, test/integrations/destinations/ortto/processor/data.ts, test/integrations/destinations/ortto/router/data.ts, test/integrations/destinations/slack/processor/data.ts
=> chore(release): pull hotfix-release/v1.66.1 into main

.github/workflows/build-push-docker-image.yml
In build-push-docker-image.yaml GHA, fetch and checkout the pull request head commit instead of merge commit
Resolves INT-2094
N/A
N/A
N/A
N/A
<hr>
=> chore: fetch and checkout the pull request head commit instead of merge commit

src/legacy/router.js, src/middleware.js, src/services/userTransform.ts, src/util/customTransformer-v1.js, src/util/customTransformer.js, src/util/customTransforrmationsStore-v1.js, src/util/customTransforrmationsStore.js, src/util/openfaas/index.js, src/util/prometheus.js, src/util/stats.js, src/util/statsd.js
=> feat: sre 456 ut move high cardinality histogram metrics to summaries cp

CHANGELOG.md, package-lock.json, package.json, src/legacy/router.js, src/services/userTransform.ts, src/util/customTransformer-v1.js, src/util/customTransformer.js, src/util/customTransforrmationsStore-v1.js, src/util/customTransforrmationsStore.js, src/util/openfaas/index.js, src/util/prometheus.js, src/util/stats.js, src/util/statsd.js
=> chore(release): pull hotfix-release/v1.67.0 into main

src/v0/sources/adjust/config.ts, src/v0/sources/adjust/mapping.json, src/v0/sources/adjust/transform.js, test/integrations/sources/adjust/data.ts
Resolves INT- 1826
N/A
N/A
N/A
N/A
<hr>
=> feat: onboarding adjust source

CHANGELOG.md, package-lock.json, package.json, src/services/userTransform.ts
=> chore(release): pull hotfix-release/v1.68.2 into main

CHANGELOG.md, package-lock.json, package.json, src/services/userTransform.ts
https://github.com/rudderlabs/rudder-transformer/pull/3445
N/A
N/A
N/A
N/A
<hr>
=> chore: conflict.fix.1.68.2 from main

package-lock.json, package.json
upgrade workflow engine package
Resolves INT-2160
N/A
N/A
N/A
N/A
<hr>
=> chore: upgrade packages

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, src/v0/destinations/gainsight/transform.js, src/v0/destinations/gainsight/util.js, src/v0/destinations/hs/HSTransform-v1.js, src/v0/destinations/hs/HSTransform-v2.js, src/v0/destinations/hs/transform.js, src/v0/destinations/hs/util.js, src/v0/destinations/marketo/transform.js, src/v0/destinations/marketo/util.js, src/v0/destinations/marketo_static_list/transform.js, src/v0/destinations/pardot/networkHandler.js, src/v0/destinations/rakuten/networkHandler.js, src/v0/destinations/snapchat_custom_audience/networkHandler.js, src/v0/destinations/the_trade_desk/networkHandler.js, src/v0/destinations/user/transform.js, src/v0/destinations/user/utils.js, src/v0/destinations/yahoo_dsp/transform.js, src/v0/destinations/yahoo_dsp/util.js, src/v0/destinations/zendesk/transform.js
Metadata has been propagated for intermediate API calls(to obtain extra metadata in metrics) for below destinations have been added
- pardot
- rakuten
- snapchat_custom_audience
- the_trade_desk
- yahoo_dsp
- braze
- user
- hubspot
- gainsight
- zendesk
- marketo
- marketo_static_list
Resolves INT-2152
N/A
N/A
N/A
N/A
<hr>
=> chore: enable labels for api calls - 3

src/v0/util/facebookUtils/networkHandler.js, test/integrations/destinations/facebook_pixel/dataDelivery/business.ts, test/integrations/destinations/facebook_pixel/dataDelivery/data.ts, test/integrations/destinations/fb_custom_audience/dataDelivery/business.ts, test/integrations/destinations/fb_custom_audience/network.ts
we were adding default message in facebook response handling for unknown error codes. Hence editing that for actual errors.
Resolves INT-2295
N/A
N/A
N/A
N/A
<hr>
=> fix: adding actual error messgae for default code in facebook destinations

src/util/prometheus.js
=> chore: remove unused stats

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/one_signal/config.js, src/v0/destinations/one_signal/data/OneSignalIdentifyConfigV2.json, src/v0/destinations/one_signal/data/OneSignalSubscriptionConfig.json, src/v0/destinations/one_signal/transform.js, src/v0/destinations/one_signal/transformV2.js, src/v0/destinations/one_signal/util.js, src/v0/destinations/one_signal/utils.test.js, test/integrations/destinations/one_signal/processor/commonConfig.ts, test/integrations/destinations/one_signal/processor/data.ts, test/integrations/destinations/one_signal/processor/data_v2.ts, test/integrations/destinations/one_signal/processor/group.ts, test/integrations/destinations/one_signal/processor/identify.ts, test/integrations/destinations/one_signal/processor/track.ts, test/integrations/destinations/one_signal/processor/validations.ts
=> chore(release): pull hotfix-release/v1.69.1 into main

src/util/ivmFactory.js, test/__tests__/user_transformation.test.js
=> chore: change in credential function name

src/legacy/router.js, src/services/userTransform.ts, src/util/customTransformer-v1.js, src/util/customTransformer.js, src/util/openfaas/index.js, src/util/prometheus.js
=> chore: remove high cardinality histogram metrics for UT

src/services/userTransform.ts, src/util/stats.js, src/util/statsd.js
=> chore: record ut events request size in summary

src/v0/destinations/google_adwords_remarketing_lists/recordTransform.js, src/v0/destinations/google_adwords_remarketing_lists/transform.js, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts, test/integrations/destinations/google_adwords_remarketing_lists/processor/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/audience.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/record.ts, test/integrations/testUtils.ts
Access token for GARL destination should be `access_token` not `accessToken`.
Resolves INT-2341
N/A
N/A
N/A
N/A
<hr>
=> fix: update access token key for garl destination

src/cdk/v2/destinations/clicksend/procWorkflow.yaml, test/integrations/destinations/clicksend/commonConfig.ts, test/integrations/destinations/clicksend/router/data.ts
The UI config variable name and one used in transformer code was out of sync.
N/A
N/A
N/A
N/A
<hr>
=> chore: correcting variable name in clicksend

src/cdk/v2/destinations/zapier/procWorkflow.yaml, test/integrations/destinations/zapier/processor/data.ts
fix: zapier event lowercase issue, while mapping it is not doing lower case and doing mapping
Resolves INT-2369
N/A
N/A
N/A
N/A
<hr>
=> fix: zapier event lower case issue

src/v0/destinations/ga4_v2/transform.ts
=> chore: update for config details

src/v0/util/facebookUtils/networkHandler.js, test/integrations/destinations/facebook_pixel/dataDelivery/data.ts, test/integrations/destinations/facebook_pixel/network.ts
The error code `21009` was unhandled currently in the source-code. With this fix, we are trying to handle it
Resolves INT-2372
N/A
N/A
N/A
N/A
<hr>
=> chore: handle error code 21009 for facebook destinations

CODEOWNERS
=> chore: add data management team access to routes controllers and services

src/v0/destinations/ga4/utils.js, src/v0/destinations/ga4_v2/customMappingsHandler.js
Added utility to remove nested objects from user_properties for ga4_v2
=> fix: ga4 v2 userproperties

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/intercom/utils.test.js
=> chore(release): pull hotfix-release/v1.71.3 into main

src/v0/destinations/ga4_v2/customMappingsHandler.js
Handle error for incorrect mappings
=> chore: add error handling for ga4 v2 custom mappings

src/v0/destinations/googlepubsub/util.js, test/integrations/destinations/googlepubsub/processor/data.ts
We are adding validation for event on google pubsub.
Resolves INT-2430
N/A
N/A
N/A
N/A
<hr>
=> fix: add validation for type in google pubsub

src/v0/destinations/tiktok_ads/data/TikTokTrackV2.json, src/v0/destinations/tiktok_ads/util.js, src/v0/util/index.js, test/integrations/destinations/tiktok_ads/processor/data.ts
This PR introduces new fields introduced for user object in tiktok ads refer [this](https://business-api.tiktok.com/portal/docs?id=1771101151059969#item-link-Web%20Standard%20Events) documentation for reference 
Resolves INT-2411
N/A
N/A
N/A
N/A
<hr>
=> feat: introduces new user fields in titkok ads

src/cdk/v2/destinations/cordial/config.js, src/cdk/v2/destinations/cordial/data/CordialIdentifyConfig.json, src/cdk/v2/destinations/cordial/data/CordialTrackConfig.json, src/cdk/v2/destinations/cordial/procWorkflow.yaml, src/cdk/v2/destinations/cordial/rtWorkflow.yaml, src/cdk/v2/destinations/cordial/utils.js, src/constants/destinationCanonicalNames.js, src/features.json, src/v0/destinations/sendinblue/transform.js, src/v0/destinations/sendinblue/util.js, src/v0/util/index.js, test/integrations/destinations/cordial/common.ts, test/integrations/destinations/cordial/network.ts, test/integrations/destinations/cordial/processor/data.ts, test/integrations/destinations/cordial/processor/identify.ts, test/integrations/destinations/cordial/processor/track.ts, test/integrations/destinations/cordial/processor/validation.ts, test/integrations/destinations/cordial/router/data.ts
Resolves INT-2386
N/A
N/A
N/A
N/A
<hr>
=> feat: onboard cordial destination

src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_remarketing_lists/network.ts
We were sending wrong value to `getAuthErrCategory` function for google ads remarketing lists destination.
N/A
N/A
N/A
N/A
<hr>
=> fix: garl get auth err category

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_remarketing_lists/network.ts
=> chore(release): pull hotfix-release/v1.72.1 into main

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/klaviyo/transform.js
=> chore(release): pull hotfix-release/v1.72.2 into main

src/v0/destinations/google_adwords_offline_conversions/utils.js, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_offline_conversions/network.ts
We missed the util function to move to new google specific authCategory identifier function.
Resolves INT-2456
N/A
N/A
N/A
N/A
<hr>
=> fix: update getConversionActionId function for gaoc

src/cdk/v2/destinations/cordial/procWorkflow.yaml, test/integrations/destinations/cordial/processor/validation.ts
=> fix: add validation for cordial destination

CODEOWNERS
=> fix: codeowners file

src/constants/destinationCanonicalNames.js, src/v0/destinations/ga4/transform.js, src/v0/destinations/ga4/utils.js, src/v0/destinations/ga4_v2/customMappingsHandler.js, src/v0/destinations/ga4_v2/transform.ts, test/integrations/destinations/ga4_v2/processor/customMappings.ts, test/integrations/testUtils.ts
Added support for Hybrid mode in Ga4 V2 by adding functionalities to read specific integration object values based on integration type and updating `clientId` and `sessionId` for the measurement protocol events
Resolves INT-2444
N/A
N/A
N/A
N/A
<hr>
=> fix: added support for ga4 v2 hybrid mode

CHANGELOG.md, package-lock.json, package.json, src/constants/destinationCanonicalNames.js, src/v0/destinations/ga4/transform.js, src/v0/destinations/ga4/utils.js, src/v0/destinations/ga4_v2/customMappingsHandler.js, src/v0/destinations/ga4_v2/transform.ts, test/integrations/destinations/ga4_v2/processor/customMappings.ts, test/integrations/testUtils.ts
=> chore(release): pull hotfix-release/v1.72.4 into main

swagger/components/examples/processor/failure.yaml, swagger/components/examples/processor/success.yaml, swagger/components/examples/router/failure.yaml, swagger/components/examples/router/success.yaml, swagger/components/schemas/request.yaml, swagger/components/schemas/routerTransformationRequest.yaml
Updated examples for swagger for router and processor.
Screenshots for Processor ,Router and Batch:
Processor:
Router:
Batch:
Resolves INT-2274
N/A
N/A
N/A
N/A
<hr>
=> feat: updated examples for swagger

CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull hotfix-release/v1.73.0 into main

src/v0/destinations/fb_custom_audience/config.js, src/v0/destinations/fb_custom_audience/util.test.js, test/integrations/destinations/fb_custom_audience/router/data.ts
ref: https://developers.facebook.com/blog/post/2024/05/21/introducing-facebook-graph-and-marketing-api-v20/
ref: https://developers.facebook.com/docs/marketing-api/reference/custom-audience/users/v20.0
Resolves INT-1900
N/A
N/A
N/A
N/A
<hr>
=> fix: fb custom audience version upgrade from v18 to v20

src/v0/destinations/facebook_pixel/config.js, src/v0/destinations/fb/config.js, test/integrations/destinations/facebook_pixel/processor/ecommTestData.ts, test/integrations/destinations/facebook_pixel/processor/validationTestData.ts, test/integrations/destinations/facebook_pixel/router/data.ts
ref :
-  https://developers.facebook.com/docs/marketing-api/conversions-api/using-the-api
- https://developers.facebook.com/docs/marketing-api/app-event-api/
- https://developers.facebook.com/docs/graph-api/reference/application/activities/
Resolves INT-1900
N/A
N/A
N/A
N/A
<hr>
=> fix: fb pixel and fb app events version upgrade

.github/workflows/build-pr-artifacts.yml, .github/workflows/check-pr-title.yml, .github/workflows/commitlint.yml, .github/workflows/component-test-report.yml, .github/workflows/dt-test-and-report-code-coverage.yml, .github/workflows/prepare-for-dev-deploy.yml, .github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml, .github/workflows/ut-tests.yml, .github/workflows/verify-server-start.yml, .github/workflows/verify.yml
Cancel already executing workflows when a PR is updated with new commits
Resolves INT-2419
N/A
N/A
N/A
N/A
<hr>
=> chore: cancel already existing workflows on pull request update

.github/workflows/build-push-docker-image.yml, .github/workflows/prepare-for-dev-deploy.yml, .github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
Updated the latest image's SHA to use merge commit of a PR rather than the head commit
Resolves INT-2419
N/A
N/A
N/A
N/A
<hr>
=> chore: update latest image sha

src/constants/destinationCanonicalNames.js, src/v0/destinations/clevertap/config.js, src/v0/destinations/clevertap/transform.js, src/v0/destinations/clevertap/utils.js, src/v0/destinations/clevertap/utils.test.js, test/integrations/destinations/clevertap/processor/data.ts
https://developer.clevertap.com/docs/upload-device-tokens-api
Resolves INT-2363
N/A
N/A
N/A
N/A
<hr>
=> feat: supporting device token type using integrations object

src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js, src/v0/util/googleUtils/index.js, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_remarketing_lists/network.ts
We are not handling the response properly when customerId is provided wrong by the customer. We are retrying those events with refresh_token authcategory despite aborting them. Also with the garl error response, we are not showing the entire destination response, fixed that also
N/A
N/A
N/A
N/A
<hr>
=> fix: update getAuthErrCategory and update error message for garl

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js, src/v0/util/googleUtils/index.js, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_remarketing_lists/network.ts
=> chore(release): pull hotfix-release/v1.73.1 into main

src/util/prometheus.js, src/util/redis/testData/shopify_source.json, src/v0/sources/shopify/transform.js, src/v0/sources/shopify/util.js
Incorporating the new format of shopify `cart_token` for identifier events only as the format change happened only for those
Resolves INT-2485
N/A
N/A
N/A
N/A
<hr>
=> fix: shopify: incorporate new shopify cart token format

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/transform.js, src/v0/destinations/braze/util.js, test/integrations/destinations/braze/processor/data.ts
Removes unnecessary reserved properties filtering for Braze
Fixes INT-2400
Customers are trying to sync specific fields which are allowed in Braze but we are filtering them as reserved which is incorrect.
=> fix: reserved properties

src/v0/util/index.js
=> fix: type null

src/v0/destinations/sendgrid/util.js, test/integrations/destinations/sendgrid/processor/data.ts
=> fix: sendgrid read root traits

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/sendgrid/util.js, test/integrations/destinations/sendgrid/processor/data.ts
=> chore(release): pull hotfix-release/v1.74.1 into main

src/v0/destinations/attentive_tag/util.js, test/integrations/destinations/attentive_tag/processor/data.ts
Added null, undefined properties check for attentive tag destination
Resolves INT-2522
N/A
N/A
N/A
N/A
<hr>
=> fix: handle attentive tag null, undefined properties

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/attentive_tag/util.js, src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/util.js, src/v0/destinations/hs/transform.js, src/v0/destinations/hs/util.js, src/v1/destinations/hs/networkHandler.ts, test/integrations/destinations/attentive_tag/processor/data.ts, test/integrations/destinations/hs/dataDelivery/business.ts, test/integrations/destinations/hs/dataDelivery/data.ts, test/integrations/destinations/hs/dataDelivery/other.ts, test/integrations/destinations/hs/network.ts, test/integrations/destinations/hs/router/data.ts
=> chore(release): pull hotfix-release/v1.75.0 into main

src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts, test/integrations/destinations/google_adwords_remarketing_lists/network.ts
We are returning 400 status code for concurrent_modification error but we should retry those events. So added a validation to return 500 status code.
Resolves INT-2536
N/A
N/A
N/A
N/A
<hr>
=> fix: add validation for concurrent_modification error

src/v0/destinations/clevertap/transform.js, test/integrations/destinations/clevertap/processor/data.ts
Resolves INT-2546
N/A
N/A
N/A
N/A
<hr>
=> fix: clevertap bugsnag issue

src/v0/destinations/snapchat_conversion/transform.js, test/integrations/destinations/snapchat_conversion/processor/data.ts
Resolves INT-2542
N/A
N/A
N/A
N/A
<hr>
=> fix: snapchat conversion bugsnag issue

src/v0/destinations/google_adwords_enhanced_conversions/config.js, test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/business.ts, test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_enhanced_conversions/network.ts, test/integrations/destinations/google_adwords_enhanced_conversions/processor/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/router/data.ts
We are updating google ads API version from 15 to 17 for GAEC destination.
Resolves INT-2304
N/A
N/A
N/A
N/A
<hr>
=> chore: update api version of google ads for gaec to 17 from 15

src/v0/sources/customerio/config.js, test/integrations/sources/customerio/data.ts
Resolves INT-2344
N/A
N/A
N/A
N/A
<hr>
=> feat: add support for customerio source email subscribed event

src/v0/destinations/reddit/networkHandler.js, test/integrations/destinations/reddit/dataDelivery/oauth.ts, test/integrations/destinations/reddit/network.ts
This PR fixes Reddit authorisation failed case handling.
Related doc: https://ads-api.reddit.com/docs/v2/#tag/Conversions
Resolves INT-2597
N/A
N/A
N/A
N/A
<hr>
=> fix: reddit authorisation failed case handling

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/reddit/networkHandler.js, test/integrations/destinations/reddit/dataDelivery/oauth.ts, test/integrations/destinations/reddit/network.ts
=> chore(release): pull hotfix-release/v1.76.1 into main

package-lock.json
ran npm audit fix
Resolves INT-2593
N/A
N/A
N/A
N/A
<hr>
=> fix: npm vulnerabilities

src/cdk/v2/destinations/koala/procWorkflow.yaml, test/integrations/destinations/koala/processor/data.ts
Add source attribute for compatibility purposes
N/A
N/A
N/A
N/A
<hr>
=> feat: include source attribute for identify messages for koala

go/webhook/testcases/testdata/testcases/pipedream/alias_type____type_and_user_id_is_given.json, go/webhook/testcases/testdata/testcases/pipedream/identify_type____type_and_user_id_is_given.json, test/integrations/testUtils.ts
Filter condition for checking if a source is a valid one is wrong.
Resolves INT-2589
N/A
N/A
N/A
N/A
<hr>
=> chore: source integration script filter condition

CHANGELOG.md, package-lock.json, package.json, src/util/customTransformer-faas.js, src/util/openfaas/index.js, test/__tests__/user_transformation.test.js
=> chore(release): pull hotfix-release/v1.77.1 into main

src/v0/util/index.js, src/v0/util/index.test.js
Circular json error would occur when we try to stringify an object who has deeply nested recursive payloads. The AxiosError object is recursive object in nature. In this PR we are removing `config` and `request` properties from error object when the error object is an instance of `AxiosError` class.
Resolves INT-2613
N/A
N/A
N/A
N/A
<hr>
=> fix: circular json bugsnag

src/util/openfaas/index.js
Adding a new env for capturing the stabilization window for the python transformations.
N/A
N/A
N/A
N/A
<hr>
=> fix: added support for window stabilization fix through envs

src/warehouse/index.js, test/__tests__/warehouse.test.js
check if object is converted to string and stringify it
Resolves [PIPE-1518](https://linear.app/rudderstack/issue/PIPE-1518/store-context-traits-in-a-single-column-for-malformed-payloads)
N/A
N/A
N/A
N/A
<hr>
=> chore: check if object is converted to string and stringify it

src/util/customTransformer-v1.js
=> chore: add configurable ivm execution timeout

CONTRIBUTING.md
Add contribution guide to develop first integration
N/A
N/A
N/A
N/A
<hr>
=> docs: add contribution guide for source integration

src/features.json
=> chore: enable router transform for http destination

src/cdk/v2/destinations/intercom/procWorkflow.yaml, src/cdk/v2/destinations/intercom/utils.js, test/integrations/destinations/intercom/network.ts, test/integrations/destinations/intercom/processor/identifyTestData.ts
We were not supporting random fields for lookups and for rETL events we are not sending custom_attributes properly. With this PR we are fixing these things.
Resolves INT-2684
N/A
N/A
N/A
N/A
<hr>
=> fix: support different lookup fields and custom_attributes for rETL events 

src/v1/destinations/ga4_v2/networkHandler.ts
Add network handler for ga4 v2, reusing the existing ga4 network handler
N/A
N/A
N/A
N/A
<hr>
=> chore: reuse ga4 network handler for ga4v2

CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull hotfix-release/v1.81.0 into main

src/cdk/v2/destinations/heap/procWorkflow.yaml, test/integrations/destinations/heap/processor/data.ts
We are using ?? the operator which only fallbacks if the value is null or undefined but the customer is sending the empty string '' so we need to use ||
Resolves INT-2779
N/A
N/A
N/A
N/A
<hr>
=> fix: heap userId extraction

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/heap/procWorkflow.yaml, test/integrations/destinations/heap/processor/data.ts
=> chore(release): pull hotfix-release/v1.82.1 into main

src/v0/destinations/ga4_v2/networkHandler.js, src/v1/destinations/ga4_v2/networkHandler.ts, test/integrations/destinations/ga4_v2/dataDelivery/business.ts, test/integrations/destinations/ga4_v2/dataDelivery/data.ts
Add network handler file for ga4 v2 in v0 implementation flow. The currently faulty network handler is written in v1 proxy flow.
N/A
N/A
N/A
N/A
<hr>
=> chore: add network handler file for ga4 v2 in v0 implementation flow

src/v0/destinations/tune/transform.js, test/integrations/destinations/tune/processor/trackTestData.ts, test/integrations/destinations/tune/router/data.ts
Taking subdomain as an input and other query parameters and updating the endpoint accordingly.
Resolves INT-282
N/A
N/A
N/A
N/A
<hr>
=> fix: endpoint fix for tune destination

src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, test/apitests/data_scenarios/cdk_v2/failure.json, test/apitests/data_scenarios/cdk_v2/success.json, test/apitests/data_scenarios/destination/proc/batch_input_multiplex.json, test/apitests/data_scenarios/destination/proc/multiplex_partial_failure.json, test/apitests/data_scenarios/destination/proc/multiplex_success.json, test/apitests/data_scenarios/destination/router/failure_test.json, test/integrations/destinations/pinterest_tag/processor/data.ts, test/integrations/destinations/pinterest_tag/router/data.ts, test/integrations/destinations/pinterest_tag/step/data.ts
This reverts commit f781a84ade98649d68cebf4da13c2ceff8df2df2.
N/A
N/A
N/A
N/A
<hr>
=> Revert "fix: add missing field for pinterest_tag single product events"

src/v0/destinations/google_adwords_enhanced_conversions/transform.js, test/integrations/destinations/google_adwords_enhanced_conversions/processor/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/router/data.ts
=> feat: gaec migration

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml, src/v0/destinations/google_adwords_enhanced_conversions/transform.js, src/v0/util/index.test.js, test/apitests/data_scenarios/cdk_v2/failure.json, test/apitests/data_scenarios/cdk_v2/success.json, test/apitests/data_scenarios/destination/proc/batch_input_multiplex.json, test/apitests/data_scenarios/destination/proc/multiplex_partial_failure.json, test/apitests/data_scenarios/destination/proc/multiplex_success.json, test/apitests/data_scenarios/destination/router/failure_test.json, test/integrations/destinations/google_adwords_enhanced_conversions/processor/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/router/data.ts, test/integrations/destinations/pinterest_tag/processor/data.ts, test/integrations/destinations/pinterest_tag/router/data.ts, test/integrations/destinations/pinterest_tag/step/data.ts
=> chore: resolve conflicts and merge main to develop

test/integrations/destinations/google_adwords_enhanced_conversions/router/data.ts
=> chore: resolve conflicts again

.github/workflows/verify.yml
Fixes github actions (lint) which used to stop when there are no unchanges ts/js files.
N/A
N/A
N/A
N/A
<hr>
=> chore: github action for unchanged commits fixed

src/v0/destinations/braze/config.js
=> fix: braze subscription batch size

src/v0/destinations/braze/braze.util.test.js, src/v0/destinations/braze/config.js
=> revert: braze batch

src/util/prometheus.js, src/v0/destinations/mailjet/transform.js
Currently we have no observability for how much data is being batched for mailjet hence we are adding metrics for the same.
=> chore: add metrics for mailjet

package-lock.json, src/cdk/v2/destinations/pinterest_tag/utils.js, src/v0/destinations/amazon_audience/utils.js, src/v0/destinations/google_adwords_remarketing_lists/recordTransform.js
Addressed these issues: https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&severities=MAJOR&sinceLeakPeriod=true&pullRequest=3893&id=rudderlabs_rudder-transformer
Resolves INT-2697
N/A
N/A
N/A
N/A
<hr>
=> refactor: code to address sonar issues

src/v0/destinations/braze/util.js
=> fix: removed console statement

.github/workflows/build-push-docker-image.yml
=> chore: fix build workflow

package.json
To silent ts & js test cases execution logs while running in local. For any failing tests, logs will be shown
N/A
N/A
N/A
N/A
<hr>
=> chore: silent testcase logs in local

src/v0/destinations/airship/transform.js, test/integrations/destinations/airship/processor/data.ts
Resolved minor bugsnag error. Updated the code to handle numeric value.
N/A
N/A
N/A
N/A
<hr>
=> fix(airship): resolved minor bugsnag error

src/routes/index.ts
Clean up unused env variable for swagger
Resolves INT-1181
=> chore: clean up unused env

package-lock.json, package.json
Resolves INT-3034
N/A
N/A
N/A
N/A
<hr>
=> chore: upgrade axios version to 1.7.9

src/v0/destinations/mp/transform.js, test/integrations/destinations/mp/processor/data.ts
dropping traits from event property for track call when dropTraitsInTrackEvent toggle is on.
Resolves INT-3100
N/A
N/A
N/A
N/A
<hr>
=> feat: added drop traits in track call feature for mixpanel

src/util/utils.js, src/util/utils.test.js
https://sonarcloud.io/project/issues?severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&types=BUG&id=rudderlabs_rudder-transformer&open=AYkw42KnZFDDOedsxVZw
Resolves INT-2990
N/A
N/A
N/A
N/A
<hr>
=> fix: sonar issues in user transformations static lookup

src/v0/destinations/adobe_analytics/utils.js
Refactor rudderPropToDestMap to address sonar issues
Resolves INT-2990
N/A
N/A
N/A
N/A
<hr>
=> fix: sonar issues in adobe analytics

CHANGELOG.md, package-lock.json, package.json, src/util/openfaas/index.js
=> chore(release): pull hotfix-release/v1.89.1 into main

src/util/worker.js
=> chore: aggregate metrics in worker thread - fix typo

src/cdk/v2/destinations/http/utils.js, src/cdk/v2/destinations/http/utils.test.js, test/integrations/destinations/http/common.ts, test/integrations/destinations/http/processor/configuration.ts, test/integrations/destinations/http/router/data.ts
Enclose constants with quotes in mappings
N/A
N/A
N/A
N/A
<hr>
=> feat(http): enclose constants with quotes in mappings

src/v0/destinations/google_adwords_offline_conversions/config.js, src/v0/destinations/google_adwords_offline_conversions/utils.test.js, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/business.ts, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_offline_conversions/network.ts, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
We are updating the google ads API version from v16 to v17 for google ads offline conversion destination.
N/A
N/A
N/A
N/A
<hr>
=> fix: update google ads api version for gaoc

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/google_adwords_offline_conversions/config.js, src/v0/destinations/google_adwords_offline_conversions/utils.test.js, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/business.ts, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_offline_conversions/network.ts, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
=> chore(release): pull hotfix-release/v1.90.1 into main

src/cdk/v2/destinations/http/procWorkflow.yaml, test/integrations/destinations/http/common.ts, test/integrations/destinations/http/processor/configuration.ts
Add support for isDefaultMapping
Resolves INT-3257
N/A
N/A
N/A
N/A
<hr>
=> feat(http): add support for isDefaultMapping

src/v0/destinations/twitter_ads/transform.js, test/integrations/destinations/twitter_ads/processor/data.ts, test/integrations/destinations/twitter_ads/router/data.ts
It fixes the existing twitter destination to transform content_price to a decimal string. 
Resolves INT-3265
N/A
N/A
N/A
N/A
<hr>
=> fix: content_price should be a number with decimal point in twitter ads

.github/workflows/build-pr-artifacts.yml, .github/workflows/build-push-docker-image.yml, .github/workflows/prepare-for-dev-deploy.yml, .github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml
Now fetching docker hub token from DOCKERHUB_TOKEN instead of DOCKERHUB_PROD_TOKEN
N/A
N/A
N/A
N/A
<hr>
=> chore: now fetching docker hub token from DOCKERHUB_TOKEN instead of DOCKERHUB_PROD_TOKEN

src/v0/destinations/snapchat_conversion/util.js, src/v0/destinations/snapchat_conversion/util.test.js
We are not handing integer phone numbers. With this pr we are fixing that.
N/A
N/A
N/A
N/A
<hr>
=> fix: snapchat util function for normalizing phone number

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/snapchat_conversion/util.js, src/v0/destinations/snapchat_conversion/util.test.js
=> chore(release): pull hotfix-release/v1.91.1 into main

src/v0/destinations/google_adwords_enhanced_conversions/config.js, src/v0/destinations/google_adwords_offline_conversions/config.js, src/v0/destinations/google_adwords_offline_conversions/utils.test.js, src/v0/destinations/google_adwords_remarketing_lists/config.js, test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/business.ts, test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_enhanced_conversions/network.ts, test/integrations/destinations/google_adwords_enhanced_conversions/processor/data.ts, test/integrations/destinations/google_adwords_enhanced_conversions/router/data.ts, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/business.ts, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_offline_conversions/network.ts, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts, test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_remarketing_lists/network.ts, test/integrations/destinations/google_adwords_remarketing_lists/processor/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts
We are updating Google Ads API from 17 to 18
Resolves INT-3229
N/A
N/A
N/A
N/A
<hr>
=> chore: update google ads api version from 17 to 18

src/index.ts, src/v0/destinations/lambda/transform.js, src/v0/destinations/marketo/transform.js, src/v0/destinations/marketo_static_list/transform.js, src/v0/destinations/marketo_static_list/transformV2.js, src/v0/destinations/salesforce/transform.js, src/v0/util/index.js, src/v0/util/recordUtils.js
This PR approaches to change the reference of the `getErrorRespEvents` function from integrations-lib to transformer internal util
N/A
N/A
N/A
N/A
<hr>
=> chore: update error function ref

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/linkedin_ads/config.js, test/integrations/destinations/linkedin_ads/dataDelivery/business.ts, test/integrations/destinations/linkedin_ads/dataDelivery/oauth.ts, test/integrations/destinations/linkedin_ads/network.ts, test/integrations/destinations/linkedin_ads/processor/configLevelFeaturesTestData.ts, test/integrations/destinations/linkedin_ads/processor/trackTestData.ts, test/integrations/destinations/linkedin_ads/processor/validationTestData.ts, test/integrations/destinations/linkedin_ads/router/data.ts
=> chore(release): pull hotfix-release/v1.91.3 into main

src/cdk/v2/destinations/zoho/rtWorkflow.yaml, src/cdk/v2/destinations/zoho/transformRecordV2.js, src/cdk/v2/destinations/zoho/transformRecordsV2.test.js, src/cdk/v2/destinations/zoho/utils.js, src/cdk/v2/destinations/zoho/utils.test.js, test/integrations/destinations/zoho/common.ts, test/integrations/destinations/zoho/network.ts, test/integrations/destinations/zoho/router/deletion.ts, test/integrations/destinations/zoho/router/upsert.ts
Resolves INT-3217
N/A
N/A
N/A
N/A
<hr>
=> feat: zoho vdmv2

src/v1/sources/shopify/webhookTransformations/serverSideTransform.js, test/integrations/sources/shopify/webhookTestScenarios/CheckoutEventsTests.ts, test/integrations/sources/shopify/webhookTestScenarios/GenericTrackTests.ts
minor addtions to library and integrations label in shopify checkout multiplexed identify calls
N/A
N/A
N/A
N/A
<hr>
=> chore: add missing library and integration label to checkout identify payloads

.vscode/launch.json, package.json
Unblocks the debugging, but still not able to debug from "JS debug terminal"
N/A
N/A
N/A
N/A
<hr>
=> fix: vs code debugger config

src/services/source/nativeIntegration.ts
logging the payload schema during source transformation error.
Resolves INT-3315
N/A
N/A
N/A
N/A
<hr>
=> chore: logging payload schema during source transformation error

.github/workflows/allure-test-reporter.yml
Fix allure workflow to push reports different repo
Resolves INT-3349
N/A
N/A
N/A
N/A
<hr>
=> chore: fix allure workflow

src/v0/destinations/hs/HSTransform-v2.js, src/v0/destinations/hs/util.js, test/integrations/destinations/hs/processor/data.ts, test/integrations/destinations/hs/router/data.ts
Resolves INT-3326
N/A
N/A
N/A
N/A
<hr>
=> fix: wrong method during update call when dont batch true

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/hs/HSTransform-v2.js, src/v0/destinations/hs/util.js, test/integrations/destinations/hs/processor/data.ts, test/integrations/destinations/hs/router/data.ts
=> chore(release): pull hotfix-release/v1.92.1 into main

test/integrations/destinations/hs/router/data.ts
Fixing hs test.
N/A
N/A
N/A
N/A
<hr>
=> chore: fixing hs component test to use masked secret

package-lock.json, package.json, src/cdk/v2/destinations/zoho/transformRecordV2.js, src/cdk/v2/destinations/zoho/utils.js, src/cdk/v2/destinations/zoho/utils.test.js, test/integrations/destinations/zoho/router/upsert.ts
Update the integration-lib to version v0.2.22
In transformRecordsV2 we are using the logic from the lib to fetch mandatory fields and duplication check fields as per zoho documentation. 
Resolves rev-1481
N/A
N/A
N/A
N/A
<hr>
=> chore: use the new intgration lib in zoho vdmv2 implementation

CONTRIBUTING.md, jest.config.js, jest.config.typescript.js, package-lock.json, test/integrations/component.test.ts, test/integrations/destinations/examples/processor/data.ts, test/integrations/destinations/examples/router/data.ts, test/integrations/testUtils.ts
Add support TDD by give option to skip tests to submit tests without actual implementation.
Resolves INT-3349
N/A
N/A
N/A
N/A
<hr>
=> chore: add skipping support to component test

.github/workflows/draft-new-release.yml, .github/workflows/publish-new-release.yml
Repo sync is [archived](https://github.com/repo-sync/pull-request) since AUG 2023. 
We should migrate to GitHub CLI as it is recommended by repo owner itself
Resolves INT-3411
N/A
N/A
N/A
N/A
<hr>
=> chore: use github cli to create pull request

src/v0/destinations/customerio_audience/type.ts, src/v0/destinations/customerio_audience/utils.test.ts
audience id should be string or integer
Resolves INT-3304
N/A
N/A
N/A
N/A
<hr>
=> fix: customer io audience id type

.coderabbit.yaml
Enable code rabbit for PR reviews
=> chore: enable code rabbit for PR review

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/airship/utils.ts, test/integrations/destinations/airship/processor/business.ts
=> chore(release): pull hotfix-release/v1.95.2 into main

src/util/openfaas/index.js
In order to add security context to pods, we need to create profile custom resource and pass this resource in the payload as annotations to faas-gateway
N/A
N/A
N/A
N/A
<hr>
=> chore: set profile config for openfaas INF-834

.github/workflows/publish-new-release.yml
Updated release notifications to reference groups instead of individual users, ensuring clearer and more streamlined communication.
N/A
N/A
N/A
N/A
<hr>
=> chore: update subteam in tagged user groups in release notif

.github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-ut-deploy.yml
Git workflows are fixed to create separate devops PRs for UT and DT
Resolves INT-3439
Clean up of devops git workflows
No
No
No
No
<hr>
=> fix: seperate dt and ut devops prs

src/cdk/v2/destinations/reddit/procWorkflow.yaml, src/cdk/v2/destinations/reddit/utils.js, test/integrations/destinations/reddit/processor/data.ts, test/integrations/destinations/reddit/router/data.ts
ref: https://business.reddithelp.com/s/article/about-event-metadata
removing unwanted fields from events.
Resolves INT-3241
N/A
N/A
N/A
N/A
<hr>
=> fix: removing unwanted fields from event metadata in reddit destination

src/v0/destinations/google_adwords_remarketing_lists/recordTransform.js, test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/record.ts
Add support for record v1 (new format) for event stream flows for google adwords remarketing list destination.
Resolves INT-3474
N/A
N/A
N/A
N/A
<hr>
=> feat: add record v1 support to event stream for garl

README.md
Updated readme
Resolves INT-3369
N/A
N/A
N/A
N/A
<hr>
=> chore(docs): update README on how to configure secrets in tests

src/sources/shopify/webpixelTransformations/pixelUtils.js
This pull request includes changes to improve the robustness of the code by adding optional chaining to several properties in the `pixelUtils.js` file. The most important changes include modifications to the `cartViewedEventBuilder`, `checkoutEventBuilder`, and `checkoutStepEventBuilder` functions.
Improvements to robustness:
* [`src/sources/shopify/webpixelTransformations/pixelUtils.js`](diffhunk://#diff-19746390701cbf99bc397cfd271f331a813188c76a1e0572d5942459315760b0L85-R85): Modified the `cartViewedEventBuilder` function to use optional chaining for accessing `cart.id` to prevent potential runtime errors.
* [`src/sources/shopify/webpixelTransformations/pixelUtils.js`](diffhunk://#diff-19746390701cbf99bc397cfd271f331a813188c76a1e0572d5942459315760b0L166-R166): Modified the …
=> chore: fix null undefined check by optional chaining

src/v0/destinations/af/transform.js, src/v0/destinations/marketo_static_list/transformV2.js, src/v0/destinations/snapchat_conversion/transform.js, src/v1/destinations/emarsys/networkHandler.js
Resolves INT-3489
N/A
N/A
N/A
N/A
<hr>
=> chore: remove conplexity issue and redundant comments

src/cdk/v2/destinations/userpilot/procWorkflow.yaml, test/integrations/destinations/userpilot/processor/data.ts
This pull request includes several changes to improve the handling of user and company data in the Userpilot integration, as well as a version update. The most important changes include updating the response structure, adding validation for company ID, and modifying test data to reflect these changes.
* [`src/cdk/v2/destinations/userpilot/procWorkflow.yaml`](diffhunk://#diff-1f2e395df2b234137e75dec0466f4ecf5d5d716366fd50c97965776eb04922acR35-R39): Added assertion to check for the presence of company ID in the company object within contextual traits. Updated payload structure to include the company object. [[1]](diffhunk://#diff-1f2e395df2b234137e75dec0466f4ecf5d5d716366fd50c97965776eb04922acR35-R39) [[2]](diffhunk://#diff-1f2e395df2b234137e75dec0466f4ecf5d5d716366fd50c97965776eb04922acL53- …
=> fix: userpilot transformations

src/cdk/v2/destinations/userpilot/procWorkflow.yaml, test/integrations/destinations/userpilot/processor/data.ts
This pull request updates the `procWorkflow.yaml` and test data for the Userpilot destination to improve payload handling and validation. It introduces a more robust mechanism to handle optional fields, removes strict requirements for company IDs, and updates test cases to reflect these changes.
N/A
N/A
N/A
N/A
<hr>
=> chore: update company check

.github/workflows/build-pr-artifacts.yml, .github/workflows/ingestion-service-test.yml
Resolves INT-2926
N/A
N/A
N/A
N/A
<hr>
=> chore: run ingestion svc test after artefacts build

src/v0/destinations/mp/transform.js
Resolves INT-3555
N/A
N/A
N/A
N/A
<hr>
=> fix: revert validation in mixpanel

src/util/dynamicConfigParser.test.ts, src/util/dynamicConfigParser.ts
- Fix bug where original event was being modified instead of cloned event
- Add comprehensive tests to verify the fix works correctly
- Implement table-driven tests for better maintainability
Resolves INT-3571
N/A
N/A
N/A
N/A
<hr>
=> fix(dynamicConfigParser): fix cloning issue in getdynamicconfig method

src/adapters/network.js, src/adapters/network.test.js, test/integrations/destinations/mp/dataDelivery/proxyV1.ts
We will now return an error if we fail to do gzip compression while making the payload for data delivery
Resolves INT-3480
N/A
N/A
N/A
N/A
<hr>
=> chore: return error when gzip compression fails

src/v0/destinations/snapchat_conversion/util.js, src/v0/destinations/snapchat_conversion/util.test.js, test/integrations/destinations/snapchat_conversion/processor/data.ts
Resolves INT-2703
N/A
N/A
N/A
N/A
<hr>
=> chore: improving code coverage of snapchat conversion

src/middleware.js, src/middleware.test.js
Enable `profile_cpu-cpu` for pyroscope along with `profile_cpu-wall` data for cpu specific profile information.
Resolves INT-3493
N/A
N/A
N/A
N/A
<hr>
=> chore: enable collection of cpu data

src/v0/destinations/zendesk/transform.js, src/v0/destinations/zendesk/util.js, src/v0/destinations/zendesk/util.test.js, test/integrations/destinations/zendesk/network.ts, test/integrations/destinations/zendesk/processor/data.ts, test/integrations/destinations/zendesk/router/data.ts
=> fix: zendesk indentify flow

.github/workflows/dt-test-and-report-code-coverage.yml
[Sonarcloud-github-action](https://github.com/SonarSource/sonarcloud-github-action/releases/tag/v4.0.0) will be deprecated in future. 
Sonarcloud recommends using [sonarqube-scan-action](https://github.com/SonarSource/sonarqube-scan-action)
Supported Link:
https://github.com/SonarSource/sonarcloud-github-action?tab=readme-ov-file#scan-your-code-with-sonarqube-cloud-
https://github.com/SonarSource/sonarqube-scan-action
Resolves INT-3584
N/A
N/A
N/A
N/A
<hr>
=> chore: change sonarcloud-github-action to sonarqube-scan-action

src/v0/destinations/tiktok_ads/config.js, test/integrations/destinations/tiktok_ads/processor/data.ts
Added a new mapping for TikTok ads. Below is the list:
* Purchase
* Lead
* CustomizeProduct
* FindLocation
* Schedule
Tiktok standred event link:
https://ads.tiktok.com/help/article/standard-events-parameters?lang=en
Resolves INT-3610
N/A
N/A
N/A
N/A
<hr>
=> feat: add new event mapping for tiktok

package.json
Remove default node_options from the start command,
N/A
N/A
N/A
N/A
<hr>
=> feat: remove hardcoded node_options

src/index.ts, src/middlewares/routeActivation.ts, src/routes/index.ts
properly using dotenv with import ([link](https://www.npmjs.com/package/dotenv#how-do-i-use-dotenv-with-import))
=> chore: correct dotenv import

src/sources/shopify/webhookTransformations/serverSideTransform.js, src/sources/shopify/webhookTransformations/serverSideUtils.test.js, src/sources/shopify/webhookTransformations/serverSideUtlis.js
This pull request introduces a new utility function, `ensureAnonymousId`, to guarantee that every message has an `anonymousId`, using a UUID as a fallback if one is not present. The changes also include corresponding updates to the codebase and unit tests to integrate and validate this functionality.
* **Definition and Implementation**:
- Added the `ensureAnonymousId` function in `serverSideUtlis.js`. This function checks if a message has an `anonymousId` and generates a random UUID if it is missing. It also logs the event using the `stats.increment` method.
- Exported `ensureAnonymousId` in the `module.exports` object of `serverSideUtlis.js`.
* **Integration in Event Processing**:
- Updated the `processEvent` function in `serverSideTransform.js` to call `ensureAnonymousId` after setting …
=> fix: add uuid as fallback to missing anonymousId in webhook events

src/util/customTransformer.js, src/util/ivmFactory.js
Resolves DAW-1365
N/A
N/A
N/A
N/A
<hr>
=> chore: pass copy of metadata to avoid actual metadata modifications

RUDDER_TEST_DESTINATION_PLAN.md, src/v0/util/index.js, src/v0/util/index.test.js, test/integrations/component.test.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
This PR fixes inconsistent ordering in batch processing for Google AdWords Offline Conversions by implementing deterministic sorting based on jobId.
- **Enhanced `removeDuplicateMetadata` function**: Added sorting by jobId to ensure consistent metadata ordering within each batch
- **Enhanced `combineBatchRequestsWithSameJobIds` function**: Added sorting of final batch results by minimum jobId to ensure consistent batch ordering
- **Updated function documentation**: Clarified that the function now ensures consistent ordering
- **Re-enabled router output assertion**: Removed `google_adwords_offline_conversions` from the exclusion list in component tests
- **Updated test data ordering**: Modified test data in `test/integrations/destinations/google_adwords_offline_conversions/router/data.ts` …
=> fix: ensure consistent ordering in batch processing for google adwords offline conversions

src/v0/destinations/slack/transform.js, test/integrations/destinations/slack/processor/data.ts
This pull request introduces a new custom Handlebars helper in the Slack transformation logic to enhance template rendering.
Enhancements to Slack transformation:
* [`src/v0/destinations/slack/transform.js`](diffhunk://#diff-f670eb3a2bc1c16ced1e2eb5c5d56d576ec0e0f703b6934366c69f1d8ad72d37R22-R24): Added a custom Handlebars helper named `newline` to insert newline characters (`\n`) in templates. This change improves flexibility in formatting Slack messages.
Resolves INT-3728
N/A
N/A
N/A
N/A
<hr>
=> fix: handle newline for slack

CHANGELOG.md, package-lock.json, package.json, src/util/prometheus.js, src/v0/destinations/klaviyo/batchUtil.js, src/v0/destinations/klaviyo/config.js, src/v0/destinations/klaviyo/util.js, src/v0/destinations/slack/transform.js, test/integrations/destinations/klaviyo/processor/identifyTestDataV2.ts, test/integrations/destinations/slack/processor/data.ts
=> chore(release): pull hotfix-release/v1.101.1 into main

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/iterable/deleteUsers.js
Fix merge conficts from 1.101.2 to develop, this is create to unblock pr: https://github.com/rudderlabs/rudder-transformer/pull/4385
Resolves INT-3772
N/A
N/A
N/A
N/A
<hr>
- [] Is the type of change in the PR title appropriate as per the changes?
=> chore: fix merge conflicts from 1.101.2 to develop

src/v0/destinations/salesforce/utils.js, src/v0/destinations/twitter_ads/transform.js, src/v0/destinations/twitter_ads/util.js, src/v0/destinations/twitter_ads/utils.test.js, src/v0/destinations/x_audience/utils.js, test/integrations/destinations/salesforce/processor/data.ts, test/integrations/destinations/twitter_ads/processor/data.ts, test/integrations/destinations/twitter_ads/router/data.ts, test/integrations/destinations/x_audience/processor/data.ts, test/integrations/destinations/x_audience/router/data.ts
Resolves INT-3607
N/A
N/A
N/A
N/A
<hr>
=> fix: handle empty oauth secret for multiple destination (#4295)

.vscode/tasks.json, scripts/common.ts, scripts/dtApiCurlCreation.ts, scripts/serverApiCurlCreation.ts
Resolves INT-3795
N/A
N/A
N/A
N/A
<hr>
=> fix: ensure the testing tool is cross-platform compatible

src/util/prometheus.js, src/v0/destinations/klaviyo/config.js, src/v0/destinations/klaviyo/util.js, test/integrations/destinations/klaviyo/processor/groupTestDataV2.ts, test/integrations/destinations/klaviyo/processor/identifyTestDataV2.ts, test/integrations/destinations/klaviyo/processor/screenTestDataV2.ts, test/integrations/destinations/klaviyo/processor/trackTestDataV2.ts, test/integrations/destinations/klaviyo/router/dataV2.ts
This pull request removes support for the `2024-06-15` and `2024-10-25` Klaviyo API revisions, consolidating all references to a single `2024-10-15` revision. Additionally, it removes temporary metrics and configuration options related to the `2024-10-25` revision. The changes simplify the codebase and update relevant tests.
Resolves INT-3787
N/A
N/A
N/A
N/A
<hr>
=> chore: update klaviyo version to 2024-10-15, remove config restricted changes

src/v0/destinations/hs/HSTransform-v1.js, src/v0/destinations/hs/HSTransform-v2.js, src/v0/destinations/tiktok_ads/transform.js, src/v0/destinations/tiktok_ads/transformV2.js, src/v0/util/index.js, src/v0/util/index.test.js, test/integrations/component.test.ts, test/integrations/destinations/hs/router/data.ts, test/integrations/destinations/tiktok_ads/router/data.ts
Resolves INT-3734
N/A
N/A
N/A
N/A
<hr>
=> fix: rt event ordering for hs

src/v0/destinations/zendesk/transform.js, test/integrations/destinations/zendesk/network.ts, test/integrations/destinations/zendesk/processor/data.ts
Resolves INT-3824
N/A
N/A
N/A
N/A
<hr>
=> feat: update primary email verification status

test/integrations/component.test.ts
Added configuration for batch processing defaults in component tests to ensure tests use batch processing with specific settings.
N/A
The change configures batch processing defaults with lower values specifically for component tests. This ensures that tests properly exercise the batch processing functionality with controlled parameters:
- `batchSize: 1`
- `yieldThreshold: 1`
- `sequentialProcessing: true`
N/A
N/A
N/A
This change only affects test execution and does not impact production behavior.
<hr>
=> test: configure batch processing defaults for component tests

.github/workflows/prepare-for-prod-dt-deploy.yml
Remove broken workflow to update dedicated deployment of transformer with the lates version
N/A
N/A
N/A
N/A
<hr>
=> chore: remove broken workflow to updating dedicated deployment

test/integrations/destinations/mailchimp/router/data.ts
This pull request adds a new test case to the `data.ts` file under the Mailchimp router integration. The test case validates the functionality of event batching for multiple destinations, including handling successful and error scenarios.
* **New test case for event batching**: Introduced a test scenario to validate the batching of events for multiple Mailchimp destinations. The test includes various input messages with different configurations and metadata, such as `jobId`, `userId`, and external identifiers.
* **Output validation**:
- **Successful batch requests**: Ensures that valid events are batched and sent to the Mailchimp API with the correct headers, endpoint, and payload structure.
- **Error handling**: Verifies that invalid events (e.g., with incorrect status values) are …
=> chore(mailchimp): add router test with inputs contains different destnations

src/v0/destinations/mp/README.md, src/v0/destinations/mp/docs/businesslogic.md, src/v0/destinations/mp/docs/retl.md
Detailed AI generated documentation of mixpanel destination integration. Requires careful review by humans.
N/A
N/A
N/A
N/A
<hr>
=> chore: mixpanel ai generated documentation

CHANGELOG.md, src/v0/destinations/ga4_v2/transform.test.ts, src/v0/destinations/ga4_v2/transform.ts
* [`src/v0/destinations/ga4_v2/transform.ts`](diffhunk://#diff-b6515d6621eacbfab59751cc5b7dcf0ed4ccfb840bccc7633e1f9eb4ac6c69cfL2-R53): Refactored the configuration handling logic to avoid mutating the original `Config` object. An enhanced configuration object is now created and passed through the transformation process, improving code clarity and maintainability.
* [`src/v0/destinations/ga4_v2/transform.test.ts`](diffhunk://#diff-34c7d09891a03dfb37519ce7499392b6f6c623a38ecd9b664d40b150a5803387L92-R101): Updated test cases to validate the new configuration structure by using `expect.objectContaining` for nested properties.
N/A
N/A
N/A …
=> fix: enhance config object in ga4 v2 instead of mutating it

src/v0/destinations/google_adwords_offline_conversions/config.js, src/v0/destinations/google_adwords_offline_conversions/utils.js, src/v0/destinations/google_adwords_offline_conversions/utils.test.js, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/business.ts, test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts, test/integrations/destinations/google_adwords_offline_conversions/network.ts, test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts, test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
This pull request updates the Google Ads API integration to use version `v19` instead of `v18`. The changes include updates to API endpoints, references, and test configurations to ensure compatibility with the new API version.
* Updated `API_VERSION` from `v18` to `v19` in `src/v0/destinations/google_adwords_offline_conversions/config.js` and adjusted related endpoint references for `uploadClickConversions`, `uploadCallConversions`, and `searchStream`.
* Updated the comment link for transaction cost conversion to the `v19` reference in `src/v0/destinations/google_adwords_offline_conversions/utils.js`.
* Updated the reference link for `ClickConversion` in `src/v0/destinations/google_adwords_offline_conversions/utils.js`.
* Updated `API_VERSION` to `v19` in test files, including …
=> chore: update gaoc from v18 to v19

src/v0/destinations/mailchimp/utils.js
We are updating the error log to print the error response of the lookup on Mailchimp that might contain the email address used for the lookup. We are throwing an error with the response so it should be visible by the customer.
Resolves INT-3782
N/A
N/A
N/A
N/A
<hr>
=> chore: remove error logger from mailchimp

src/v0/destinations/iterable/README.md, src/v0/destinations/mp/README.md
Amplitude and Braze destination doc fixes
N/A
N/A
N/A
N/A
<hr>
=> chore: mp and iterable docs update

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/ga4_v2/transform.test.ts, src/v0/destinations/ga4_v2/transform.ts
Manually fixing the back merge PR: https://github.com/rudderlabs/rudder-transformer/pull/4442
=> chore(release): pull main into develop post release v1.103.0

src/v1/destinations/mp/utils.ts
Resolves INT-3639
N/A
N/A
N/A
N/A
<hr>
=> chore: improve error message log for mp

src/index.ts, src/middlewares/__tests__/memoryFencing.test.ts, src/middlewares/memoryFencing.ts
Updating memory usage every 100ms to avoid increased cpu utilization
=> fix: process memory usage method high cpu utilization

src/v0/destinations/splitio/README.md, src/v0/destinations/splitio/docs/businesslogic.md, src/v0/destinations/splitio/docs/retl.md
=> chore: ai generated docs for splitio

src/v0/destinations/facebook_conversions/README.md, src/v0/destinations/facebook_conversions/config.js, src/v0/destinations/facebook_conversions/docs/businesslogic.md, src/v0/destinations/facebook_conversions/docs/retl.md
=> chore: ai generated docs for facebook conversions

src/v0/destinations/mailchimp/utils.js
We are updating the logger to include metadata to track the destination where this failure is happening.
Resolves INT-3782
N/A
N/A
N/A
N/A
<hr>
=> fix: update mailchimp logger to include metadata

src/v0/destinations/moengage/README.md, src/v0/destinations/moengage/docs/businesslogic.md, src/v0/destinations/moengage/docs/retl.md
=> chore: ai generated docs for moengage

src/index.ts, src/middlewares/errorHandler.ts, src/util/errorNotifier/bugsnag.js
Added graceful shutdown handling for uncaught exceptions in the Bugsnag error notifier. Instead of using `process.exit(1)` which terminates the process abruptly, the system now emits a `SIGTERM` signal to allow for graceful shutdown.
Resolves https://linear.app/rudderstack/issue/INT-3865/bugsnag-node-internal-alerts
This change improves the reliability and observability of the application when uncaught exceptions occur. By emitting `SIGTERM` instead of calling `process.exit(1)`, the application can:
1. **Graceful Shutdown**: Allow the application to properly close connections, complete ongoing operations, and clean up resources
2. **Better Logging**: Log the error details before initiating shutdown for better debugging
3. **Container Orchestration**: Work better with container …
=> fix: add graceful shutdown for uncaught exceptions in bugsnag

CHANGELOG.md, package-lock.json, package.json, src/index.ts, src/middlewares/errorHandler.ts, src/util/errorNotifier/bugsnag.js
=> chore(release): pull hotfix-release/v1.104.2 into main

.github/workflows/prepare-for-prod-dt-deploy.yml
We have skipped the cloning step, so the workflow to create pr on top of the operator is failing. We are adding that step here.
Resolves INT-3810
N/A
N/A
N/A
N/A
<hr>
=> fix: add cloning of operator repo in workflow

CHANGELOG.md, package-lock.json, package.json, src/util/metricsAggregator.js
=> chore(release): pull hotfix-release/v1.104.4 into main

CHANGELOG.md, package-lock.json, package.json, src/util/metricsAggregator.js, test/__tests__/metricsAggregator.test.js
=> chore(release): pull main into develop post release v1.104.5

CHANGELOG.md, package-lock.json, package.json, src/util/cluster.ts, src/util/metricsAggregator.js, src/v0/destinations/snapchat_conversion/transformV3.js, src/v0/destinations/snapchat_conversion/utilsV3.js, test/__tests__/metricsAggregator.test.js, test/integrations/destinations/snapchat_conversion/processor/dataV3.ts, test/integrations/destinations/snapchat_conversion/router/dataV3.ts
=> chore(release): pull hotfix-release/v1.104.6 into main

CHANGELOG.md, package-lock.json, package.json, src/util/cluster.ts, src/util/metricsAggregator.js, src/v0/destinations/snapchat_conversion/transformV3.js, src/v0/destinations/snapchat_conversion/utilsV3.js, test/__tests__/metricsAggregator.test.js, test/integrations/destinations/snapchat_conversion/processor/dataV3.ts, test/integrations/destinations/snapchat_conversion/router/dataV3.ts
=> chore(release): pull main into develop post release v1.104.6

src/services/destination/postTransformation.ts
This PR refactors the  method in the  to improve immutability by:
- Removing the  dependency from lodash
- Replacing deep cloning with shallow copying using spread operators
- Ensuring all object modifications are done immutably
N/A
The main objective is to improve code quality and performance by:
1. Reducing dependencies by removing unused  import
2. Improving performance by using shallow copies instead of deep cloning
3. Following functional programming principles with immutable operations
**No breaking changes.** The refactoring maintains the same functionality while improving the implementation approach.
**No new dependencies.** In fact, this removes the unused  import from lodash.
**No new utilities.** This is a refactoring of existing code to improve immutability patterns.
- …
=> refactor: improve immutability in postTransformation service

.github/workflows/build-pr-artifacts.yml, .github/workflows/check-pr-title.yml, .github/workflows/commitlint.yml, .github/workflows/create-hotfix-branch.yml, .github/workflows/draft-new-release.yml, .github/workflows/dt-test-and-report-code-coverage.yml, .github/workflows/housekeeping.yml, .github/workflows/ingestion-service-test.yml, .github/workflows/prepare-for-dev-deploy.yml, .github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-rollback.yml, .github/workflows/prepare-for-prod-ut-deploy.yml, .github/workflows/prepare-for-staging-deploy.yml, .github/workflows/publish-new-release.yml, .github/workflows/slack-notify.yml, .github/workflows/ut-tests.yml, .github/workflows/verify-server-start.yml, .github/workflows/verify.yml
This PR adds explicit permissions blocks to all GitHub Actions workflows to follow security best practices and address GitHub's security [recommendations](https://github.com/rudderlabs/rudder-transformer/security/code-scanning?query=is%3Aopen+branch%3Adevelop+rule%3Aactions%2Fmissing-workflow-permissions).
- Added `contents: read` permission to workflows that only need to read repository contents
- Added `contents: write` permission to workflows that need to create releases or push changes
- Added `id-token: write` permission to workflows that need OIDC tokens for authentication
- Added `actions: write` permission to workflows that need to create workflow artifacts
- Added `pull-requests: write` permission to workflows that need to comment on PRs
- Follows the principle of least privilege …
=> chore: add explicit permissions to GitHub Actions workflows

.github/workflows/prepare-for-prod-dt-deploy.yml, .github/workflows/prepare-for-prod-rollback.yml
Resolves INT-3952
N/A
N/A
N/A
N/A
<hr>
=> chore: refactor workflow files for better organization

README.md
Resolves INT-3795
N/A
N/A
N/A
N/A
<hr>
=> chore: add section for testing tool in readme

test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts, test/integrations/destinations/google_adwords_remarketing_lists/router/record.ts
Add test case to enhance batching scenarios
N/A
N/A
N/A
N/A
<hr>
=> chore: add test cases to enhance batching scenarios

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/klaviyo/batchUtil.js
=> chore(release): pull hotfix-release/v1.104.8 into main

.github/workflows/prepare-for-prod-dt-deploy.yml, CHANGELOG.md, package-lock.json, package.json, src/middleware.js, src/middleware.test.js
=> chore(release): pull hotfix-release/v1.105.1 into main

.github/actions/restart-deployment/action.yml, .github/workflows/prepare-for-dev-deploy.yml
This pull request introduces a new GitHub Action for restarting Kubernetes deployments and integrates it into the development deployment workflow. The main changes include the creation of the custom action and its usage in the workflow configuration.
* [`.github/actions/restart-deployment/action.yml`](diffhunk://#diff-a56eed66d5a480003a0d80c5f7780928f1b5a9a7faaf1f72df129c4b5e2fb84aR1-R69): Added a custom composite GitHub Action named `K8s Deployment Restart`. This action allows for restarting deployments in specified Kubernetes namespaces, with support for multiple namespaces and deployments. It configures AWS credentials, updates the kubeconfig, and executes the `kubectl rollout restart` command for each deployment in the provided namespaces.
* …
=> chore: restart deployment after creating a develop image

go/webhook/testcases/testdata/testcases/shopify/identify_call_for_customers_create_event_0.json, src/sources/shopify/pixelEventsMappings/productViewedEventMapping.json, src/sources/shopify/webpixelTransformations/pixelUtils.test.js, test/integrations/sources/shopify/pixelMappingTests/CheckoutEventsTests.ts, test/integrations/sources/shopify/pixelMappingTests/CheckoutStepsTests.ts, test/integrations/sources/shopify/pixelMappingTests/ProductEventsTests.ts
This pull request introduces updates to Shopify pixel event mappings and associated test scenarios, focusing on improving data accuracy and enabling previously skipped tests. The most significant changes include adjustments to the `sku` mappings, enabling tests for various Shopify events, and updates to test data timestamps.
* [`src/sources/shopify/pixelEventsMappings/productViewedEventMapping.json`](diffhunk://#diff-14a60d9f902161c6226871917e39d777a1e3cb29e410e03b570f3a6b8abb7e57L35-R35): Updated `sourceKeys` mapping from `productVariant.product.sku` to `productVariant.sku` for better alignment with Shopify's data structure.
Resolves INT-3906
N/A
N/A …
=> chore: update sku mappings for product viewed event

.github/workflows/prepare-for-dev-deploy.yml
Deployment restart was failing due to a missing checkout step. 
I added the step for each type of deployment restart action 
Resolves INT-3811
N/A
N/A
N/A
N/A
<hr>
=> chore: add checkout step for deployment restart action

CHANGELOG.md, package-lock.json, package.json, src/v1/destinations/iterable/strategies/track-identify.test.ts, src/v1/destinations/iterable/strategies/track-identify.ts, src/v1/destinations/iterable/utils.test.ts, src/v1/destinations/iterable/utils.ts
:crown: *An automated PR*
Resolves https://linear.app/rudderstack/issue/INT-3971/optimize-iterable-trackidentifystrategy-for-large-batch-processing
=> chore(release): pull hotfix-release/v1.105.2 into main

src/v0/destinations/airship/README.md, src/v0/destinations/airship/docs/businesslogic.md, src/v0/destinations/airship/docs/retl.md
=> chore: ai generated docs for airship

.github/workflows/publish-new-release.yml, .github/workflows/slack-notify.yml
This pull request updates Slack notification workflows to use the `chat.postMessage` method instead of specifying `channel-id` directly. The changes ensure that the channel information is explicitly passed within the payload, improving clarity and alignment with Slack API best practices.
* [`.github/workflows/publish-new-release.yml`](diffhunk://#diff-e43eb5ddcc0d90e7a3f85c8c60bffd437d93fcf8284e1f71b1b19c93fbf60eb0L176-R179): Replaced `channel-id` with `method: chat.postMessage` and added the `channel` field to the payload for release notifications.
* [`.github/workflows/slack-notify.yml`](diffhunk://#diff-4c782e921e0d271a8397236e20ca24abe9f763364962abce17287bffe1d02403L31-R34): Replaced `channel-id` with `method: chat.postMessage` and added the `channel` field to the payload for …
=> ci: add method to slack github action

.github/workflows/prepare-for-prod-ut-deploy.yml
Fixed the yaml path in the GitHub workflow for hosted user-transformer deployment. The paths were incorrectly using dot notation instead of the correct kebab-case format.
N/A
Updated the yaml evaluation paths in  from:
-  to 
-  to 
Fixed incorrect yaml path format that was preventing proper image configuration updates during deployment.
N/A
N/A
N/A
<hr>
=> fix: update yaml path for hosted user-transformer image config

src/util/customTransformer-v1.js, src/util/ivmFactory.js, test/__tests__/data/user_transformation_async_output_with_errors.json, test/__tests__/data/user_transformation_service_filter_output.json, test/__tests__/user_transformation_errors.test.js
Resolves DAW-1526
N/A
N/A
N/A
N/A
<hr>
=> chore: include transformation name in error stack trace

src/util/eventValidation.js, test/__tests__/eventValidation.test.js, test/__tests__/trackingPlan.test.js
Resolves DAW-1641
N/A
N/A
N/A
N/A
<hr>
=> feat: add keyword if under advance rule violations

CHANGELOG.md, package-lock.json, package.json, src/util/eventValidation.js, test/__tests__/trackingPlan.test.js
=> chore(release): pull hotfix-release/v1.107.1 into main

src/v0/destinations/tiktok_ads/util.js, src/v0/destinations/tiktok_ads/util.test.js, test/integrations/destinations/tiktok_ads/router/data.ts
Remove channel from evaluation of event_source for tiktok_ads
N/A
N/A
N/A
N/A
<hr>
=> fix: remove channel from eventSource evaluation for tiktok_ads

CHANGELOG.md, package-lock.json, package.json, src/v0/destinations/tiktok_ads/util.js, src/v0/destinations/tiktok_ads/util.test.js, test/integrations/destinations/tiktok_ads/router/data.ts
=> chore(release): pull hotfix-release/v1.107.2 into main

src/v0/destinations/braze/config.js, src/v0/destinations/braze/transform.js
Braze alias identity batching feature was behind an ENV based feature flag. This PR cleans up that ENV now that the feature is stable.
Resolves INT-3922
Post feature release feature flag clean up.
No
No
No
No
<hr>
=> chore: braze feature env cleanup

src/v0/destinations/campaign_manager/util.js, src/v0/destinations/campaign_manager/util.test.js, test/integrations/destinations/campaign_manager/processor/data.ts
Add proper error handling for invalid phone numbers in Campaign Manager normalizePhone function
`Note: This will not solve the actual integration issue. We will handle it seperately.`
The `normalizePhone` function was throwing unhandled 500 error (because of `parsePhoneNumber` was throwing unhandled INVALID_COUNTRY errors from `libphonenumber-js`) for invalid phone numbers instead of throwing proper 400 errors.
Added proper error handling to ensure the function always either returns a valid E.164 formatted phone number or throws an `InstrumentationError`.
- Added missing `throw new InstrumentationError('Invalid phone number')` for invalid cases
- Function now consistently handles all error scenarios instead of returning `undefined`
- **Low risk**: Only affects error handling, no …
=> fix(campaign_manager): handling normalizePhone function error

CHANGELOG.md, package-lock.json, package.json, src/util/eventValidation.js, test/__tests__/eventValidation.test.js
=> chore(release): pull hotfix-release/v1.107.5 into main

src/v0/destinations/customerio/util.js, src/v0/destinations/customerio/util.test.js, test/integrations/destinations/customerio/processor/data.ts
Resolves INT-4105
N/A
N/A
N/A
N/A
<hr>
=> fix: encoding behaviour for customerio endpoints

src/v0/destinations/af/config.js, src/v0/destinations/af/transform.js, test/integrations/destinations/af/processor/data.ts, test/integrations/destinations/af/processor/validation.ts, test/integrations/destinations/af/router/data.ts, test/integrations/testUtils.ts
Updated AF destination configuration and transform logic to improve data processing capabilities.
Resolves https://linear.app/rudderstack/issue/INT-4102/add-endpoint-path-details-in-rudder-transformer-for-top-15
This PR includes updates to the AF (AppsFlyer) destination integration:
- Enhanced AF destination configuration for better data handling
- Improved transform logic for more accurate data processing
- Updated test data and validation to ensure reliability
N/A
- Updated test utilities in testUtils.ts for better integration testing support
- All changes maintain backward compatibility
- Enhanced test coverage for better reliability
<hr>
=> feat(af): add endpoint path to responses

src/v0/destinations/ga4/utils.js, test/integrations/destinations/ga4/processor/ecomTestData.ts, test/integrations/destinations/ga4/processor/groupTestData.ts, test/integrations/destinations/ga4/processor/pageTestData.ts, test/integrations/destinations/ga4/processor/trackTestData.ts, test/integrations/destinations/ga4_v2/network.ts, test/integrations/destinations/ga4_v2/processor/customMappings.ts, test/integrations/testUtils.ts
This PR adds the `endpointPath` field to the GA4 destination response and updates all related test data to include this new field.
Resolves https://linear.app/rudderstack/issue/INT-4102/add-endpoint-path-details-in-rudder-transformer-for-top-15
The changes ensure consistency between the actual GA4 destination response and the test expectations by:
1. **Adding endpointPath field to GA4 utils response**: Both debug and production modes now include the `endpointPath` field in the response
2. **Updating testUtils**: The `transformResultBuilder` function now includes `endpointPath` in the expected output structure
3. **Updating test data**: All GA4 test data files have been updated to include the `endpointPath` field in their expected outputs
No breaking changes. This is purely additive - …
=> feat(ga4): add endpointPath field to response and update tests

CHANGELOG.md, package-lock.json, package.json, src/cdk/v2/destinations/linkedin_ads/config.js, src/cdk/v2/destinations/linkedin_audience/procWorkflow.yaml, src/v1/destinations/linkedin_ads/networkHandler.js, test/integrations/destinations/linkedin_ads/dataDelivery/business.ts, test/integrations/destinations/linkedin_ads/dataDelivery/oauth.ts, test/integrations/destinations/linkedin_ads/network.ts, test/integrations/destinations/linkedin_ads/processor/configLevelFeaturesTestData.ts, test/integrations/destinations/linkedin_ads/processor/trackTestData.ts, test/integrations/destinations/linkedin_ads/processor/validationTestData.ts, test/integrations/destinations/linkedin_ads/router/data.ts, test/integrations/destinations/linkedin_audience/processor/business.ts, test/integrations/destinations/linkedin_audience/processor/validation.ts, test/integrations/destinations/linkedin_audience/router/data.ts
=> chore(release): pull hotfix-release/v1.107.6 into main

CODEOWNERS
Removed global owners on the repo.
Resolves https://linear.app/rudderstack/issue/INT-4134/on-call-sep-17-to-23-mahesh-progress-on-following-tasks
N/A
N/A
N/A
N/A
<hr>
=> chore: remove integration platform from codeowners

CODEOWNERS
Updated CODEOWNERS without any segregation of platform group, it's only one group integrations now.
This PR https://github.com/rudderlabs/rudder-transformer/pull/4657 removed default code owners, fixing that too
N/A
N/A
N/A
N/A
<hr>
=> chore: updated codeowners file

test/integrations/destinations/dub/processor/common.ts, test/integrations/destinations/dub/processor/data.ts, test/integrations/destinations/dub/processor/leadEventTestData.ts, test/integrations/destinations/dub/processor/maskedSecrets.ts, test/integrations/destinations/dub/processor/saleEventTestData.ts, test/integrations/destinations/dub/processor/validationTestData.ts, test/integrations/destinations/dub/router/data.ts, test/integrations/testUtils.ts
Added a test for dub
Resolves INT-4095
N/A
N/A
N/A
N/A
<hr>
=> chore: add dub test

src/v0/destinations/dub/README.md, src/v0/destinations/dub/docs/businesslogic.md, src/v0/destinations/dub/docs/retl.md
Added AI-generated internal docs
Resolves INT-4197
N/A
N/A
N/A
N/A
<hr>
=> chore: add dub internal doc

src/cdk/v2/destinations/userpilot/procWorkflow.yaml
* fix: check on traits and traits.context
* prioritize message.context.traits
N/A
N/A
N/A
N/A
<hr>
=> fix: check on traits and traits.context (#4682)
