rudderlabs/rudder-transformer

data/GAEComGenericEventConfig.json
data/GANonEComEventConfig.json
data/GAPageViewConfig.json
data/GAPaymentRelatedEventConfig.json
data/GAProductEventConfig.json
data/GAProductListEventConfig.json
data/GAProductShareEventConfig.json
data/GAPromotionEventConfig.json
data/GARefundEventConfig.json
data/GAScreenViewConfig.json
data/GASharingEventConfig.json
data/GATransactionEventConfig.json
userTransformer.js

1. GA send ip
2. cid as user_id
3. filter AM events

Torpedo issues

---

data/GAEComGenericEventConfig.json
data/GANonEComEventConfig.json
data/GAPageViewConfig.json
data/GAPaymentRelatedEventConfig.json
data/GAProductEventConfig.json
data/GAProductListEventConfig.json
data/GAProductShareEventConfig.json
data/GAPromotionEventConfig.json
data/GARefundEventConfig.json
data/GAScreenViewConfig.json
data/GASharingEventConfig.json
data/GATransactionEventConfig.json
userTransformer.js

1. add ua for passing to GA
2. sample .25 events to GA

Torpedo fix

---

.gitignore
__tests__/data/user_transformation_filter_input.json
__tests__/data/user_transformation_filter_output.json
__tests__/data/user_transformation_input.json
__tests__/data/user_transformation_output.json
__tests__/user_transformation.test.js
destTransformer.js
package-lock.json
package.json
util/customTransformer.js
util/customTransforrmationsStore.js
versionedRouter.js

Fix in case of multiple destinations of the same type.
Add fetch to make API calls.

Custom transformation changes

---

__tests__/braze_test.js
__tests__/data/braze_input.json
__tests__/data/braze_output.json
v0/braze/transform.js

#77 
Merged it to develop to keep it in sync

braze append traits with track events & also tests

---

__mocks__/axios.js
__tests__/data/salesforce_input.json
__tests__/data/salesforce_output.json
__tests__/salesforce.test.js
v0/salesforce/config.js
v0/salesforce/data/SFIgnoreConfig.json
v0/salesforce/transform.js

Destination salesforce 2

---

__tests__/data/am_input.json
__tests__/data/am_output.json
__tests__/data/ga_input.json
__tests__/data/ga_output.json
__tests__/data/keen_input.json
__tests__/data/keen_output.json
__tests__/data/kochava_input.json
__tests__/data/kochava_output.json
v0/am/transform.js
v0/ga/transform.js
v0/keen/transform.js
v0/kochava/transform.js
v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/90)

ip fix and test case update

---

v0/braze/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/96)

null check for properties

---

__tests__/data/mp_input.json
__tests__/data/mp_output.json
v0/mp/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/104)

Mixpanel Revisit

---

v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/105)

Warehouse refactor raj

---

__tests__/data/slack_input.json
__tests__/data/slack_output.json
__tests__/slack.test.js
package-lock.json
package.json
v0/slack/config.js
v0/slack/transform.js

Fixes rudderlabs/rudder-qa#7
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/99)

Dest slack

---

__tests__/data/leanplum_output.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/108)

Updated output for leanplum test

---

v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/109)

Exclude rudder created table names from event name tables

---

v0/bq/data/WHDefaultConfig.json
v0/rs/data/WHDefaultConfig.json
v0/snowflake/data/WHDefaultConfig.json
v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/112)

Add additional columns for page and screen calls

---

v0/customerio/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/121)

Fixed screen events name

---

versionedRouter.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/126)

Fix for when incoming event contains an integer userId.

---

__tests__/data/am_output.json
v0/am/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/128)

Fix for min length of user ID is set to 1

---

v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/134)

Group call support in warehouse

---

v0/mp/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/133)

MixPanel bug Fixes

---

v0/mp/transform.js

Reverts rudderlabs/rudder-transformer#133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/136)

Revert "MixPanel bug Fixes"

---

v0/util.js

I will be adding tests for warehouse transformers in a separate task
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/137)

Fix setting column data type from prev computed value

---

v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/135)

Warehouse scheduling

---

__tests__/data/user_transformation_filter_input.json
__tests__/data/user_transformation_filter_output.json
__tests__/user_transformation.test.js
util/customTransformer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/138)

Adding support for metadata func

---

v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/140)

Fixed func signature in alias, group calls

---

v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/145)

Handle null json values

---

util/cluster.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/141)

Kill process when one of the worker dies

---

v0/kissmetrics/transform.js

1. 'screen' call support added
2. Application LifeCycle Event support added
3. Simple `track` call without properties fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/131)

Kissmetrics bug fixes

---

__tests__/data/am_output.json
v0/am/data/AmplitudeCoinsPurchasedEventConfig.json
v0/am/data/AmplitudeDefaultConfig.json
v0/am/data/AmplitudeIdentifyConfig.json
v0/am/data/AmplitudePageConfig.json
v0/am/data/AmplitudeProductActionsConfig.json
v0/am/data/AmplitudePromotionClickedConfig.json
v0/am/data/AmplitudePromotionViewedConfig.json
v0/am/data/AmplitudeRevenueConfig.json
v0/am/data/AmplitudeScreenConfig.json
v0/am/transform.js

1. rudderanalytics.page("test3", {"category": "test3"})
2. rudderanalytics.page()
3.  rudderanalytics.identify(
"12345",
{ email2: "hiji@domain.com" },
{
context: {
ip: "0.0.0.0"
},
anonymousId: "12345"
},
() => {
console.log("in identify call");
}
);
4. rudderanalytics.page()
5. rudderanalytics.page()
6. rudderanalytics.reset()
7.  rudderanalytics.page("test4", {"category": "test4"}, {integrations: {All: false, Amplitude:true}})
8. rudderanalytics.page("test2", {"category": "test2"}, {integrations: {All: false, Amplitude: true}})
**This call flow now gives correct identification match in AM dashboard**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/152)

AM identification

---

__tests__/data/kafka_input.json
__tests__/data/kafka_output.json
__tests__/data/kinesis_input.json
__tests__/data/kinesis_output.json
__tests__/kafka.test.js
v0/kafka/transform.js
v0/kinesis/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/150)

Master <- Kafka

---

__tests__/azure_event_hub.test.js
__tests__/data/azure_event_hub_input.json
__tests__/data/azure_event_hub_output.json
__tests__/data/kinesis_input.json
v0/azure_event_hub/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/153)

Azure event hub

---

.prettierrc
v0/util.js

ignoring symbols, letters whose ascii values are more than 127, handling letter case for wh destinations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/154)

modifyColumnName

---

buildspec.saas.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/156)

Build master into docker tag:latest and remove saas- prefix

---

__tests__/data/hs_output.json
v0/destinations/hs/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/163)

415 error in HS

---

warehouse/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/165)

Fix issue for identify event with null userId

---

v0/destinations/braze/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/166)

Braze Fixes

---

warehouse/v0/util.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/168)

Fix casing for redshift v0 transformer

---

v0/destinations/hs/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/178)

Hubspot key

---

v0/destinations/mp/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/182)

Mixpanel fixes dev

---

v0/destinations/mp/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/181)

Interim fixes for Mixpanel

---

buildspec.dev.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/185)

Modifying buildspec.dev.yaml to work with our new build workflow

---

v0/destinations/mp/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/186)

add identify/merge calls

---

warehouse/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/187)

Fix incorrect func signatures in wh tranformers

---

warehouse/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/188)

handled data type override to return string instead of undefined

---

__tests__/data/eventbridge_input.json
__tests__/data/eventbridge_output.json
__tests__/eventbridge.test.js
v0/destinations/eventbridge/transform.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/189)

Destination Eventbridge

---

v0/destinations/clickhouse/transform.js
warehouse/config/ReservedKeywords.json
warehouse/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/201)

clickhouse destination

---

__tests__/data/segment_input.json
__tests__/data/segment_output.json
__tests__/segment.test.js
v1/destinations/segment/transform.js

some minor change of segment transform.js

some minor change on segment

---

warehouse/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/322)

add boundaries for valid timestamps

---

warehouse/index.js

* add boundaries for valid timestamps
Co-authored-by: gane5hvarma <ganesh@rudderlabs>

add boundaries for valid timestamps (#322)

---

__tests__/warehouse.test.js
warehouse/index.js

* WH: Handle invalud values for context
* WH: Throw error if too many column
* add maxColumns from env

Wh: Handle invalid context values (#339)

---

__tests__/data/redis_input.json
v0/destinations/redis/transform.js

redis: handle empty object in traits

---

__tests__/data/redis_input.json
v0/destinations/redis/transform.js

SaaS <- Master

---

__tests__/data/redis_input.json
__tests__/data/redis_output.json
v0/destinations/redis/transform.js

redis: change handling empty strings

---

__tests__/data/redis_input.json
__tests__/data/redis_output.json
v0/destinations/redis/transform.js

redis: fix handling empty strings (#391)

---

__tests__/confluent_cloud.test.js
__tests__/data/confluent_cloud_input.json
__tests__/data/confluent_cloud_output.json
v0/destinations/confluent_cloud/transform.js

Confluent cloud

---

__tests__/data/indicative_input.json
__tests__/data/indicative_output.json
v0/destinations/indicative/data/INPageConfig.json
v0/destinations/indicative/data/INScreenConfig.json
v0/util/index.js

handle page and screen without name calls

---

__tests__/warehouse.test.js
warehouse/index.js
warehouse/util.js

> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-transformer/405)

remove default columns which has value with type object

---

__tests__/warehouse.test.js
warehouse/index.js

wh: delete rudder defined columns in event

---

__tests__/data/braze_input.json
__tests__/data/braze_output.json
v0/destinations/braze/transform.js
v0/util/data/GenericFieldMapping.json

Group support for Braze

---

__tests__/user_transformation.test.js
util/customTransformer-v1.js

> This PR is aimed to add on demand isolate VM support for
multi-tenant architecture.
> We introduce a environment variable ON_DEMAND_ISOLATE_VM
which when valuated to a non zero number means on demand
isolated VMs are to be used. Pooled way other wise.
> Fix [#1]()

Isolate VM support in V1

---

__tests__/data/userlist_input.json
__tests__/data/userlist_output.json
__tests__/userlist.test.js
v0/destinations/userlist/config.js
v0/destinations/userlist/transform.js
v0/util/index.js

This pull requests adds [Userlist](https://userlist.com) as a new destination.

Adds transform for Userlist

---

__tests__/data/marketo_output.json
__tests__/data/marketo_router_input.json
__tests__/data/marketo_router_output.json
__tests__/marketo.test.js
v0/destinations/marketo/transform.js
versionedRouter.js

Router transformer end point for marketo

---

util/customTransforrmationsStore.js

Remove transformer code TTL

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/transform.js
v0/util/index.js

Traits for AM cloud

---

__tests__/data/am_output.json
v0/destinations/am/transform.js

Fix: User properties

---

__tests__/data/marketo_router_input.json
v0/destinations/marketo/config.js
v0/destinations/marketo/transform.js
v0/util/index.js
v0/util/network.js

Marketo - Response rules handler

---

__tests__/data/marketo_output.json
__tests__/data/marketo_router_input.json
__tests__/data/marketo_router_output.json
__tests__/marketo.test.js
routerDestinations/marketo/transform.js
v0/destinations/marketo/config.js
v0/destinations/marketo/transform.js
v0/util/network.js
versionedRouter.js

added api end point for routerTransformer

---

__tests__/data/af_input.json
__tests__/data/af_output.json
v0/destinations/af/transform.js

fix for endpoint

---

v0/destinations/ga/transform.js

GA - Ecommerce logic update

---

__tests__/data/am_output.json
v0/destinations/am/transform.js

Added Campaign Support for all api calls

---

v0/destinations/ga/transform.js

added bug fix for event name and type in ga

---

__tests__/data/ga_input.json
v0/destinations/ga/transform.js

get clientid from displayName

---

v0/destinations/ga/transform.js

Fixed Ecommerce events in GA

---

__tests__/data/ga_output.json
v0/destinations/ga/transform.js

add support for product level properties in generic ecom events

---

__tests__/data/ga_input.json
__tests__/data/ga_output.json
v0/destinations/ga/transform.js
v0/util/index.js

GA changes

---

__tests__/warehouse.test.js
warehouse/index.js

WH: Do not force set userId to string datatype

---

util/ivmFactory.js
versionedRouter.js

Metadata fixes V1 Transform

---

v0/destinations/braze/config.js
v0/destinations/braze/transform.js

Added support for incremental update for Salesforce

---

__tests__/data/facebook_pixel_output.json
v0/destinations/facebook_pixel/transform.js

changed api version from v9.0 to v10.0

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/transform.js

use get lib

---

__tests__/appcenter_source.test.js
__tests__/data/appcenter_source_input.json
__tests__/data/appcenter_source_output.json
v0/sources/appcenter/mapping.json
v0/sources/appcenter/transform.js
v0/sources/message.js

Developed Appcenter as Source

---

v0/util/data/GenericFieldMapping.json

adding phone in generic mapping

---

__tests__/warehouse.test.js
warehouse/config/WHPageConfig.js
warehouse/config/WHScreenConfig.js
warehouse/index.js

WH: Fallback to screen name in properties if top level name is missing

---

__tests__/data/moengage_input.json
__tests__/data/moengage_output.json
v0/destinations/ga/transform.js
v0/destinations/sfmc/transform.js

added comments

---

__tests__/data/clevertap_input.json
__tests__/data/clevertap_output.json
v0/destinations/clevertap/transform.js
v0/util/data/GenericFieldMapping.json

added support for option to track anon user or not

---

__tests__/data/customerio_input.json
__tests__/data/customerio_output.json
v0/destinations/customerio/config.js
v0/destinations/customerio/transform.js

EU based account implementation
> Fix [#1]()

transformer updated to handle eu region and test cases added

---

v0/destinations/marketo/config.js
v0/destinations/marketo/transform.js
v0/util/cache.js
v0/util/constant.js
v0/util/network.js

Added stats to marketo

---

__tests__/data/moengage_output.json
v0/destinations/moengage/config.js

MoEngage Data API updates
> Fix [#1]()

api domains and unit test cases updated

---

__tests__/data/moengage_input.json
__tests__/data/moengage_output.json
v0/destinations/moengage/data/MOENGAGEIdentifyAttributesConfig.json

fix attributes issue
> Fix [#1]()

fix attributes issue

---

__tests__/data/af_input.json
__tests__/data/af_output.json
v0/destinations/af/transform.js

fixed appsflyer stringifying event value issue

---

__tests__/warehouse.test.js
warehouse/v1/util.js

WH: Do not remove leading underscores in properties

---

v0/sources/extole/mapping.json
v0/sources/extole/transform.js
v0/util/index.js

> Extole as Source
> Fix [#1]()

Extole as Source

---

__tests__/data/ga_output.json
v0/destinations/ga/transform.js

Ga get to post

---

__tests__/data/ga_input.json
__tests__/data/ga_output.json
v0/destinations/ga/transform.js

configurable parameter added to manage ga fallback for cid
> Fix [#1]()

configurable parameter added to manage ga fallback for cid

---

__tests__/data/ga_output.json

changed from get to post

---

__tests__/data/posthog_input.json
__tests__/data/posthog_output.json
v0/destinations/posthog/transform.js

Convert userId to string before sending

---

__tests__/warehouse.test.js
v0/destinations/bq/transform.js
v0/destinations/clickhouse/transform.js
v0/destinations/postgres/transform.js
v0/destinations/rs/transform.js
v0/destinations/snowflake/transform.js
warehouse/config/WHTrackEventTableConfig.js
warehouse/config/WHTracksTableConfig.js
warehouse/index.js

Handle recordId from cloud sources

---

__tests__/data/am_input.json
__tests__/data/am_output.json
__tests__/data/ga_output.json
v0/destinations/am/transform.js

Initial referrer and Initial referring domain added
> Fix [#1]()

Am track referrers update

---

__tests__/data/clevertap_input.json
__tests__/data/clevertap_output.json
v0/destinations/clevertap/data/CleverTapIdentify.json
v0/destinations/clevertap/transform.js
v0/destinations/kustomer/transform.js
v0/util/index.js

Clevertap enhancement

---

__tests__/data/customerio_input.json
__tests__/data/customerio_output.json
v0/destinations/customerio/transform.js

Fix Customer.io dot escaping

---

__tests__/data/iterable_input.json
__tests__/data/iterable_output.json
v0/destinations/iterable/transform.js

iterable fix

---

__tests__/data/webhook_input.json
__tests__/data/webhook_output.json
v0/destinations/webhook/transform.js

Webhook destination - don't set context object if the context object is not found and request_ip is also absent.

Rudder-Saas <-- Master

---

__tests__/warehouse.test.js
warehouse/index.js
warehouse/v0/util.js
warehouse/v1/util.js

postgres identifiers limitation

---

__tests__/data/ga_input.json
__tests__/ga.test.js
v0/destinations/ga/transform.js

added qt param

---

v0/destinations/ga/transform.js

Ga added router transformer support

---

v0/destinations/ga/transform.js

backward compatibility

---

v0/destinations/ga/transform.js

added support for router transformer for ga

---

destTransformer.js

Do not kill process on SIGTERM

---

v0/util/network.js

returning 400 for wrong credentials

---

__tests__/user_transformation.test.js
util/ivmFactory.js
versionedRouter.js

Support for transformEvent to return an array

---

__tests__/data/facebook_pixel_output.json
v0/destinations/facebook_pixel/config.js
v0/destinations/facebook_pixel/data/FBPIXELCommonConfig.json
v0/destinations/facebook_pixel/transform.js

added common data keys to fb pixel

---

__tests__/data/customerio_input.json
__tests__/data/customerio_output.json
package-lock.json
package.json
v0/destinations/customerio/transform.js

Customer.IO:  event name trimmed to 500 characters as well as 100 bytes 

---

warehouse/identity.js

toString() for all merge event prop values

---

warehouse/identity.js

Fix undefined merge prop value error

---

features.json
versionedRouter.js

Adding Features End Point

---

__tests__/data/webhook_input.json
__tests__/data/webhook_output.json
v0/util/index.js

Fix empty header key in webhook destination

---

v0/destinations/zendesk/transform.js

Zendesk: zendeskUserId check

---

v0/destinations/kochava/config.js

Updated the `Add to wishlist` event name to `Product Added to Wishlist` in Standard eventss Mapping

---

__tests__/data/iterable_input.json
__tests__/data/iterable_output.json
v0/destinations/iterable/data/IterablePageConfig.json
v0/destinations/iterable/data/IterableTrackConfig.json

take emails from properties

---

v0/destinations/sfmc/transform.js

added routerTransformer for SFMC

---

__tests__/data/marketo_input.json
v0/destinations/marketo/transform.js

Marketo new Feature

---

__tests__/data/facebook_pixel_input.json
__tests__/data/facebook_pixel_output.json
v0/destinations/facebook_pixel/transform.js

Added test destination settings for Facebook Pixel

---

__tests__/data/kustomer_output.json
__tests__/data/kustomer_router_input.json
__tests__/data/kustomer_router_output.json
__tests__/kustomer.test.js
features.json
v0/destinations/kustomer/config.js
v0/destinations/kustomer/transform.js
v0/destinations/kustomer/util.js

Kustomer V2

---

__tests__/data/mp_output.json
v0/destinations/mp/transform.js

Fix mixpanel basic auth token gen

---

warehouse/config/ReservedKeywords.json

Fix mixpanel basic auth token

---

__tests__/data/gainsight_router_input.json
__tests__/data/gainsight_router_output.json
__tests__/gainsight.test.js
v0/destinations/gainsight/transform.js

add routerTransform test, add missed message type check

---

__mocks__/axios.js
__mocks__/data/mailchimp/response.json
__mocks__/mailchimp.mock.js
__tests__/data/mailchimp_input.json
__tests__/data/mailchimp_output.json
__tests__/mailchimp.test.js
v0/destinations/mailchimp/transform.js

Mailchimp : error handling for error code 403

---

__tests__/data/marketo_output.json
__tests__/data/marketo_router_output.json
__tests__/data/sanity/marketo_router_output.json
v0/destinations/marketo/transform.js

Marketo api hotfix track

---

v0/destinations/kustomer/transform.js
v0/destinations/kustomer/util.js
v0/util/index.js

Kustomer advanced transform

---

v0/destinations/facebook_pixel/data/FBPIXELUserDataConfig.json
v0/destinations/posthog/data/PHPropertiesConfig.json

change ip precedence

---

v0/destinations/ga/transform.js

"Illegal argument undefined" bug fixed.

---

__tests__/data/variance_input.json
__tests__/data/variance_output.json
__tests__/variance.test.js
v0/destinations/variance/transform.js

Add [Variance](https://www.variance.com) as a destination.
- https://github.com/rudderlabs/rudderstack-docs/pull/109
- https://github.com/rudderlabs/rudder-transformer/pull/660
- https://github.com/rudderlabs/config-generator/pull/15

feat: add Variance as a destination

---

__tests__/data/facebook_pixel_output.json
__tests__/data/facebook_pixel_router_output.json
v0/destinations/facebook_pixel/transform.js

updated test cases for fbpixel

---

__mocks__/axios.js
__mocks__/gainsight_px.mock.js
__tests__/data/gainsight_px_input.json
__tests__/data/gainsight_px_output.json
v0/destinations/gainsight_px/util.js

improve gainsight px test coverage

---

v0/destinations/lytics/config.js
v0/destinations/lytics/transform.js

added support for name

---

__mocks__/axios.js
__mocks__/hs.mock.js
__tests__/data/hs_input.json
__tests__/data/hs_output.json
__tests__/data/hs_router_input.json
__tests__/data/hs_router_output.json
v0/destinations/hs/transform.js

Hubspot Error Fixes

---

__tests__/data/iterable_input.json
__tests__/data/iterable_output.json
v0/destinations/iterable/transform.js

bugfix for joybird issue on product array

---

__tests__/warehouse.test.js
warehouse/index.js

restrict event destructing to 3 levels

---

versionedRouter.js

revert buildspec

---

buildspec.saas.yml

Revert "revert buildspec"

---

buildspec.saas.yml

Reverts rudderlabs/rudder-transformer#696

Revert "Revert "revert buildspec""

---

buildspec.saas.yml

changed package manager

---

buildspec.master.yml

test-pr-with-master-version

---

buildspec.master.yml

Reverts rudderlabs/rudder-transformer#700

Revert "test-pr-with-master-version"

---

__tests__/data/kafka_batch_input.json
__tests__/data/kafka_batch_output.json
__tests__/kafka.test.js
v0/destinations/kafka/transform.js

Kafka batching

---

constants/destinationCanonicalNames.js
constants/index.js
v0/destinations/facebook_pixel/transform.js
v0/util/index.js
versionedRouter.js

Facebook Pixel hashing support

---

__tests__/data/branch_input.json
__tests__/data/branch_output.json
v0/destinations/branch/data/eventMapping.js
v0/destinations/branch/transform.js

add IDFA, IDFV, and ATT parameters
> Fix [#1]()

Branch - revamp

---

v0/destinations/kustomer/transform.js
v0/destinations/kustomer/util.js
v0/util/index.js

Kustomer adding email as tracking identity, adv transform imporvements

---

__tests__/warehouse.test.js
package-lock.json
package.json
warehouse/index.js

WH: Add missing messageId for events

---

__tests__/warehouse.test.js
package-lock.json
package.json
warehouse/index.js

WH: Add missing messageId for events (#713)

---

versionedRouter.js

Remove debug log in versioned-router

---

__tests__/warehouse.test.js
v0/destinations/azure_synapse/transform.js
v0/destinations/bq/transform.js
v0/destinations/clickhouse/transform.js
v0/destinations/mssql/transform.js
v0/destinations/postgres/transform.js
v0/destinations/rs/transform.js
v0/destinations/snowflake/transform.js
warehouse/index.js

WH: Add missing receivedAt

---

v0/destinations/intercom/transform.js

fix to return non null string for name

---

v0/destinations/s3_datalake/transform.js

s3 datalake

---

v0/destinations/marketo_bulk_upload/fetchJobStatus.js
v0/destinations/marketo_bulk_upload/fileUpload.js

changed for stats

---

v0/destinations/marketo_bulk_upload/fileUpload.js

added more stats marketo bulk upload

---

v0/destinations/marketo_bulk_upload/fetchJobStatus.js
v0/destinations/marketo_bulk_upload/fileUpload.js

marketo bulk added stats

---

v0/destinations/marketo_bulk_upload/fileUpload.js

removed replace

---

v0/destinations/marketo_bulk_upload/fileUpload.js

marketo bulk

---

v0/destinations/marketo_bulk_upload/fileUpload.js
v0/destinations/marketo_bulk_upload/util.js

Constant Fix

---

v0/destinations/rs/transform.js

Redshift: Fix setting text datatype for JSON arrays

---

__tests__/data/personalize_input.json
__tests__/data/personalize_output.json
v0/destinations/personalize/transform.js

Personalize : putUsers and putItems

---

__tests__/data/facebook_pixel_input.json
__tests__/data/facebook_pixel_output.json
v0/destinations/facebook_pixel/config.js
v0/destinations/facebook_pixel/transform.js

fixed bug for other standard events fb pixel

---

__tests__/data/clevertap_input.json
__tests__/data/clevertap_output.json
v0/destinations/clevertap/transform.js

Clevertap device token

---

__mocks__/axios.js
__tests__/data/drip_output.json

Drip (updated mock)

---

__tests__/data/personalize_output.json
v0/destinations/personalize/transform.js

Personalize compatibility issue

---

__tests__/data/clevertap_input.json
__tests__/data/clevertap_output.json
v0/destinations/clevertap/data/CleverTapPage.json
v0/destinations/clevertap/data/CleverTapScreen.json
v0/destinations/clevertap/data/CleverTapTrack.json
v0/destinations/clevertap/transform.js

Clevertap reformatting of code for new feature

---

util/customTransforrmationsStore-v1.js
v0/util/index.js
versionedRouter.js

cleanup stat tags

---

util/customTransforrmationsStore-v1.js
v0/util/index.js
versionedRouter.js

cleanup stat tags (#786)

---

__tests__/data/customerio_input.json
__tests__/data/customerio_output.json
__tests__/data/customerio_router_output.json
v0/destinations/customerio/transform.js

Fix merging issues for customer io. Anon ids were not sent. Added sending of anonymousId.
API:
https://customer.io/docs/api/#operation/identify
https://customer.io/docs/api/#operation/trackAnonymous
Issue raised in open source slack channel:
https://rudderstack.slack.com/archives/C01E4PLB135/p1632308702475400
> Fix [#1]()

Fix for customer io

---

util/eventValidation.js
util/trackingPlan.js

Recent changes as per in the spreadsheet.

---

util/eventValidation.js
util/trackingPlan.js

Tracking plan

---

warehouse/index.js

Adding source and destination info to context.

---

__tests__/data/hs_router_input.json
__tests__/data/hs_router_output.json
v0/destinations/hs/transform.js

resolved conflict and updated test cases
> Fix [#1]()

Master to saas

---

__tests__/data/hs_router_input.json
__tests__/data/hs_router_output.json
v0/destinations/hs/transform.js

fix bug in hubspot transformer, update test cases

---

versionedRouter.js

Add apiversion header to batch endpoint

---

versionedRouter.js

Add apiversion header to batch rudder

---

versionedRouter.js

Add apiversion header to batch rudder saas

---

v0/destinations/customerio/config.js
v0/destinations/customerio/transform.js

Added Alias feature for customer.io
setting primary id as userId and secondary id as the previous id
> Fix [#1]()

Customer.io:feature : alias support added

---

versionedRouter.js

Hotfix: adding transformer version to response transform route

---

v0/destinations/hs/transform.js

> Optimize the call for "properties" endpoint to avoid reaching its rate-limit.
> Fix [#1]()

HS - feat: optimize "properties" endpoint

---

__tests__/data/zendesk_input.json
__tests__/data/zendesk_output.json
v0/destinations/zendesk/transform.js

Included check for payload.user and throwing error if userEmail is not found.
> Notion -> https://www.notion.so/rudderstacks/Zendesk-Aellocred-6b12bb67dafd484e8b4188feaa6685f5
> Fix [#1]()

Bug: Included check for payload.user and userEmail for Zendesk

---

__tests__/data/zendesk_input.json
__tests__/data/zendesk_output.json
v0/destinations/zendesk/transform.js

Reverts rudderlabs/rudder-transformer#858

Revert "Bug: Included check for payload.user and userEmail for Zendesk"

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/transform.js

Added check for traits before calling handleTraits function and also added a test case to demonstrate this issue.
> Fix [#1]()

Bug Fix: added check for traits for Amplitude

---

__tests__/azure_synapse.test.js
__tests__/bq.test.js
__tests__/clickhouse.test.js
__tests__/mssql.test.js
__tests__/postgres.test.js
__tests__/rs.test.js
__tests__/s3_datalake.test.js
__tests__/snowflake.test.js
v0/destinations/azure_synapse/transform.js
v0/destinations/bq/transform.js
v0/destinations/clickhouse/transform.js
v0/destinations/mssql/transform.js
v0/destinations/postgres/transform.js
v0/destinations/rs/transform.js
v0/destinations/s3_datalake/transform.js
v0/destinations/snowflake/transform.js
warehouse/index.js

> Added json support for validation errors so that it will be easy to query using json format.
> Fix [#1]()

Added json support for validation errors.

---

__tests__/data/am_input.json
__tests__/data/am_output.json
__tests__/data/am_router_output.json
v0/destinations/am/data/AmplitudeDefaultConfig.json
v0/destinations/am/transform.js

> add addl. Properties Support (productID, country, city, Latitude, Longitute, region, dma)
> Fix [#1]()

AM - fix: add additional properties support

---

buildspec.saas.yml

Commented out devops PR creation for saas builds temporarily

---

buildspec.saas.yml

master --> rudder-saas

---

buildspec.saas.yml

Uncomment saas buildspec as part of Node version downgrade

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/transform.js

[Click here](https://rudderlabs.slack.com/archives/C02A3UAU9UN/p1638508147258000)

Ampplitude: addressing CFD for revenue field , when the value is 0

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/config.js
v0/destinations/am/data/AmplitudeCommonConfig.json
v0/destinations/am/data/AmplitudeDefaultConfig.json
v0/destinations/am/transform.js

> add location properties in common config
> Fix [#1]()

Amplitude: add location in common config

---

buildspec.saas.yml

Fixed automate PR raise for rudder-devops repository for upgrading transformer image
> Fix [#1]()

Fix: PR raise for Devps Repository

---

__tests__/user_transformation.test.js
util/customTransformer.js
util/ivmFactory.js

* fetchV2 api support
* wrapper
* test cases
* env change
* unused line
https://www.notion.so/rudderstacks/Transformations-node-fetch-give-as-npm-package-rudder-fetch-a6651223fc3d4111afbec083aef598c0
> Fix [#1]()

fetchV2 api support (#916)

---

__tests__/data/branch_input.json
__tests__/data/branch_output.json
__tests__/data/branch_router_input.json
__tests__/data/branch_router_output.json
v0/destinations/branch/transform.js

`getUserData` will work even if there is no traits or properties block, if os information is missing error will be thrown.
[Notion Link here](https://www.notion.so/rudderstacks/BRANCH-Destination-OS-name-check-missing-8370abe39e29448a88304b8644a756fb
)
> Fix [#1]()

Branch CFD: OS name missing 

---

__tests__/data/branch_input.json
__tests__/data/branch_output.json
__tests__/data/branch_router_input.json
__tests__/data/branch_router_output.json
v0/destinations/branch/transform.js

* getUserData will work even if there is no traits or properties, also if os information is missing error will be thrown
* adding additional check for os.name and throwing error, editing test cases accordingly
* error messaging changed
> Fix [#1]()

Branch CFD: OS name missing  master --> saas

---

__tests__/data/fb_custom_audience_output.json
__tests__/data/fb_custom_audience_router_output.json
v0/destinations/fb_custom_audience/config.js

The API version changed from 11.0 to 12.0. The whole document remains to be same. So changed the API version in the existing endpoint.
[Notion link](https://www.notion.so/rudderstacks/Facebook-Custom-Audience-Revisit-a032c834351746c6a1ab5cefc30e4cec)
[Slack link](https://rudderlabs.slack.com/archives/C02A3UAU9UN/p1641409531474200?thread_ts=1641324843.461400&cid=C02A3UAU9UN)
> Fix [#1]()

Facebook Custom Audience: changed the API version to v12.0 and edited test cases accordingly

---

__tests__/data/kochava_output.json
v0/destinations/kochava/transform.js

> correct idfv keyword name
> Fix [#1]()

Kochava - correct idfv keyword name

---

adapters/network.js

https://rudderlabs.slack.com/archives/C02G82J94RJ/p1641826266005800?thread_ts=1641823167.001600&cid=C02G82J94RJ
An issue we were facing for Marketo destinations
> Fix [#1]()

Missing return statements added to all http wrapper methods

---

v0/destinations/marketo_bulk_upload/poll.js

marketo-bulk-upload-bugfix: bugfix for poll.js

---

v0/destinations/marketo_bulk_upload/poll.js

marketo-bulk-upload-bugfix: bugfix for poll.js (#948)

---

v0/destinations/marketo_bulk_upload/fetchJobStatus.js

marketo-bulk-upload-bugfix: bugfix for fetchJobStatus.js

---

v0/destinations/marketo_bulk_upload/fetchJobStatus.js

marketo-bulk-upload-bugfix: bugfix for fetchJobStatus.js (#950)

---

__tests__/appsFlyer.test.js
__tests__/data/af_input.json
__tests__/data/af_output.json
__tests__/data/af_router_input.json
__tests__/data/af_router_output.json
v0/destinations/af/transform.js

AF bugFix : removed default value 'all' from sharingFilter

---

destTransformer.js

> correct cluster-enabled logic in destTransform
> Fix [#1]()

destTransform - correct cluster-enabled logic

---

__tests__/data/webhook_input.json
__tests__/data/webhook_output.json
v0/destinations/webhook/transform.js

> Add support for the PUT request method to the webhook destination
> Fix [#1]()

Add support for PUT to webhook destination

---

__tests__/data/iterable_input.json
__tests__/data/iterable_output.json
v0/destinations/iterable/config.js
v0/destinations/iterable/data/IterableAliasConfig.json
v0/destinations/iterable/transform.js

Adding support for Alias call 
> Fix [#1]()

Enhancement Iterable : Adding support for alias call

---

v0/destinations/sfmc/transform.js

> Added support for errors thrown by node HTTP agent. We have utilised `nodeSysErrorToStatus` to provide a more clear error message in case of error response being empty.
> Fix [#1]()

SFMC : Added error handling for empty error.response

---

__tests__/data/mp_input.json
v0/destinations/mp/transform.js

Changing useOldMapping to useNewMapping for Mixpanel

---

__tests__/data/am_input.json
__tests__/data/am_output.json
__tests__/data/am_router_output.json
v0/destinations/am/data/AmplitudeDefaultConfig.json
v0/destinations/am/data/AmplitudeGroupConfig.json
v0/destinations/am/data/AmplitudeIdentifyConfig.json
v0/destinations/am/data/AmplitudePageConfig.json
v0/destinations/am/data/AmplitudeProductActionsConfig.json
v0/destinations/am/data/AmplitudePromotionClickedConfig.json
v0/destinations/am/data/AmplitudePromotionViewedConfig.json
v0/destinations/am/data/AmplitudeRevenueConfig.json
v0/destinations/am/data/AmplitudeScreenConfig.json
v0/destinations/am/transform.js
v0/destinations/am/utils.js

Adding device_brand in mapping jsons.
> Fix [#1]()

Amplitude : Adding device_brand in mapping

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/data/AmplitudeScreenConfig.json

Amplitude BugFix: Screen configs updated to fetch device_brand value via getBrand Fucntion

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/transform.js

This Pr contains following change-
adding check in mobile channel type for mapDeviceBrand before adding device_brand
> Fix [#1]()

Master -> rudder-saas

---

__tests__/data/facebook_pixel_input.json
__tests__/data/facebook_pixel_output.json
v0/destinations/facebook_pixel/transform.js

> add event validation check
> Fix [#1]()

Facebook Pixel: add event validation check

---

v0/sources/webhook/transform.js

Change: events to event

---

v0/destinations/marketo_bulk_upload/fileUpload.js

Marketo-bulk-upload-fix

---

__tests__/data/candu_input.json
__tests__/data/candu_output.json
v0/destinations/candu/transform.js

Candu expects the userId as a string only. We are unable to check that because userId with numeric value is getting deleted by removeUndefinedAndNullAndEmptyValues. So removed that function and used removeUndefinedAndNullValues.
> Fix [#1]()

CANDU numeric userId issue.

---

__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/transform.js

Added amplitude as a vdm destination
https://www.notion.so/rudderstacks/cfe8e8ef60a34485a373e789b7b6933a?v=a07a0b1350f84d46af9792260b39a194&p=067f800d40854428b7a7c93c92109131
> Fix [#1]()

VDM-Amplitude: added visual mapper for am

---

__tests__/data/active_campaign_output.json
v0/destinations/active_campaign/transform.js
v0/destinations/active_campaign/util.js

> fix invalid json issue for `visit` key and add case for empty err.response
> Fix [#1]()

Active Campaign - fix invalid json issue and add case for empty err.response

---

__tests__/data/active_campaign_output.json
__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/active_campaign/transform.js
v0/destinations/active_campaign/util.js
v0/destinations/am/transform.js
v0/destinations/mp/transform.js

> rudder-saas <- master
> Fix [#1]()

rudder-saas <- master

---

buildspec.saas.yml

Omit yum from node 14 pipeline

---

buildspec.saas.yml

https://www.notion.so/rudderstacks/Fix-CB-pipeline-for-rudder-transformer-7e4bbcf3ad12414a89615cec382853ad
> Fix [#1]()

fix hub installation for codebuild

---

__tests__/data/ga_output.json
__tests__/data/ga_router_output.json
v0/destinations/ga/transform.js

> fix url encoded bug
> Fix [#1]()

GA: url encoded bug

---

__tests__/data/fb_custom_audience_input.json
__tests__/data/fb_custom_audience_output.json
v0/destinations/fb_custom_audience/transform.js

Fb audience fix handling for null props

---

buildspec.saas.yml

https://www.notion.so/rudderstacks/Fix-CB-pipeline-for-rudder-transformer-7e4bbcf3ad12414a89615cec382853ad
> Fix [#1]()

hub installation fix

---

v0/destinations/active_campaign/transform.js

> Fix custom error to check when event is being created.
> Fix [#1]()

AC: fix customError

---

__tests__/data/google_adwords_remarketing_lists_input.json
__tests__/data/google_adwords_remarketing_lists_output.json
__tests__/data/google_adwords_remarketing_lists_proxy_input.json
__tests__/data/google_adwords_remarketing_lists_proxy_output.json
__tests__/data/google_adwords_remarketing_lists_router_input.json
__tests__/data/google_adwords_remarketing_lists_router_output.json
v0/destinations/google_adwords_remarketing_lists/transform.js
v0/destinations/google_adwords_remarketing_lists/util.js

> add deletion support for Google Ads Audience
> Fix [#1]()

Google Ads Audience - add deletion support

---

__tests__/data/facebook_pixel_input.json
__tests__/data/facebook_pixel_output.json
__tests__/data/google_adwords_remarketing_lists_input.json
__tests__/data/google_adwords_remarketing_lists_output.json
__tests__/data/google_adwords_remarketing_lists_proxy_input.json
__tests__/data/google_adwords_remarketing_lists_proxy_output.json
__tests__/data/google_adwords_remarketing_lists_router_input.json
__tests__/data/google_adwords_remarketing_lists_router_output.json
__tests__/data/user_transformation_code_test_output.json
__tests__/user_transformation.test.js
util/customTransformer-v1.js
util/customTransformer.js
util/ivmFactory.js
v0/destinations/facebook_pixel/transform.js
v0/destinations/google_adwords_remarketing_lists/transform.js
v0/destinations/google_adwords_remarketing_lists/util.js
versionedRouter.js

saas <<-- master

---

util/customTransformer.js

propagating error from transformer test to config-backend

---

util/customTransformer.js

propagating error from transformer test to config-backend (#1039)

---

__tests__/data/active_campaign_output.json
v0/destinations/active_campaign/transform.js

Ac event discripancy

---

__tests__/data/mailchimp_input.json
__tests__/data/mailchimp_output.json
v0/destinations/mailchimp/config.js
v0/destinations/mailchimp/transform.js

> Added check for the possible status value and added one test case for that
> Fix [#1]()

Mailchimpsync issuess

---

__tests__/data/posthog_input.json
__tests__/data/posthog_output.json
v0/destinations/posthog/config.js
v0/destinations/posthog/data/PHGroupConfigOld.json
v0/destinations/posthog/transform.js

Update the group call in posthog. 
> Fix [#1]()

update group call in posthog

---

v0/destinations/heap/transform.js

hotfix for heap properties

---

__tests__/data/heap_input.json
__tests__/data/heap_output.json
__tests__/data/heap_router_input.json
__tests__/data/heap_router_output.json
__tests__/data/versioned_processor_heap_output.json
__tests__/data/versioned_router_heap_output.json
v0/destinations/heap/data/HEAPIdentifyConfig.json
v0/destinations/heap/data/HEAPTrackConfig.json
v0/destinations/heap/transform.js

> add `timestamp` and `idempotency_key` params
> Fix [#1]()

Heap: add additional params

---

v0/destinations/salesforce/transform.js

> Add toggle support for contactId
> Fix [#1]()

SF:Add toggle support for contactId

---

__tests__/data/zendesk_output.json
v0/destinations/zendesk/data/ZDIdentifyConfig.json
v0/destinations/zendesk/transform.js

> For Identify call, a key name is required.
> Fix [#1]()

Zendesk : name require, identify

---

__mocks__/data/mailchimp/response.json
__mocks__/mailchimp.mock.js
__tests__/data/mailchimp_input.json
__tests__/data/mailchimp_output.json
v0/destinations/mailchimp/transform.js

> email is required for adding a new member to the list and updating a list member
> Fix [#1]()

Mailchimp: add email validation

---

__tests__/data/google_adwords_enhanced_conversions_input.json
__tests__/data/google_adwords_enhanced_conversions_output.json
__tests__/data/google_adwords_remarketing_lists_input.json
__tests__/data/google_adwords_remarketing_lists_output.json
v0/destinations/google_adwords_enhanced_conversions/transform.js
v0/destinations/google_adwords_remarketing_lists/transform.js
v0/util/index.js

Adding support for removing - from login-customer-id in GARL and GAEC.

---

__tests__/data/facebook_pixel_output.json
__tests__/data/facebook_pixel_router_output.json
v0/destinations/facebook_pixel/data/FBPIXELCommonConfig.json

> Updating event_id sourceKeys
> Fix [#1]()

Facebook Pixel event_id discrepancy

---

__tests__/data/am_batch_input.json
__tests__/data/am_batch_output.json
__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/config.js
v0/destinations/am/transform.js

> Providing the functionality in the way that existing customers can use the existing endpoint in the transformer.
> And provide an option in the dashboard which can be used for choosing between the endpoints.
> Option to opt for "EU Residency Server".
> By default the option should be set to the existing endpoint.
> Fix [#1]()

am-eu-support

---

__tests__/data/am_batch_input.json
__tests__/data/am_batch_output.json
__tests__/data/am_input.json
__tests__/data/am_output.json
v0/destinations/am/config.js
v0/destinations/am/transform.js

Master <- Saas (#1100)

---

CODEOWNERS

> Adding @utsabc to the list of Code Owners for this repository

Adding Utsab to Code Owner List

---

versionedRouter.js

Previously, only old destinations were being onboarded to CDK. While onboarding new destinations the file path was not matching with new cdk format.
> Fix [#1]()

Transformer CDK: solving cdk new destination onboarding problem

---

__tests__/data/airship_input.json
__tests__/data/airship_output.json
__tests__/data/airship_router_input.json
__tests__/data/airship_router_output.json
v0/destinations/airship/transform.js

> Using API key for authorization
> Fix [#1]()

Airship: Use API key authorization

---

__tests__/data/braze_input.json
__tests__/data/braze_output.json
v0/destinations/braze/transform.js

Inside braze transform.js we are traversing through each products in `properties.products` array. If any all the products in the array contains price as `0` then we are discarding that event with the following error `Invalid Order Completed event`.
> Fix [#1]()

bugfix(braze): Adding support for products with price 0.

---

v0/destinations/active_campaign/util.js

This changes is to update the activecampaign errorHandler to check more error data.
> Fix [#1]()

bugfix[active campaign]: Updating the error handler for showing more error data.

---

v0/destinations/active_campaign/util.js

Adding JSON stringifyer for error response data.
> Fix [#1]()

[Bugfix/activeCampaign]::Adding JSON stringifyer for error response data.

---

__tests__/data/iterable_source_input.json
__tests__/data/iterable_source_output.json
__tests__/iterable_source.test.js
v0/sources/iterable/mapping.json
v0/sources/iterable/transform.js

> Creating `iterable` source
> Fix [#1]()

feature(new integration): Iterable source onboarding

---

v0/destinations/active_campaign/transform.js

* bugfix(active_campaign): adding active campaign support for rt transform
> Fix [#1]()

Bugfix/active campaign router (#1139)

---

__tests__/cdk_postMapper/new_relic.test.js
__tests__/data/new_relic_input.json
__tests__/data/new_relic_output.json
__tests__/new_relic.test.js
__tests__/utilities/test-utils.js
cdk/new_relic/config.yaml
cdk/new_relic/mapping/track.yaml
cdk/new_relic/transform.js
constants/destinationCanonicalNames.js

> Onboarding New Relic destination
> Fix [#1]()

feature(new integration): New Relic Onboarding

---

util/customTransforrmationsStore-v1.js
util/customTransforrmationsStore.js
util/fetch.js

Additional logs for fetching transformer func with proxy

---

__mocks__/data/salesforce/proxy_response.json
__mocks__/network.js
__tests__/data/proxy_input.json
__tests__/data/proxy_output.json
versionedRouter.js

* Hotfix for fixing 204 status-code sent from genericNetworkHandler with test-cases
* Moved the change for genericNetworkHandlers to all
* Adding import of isHttpStatusSuccess
* Change test-case output for 204
Co-authored-by: Sai Sankeerth <sanpj2292@github.com>
> Fix [#1]()

Master -> Saas (Contains hotfix for nw layer)

---

v0/destinations/ga4/data/GA4CommonConfig.json

> Modify `userId`'s `commonConfig`
> Fix [#1]()

feature(enhancement): GA4 update userId's commonConfig

---

__tests__/data/personalize_output.json
v0/destinations/personalize/transform.js

Stringifying value in properties. 
> Fix [#1]()

fix[personalize]: Stringifying value in properties

---

__tests__/data/mp_output.json
v0/destinations/mp/transform.js

>  update error message where for group call, Group Key Settings must be configured in the UI
> Fix [#1]()

bugfix(integration):Mixpanel update error message for group api

---

__tests__/data/zendesk_input.json
__tests__/data/zendesk_output.json
v0/destinations/zendesk/transform.js

>deleted the unnecessary userId check for sendGroupCallsWithoutUserId true
> Fix [#1]()

bugfix(Integration): For Zendesk, deleted the unnecessary userId check for sendGroupCallsWithoutUserId true

---

__tests__/data/webhook_input.json
__tests__/data/webhook_output.json
constants/destinationCanonicalNames.js
v0/destinations/webhook/transform.js

> Supporting delete method for webhook destination
> Fix [#1]()

feature(integrations): Webhook supporting delete method for webhook

---

__tests__/data/attribution_input.json
__tests__/data/attribution_output.json
v0/destinations/attribution/transform.js

Pass message context to Attribution destination.

Pass message context to Attribution destination

---

CODEOWNERS

Updated codeowners for WH module

---

__tests__/data/attribution_output.json
v0/destinations/attribution/transform.js

Pass full payload to Attribution.

Pass full payload to Attribution

---

__tests__/__integration_util_test__/data/getValueFromPropertiesOrTraits.json
__tests__/__integration_util_test__/data/handleSourceKeysOperation.json
__tests__/__integration_util_test__/v0_index.test.js
v0/util/index.js

Added utility functions and tests for util/index.js

---

__mocks__/data/mailchimp/response.json
__mocks__/mailchimp.mock.js
__tests__/data/mailchimp_batch_input.json
__tests__/data/mailchimp_batch_output.json
__tests__/data/mailchimp_output.json
__tests__/data/mailchimp_router_input.json
__tests__/data/mailchimp_router_output.json
v0/destinations/mailchimp/config.js
v0/destinations/mailchimp/transform.js
v0/destinations/mailchimp/utils.js

Merging the transformation flow of mailchimp for RETL and streaming sources also added some cleanups
> Fix [#1]()

fix(mailchimp): merging flows for RETL and Streaming

---

buildspec.saas.yml

https://www.notion.so/rudderstacks/Infra-on-Call-tasks-d195e15f1d0749e495e2e586b0ca5875
> Fix [#1]()

add 1b pool for automatic pr

---

__tests__/data/ga4.json
v0/destinations/ga4/data/GA4PageConfig.json

> align `page_view` custom event mappings for auto-collected events with gtag.js
> Fix [#1]()

feature(integration): GA4 - add page mapping for auto collected events

---

__tests__/data/customerio_input.json
__tests__/data/customerio_output.json
v0/destinations/customerio/transform.js

> Fix changes introduced in PR #1191 .
> Fix [#1]()

bugfix(integration): CustomerIO - Revert changes from PR #1191

---

package-lock.json
package.json

Reuse test commands declared in combined tests.
This change only minor refactor to test scripts and no behaviour change.
> Fix [#1](Reuse individual test scripts in combined test)

Refactor test scripts in npm

---

__tests__/data/adj_input.json
__tests__/data/adj_output.json
v0/destinations/adj/transform.js

> Adding support for partner parameters
> Fix [#1]()

feature(new feature): Adjust- adding partner parameters

---

.deepsource.toml

Adding deepsource integration

---

__tests__/data/klaviyo.json
v0/destinations/klaviyo/util.js

> modify error message and refactor code
> Fix [#1]()

hotfix(integration): klaviyo - modify error message and refactor code

---

features.json
v0/destinations/klaviyo/util.js

We are doing router transformation in klaviyo, so we need to add klaviyo in feature.json.
> Fix [#1]()

bugfix[klaviyo]: Adding klaviyo to feature.json

---

__tests__/data/ga_input.json
__tests__/data/ga_output.json
v0/destinations/ga/transform.js

> GA Reverting validation for size
> Fix [#1]()

bugfix(integration): GA Reverting validation for size

---

__tests__/data/ga_input.json
__tests__/data/ga_output.json
v0/destinations/ga/transform.js

> GA Reverting validation for size
> Fix [#1]()

master -> SaaS

---

.github/workflows/build-master.yaml
.github/workflows/build-pr.yaml

Migrate from AWS CodeBuild to GitHub Actions

feature: migrate to GitHub Actions

---

__mocks__/axios.js
__mocks__/data/salesforce/response.json
v0/destinations/salesforce/transform.js

Added response handling for Salesforce network requests. Correct parsing of retryable, abortable network response and returning same back to server
> Fix [#1]()

bugfix(integrations): Salesforce added network response handling 

---

__tests__/data/snapchat_conversion_router_input.json
__tests__/data/snapchat_conversion_router_output.json
v0/destinations/snapchat_conversion/transform.js

In some of the `customError` calls, we are not providing `statusCode`. So added `statusCode` in all the `customError` function calls.
> Fix [#1]()

bugfix(snapchat_conversion): Adding status code in customError.

---

__tests__/data/fb_custom_audience.json

Description of Test Cases updated and Coverage improved
> Fix [#1]()

Description for Test Cases of Fb Audience Updated and Coverage Improved

---

__tests__/data/hs_input.json
__tests__/data/hs_output.json
__tests__/data/hs_router_input.json
__tests__/data/hs_router_output.json
v0/destinations/hs/HSTransform-v2.js
v0/destinations/hs/util.js

> modify batch logic for duplicate concatenation and add test cases
> Fix [#1]()

feature(HS): modify batch logic and add test cases

---

__tests__/data/canny.json
v0/destinations/canny/data/identifyConfig.json
v0/destinations/canny/transform.js
v0/destinations/canny/util.js
v0/destinations/one_signal/transform.js
v0/util/data/GenericFieldMapping.json

Refactoring code.
> Fix [#1]()

feature[canny&onesignal]:: Refactoring code.

---

Dockerfile-no-func
README.md
package.json

> update dockerfile-no-func
> update readme
> delete unused package
> Fix [#1]()

update dockerfile-no-func, readme

---

CODEOWNERS

Updated codeowners for tests, mocks and feature.json

---

v0/destinations/custify/config.js
v0/destinations/custify/data/CUSTIFYGroupConfig.json
v0/destinations/custify/data/CUSTIFYIdentifyConfig.json
v0/destinations/custify/data/CUSTIFYTrackConfig.json
v0/destinations/custify/deleteUsers.js
v0/destinations/custify/transform.js
v0/destinations/hs/transform.js

> add error handling
> Fix [#1]()

feature(integration): hs - add error handling

---

Dockerfile
Dockerfile-no-func

Bumped the version of Node to fix docker vulnerabilities.
Before:
```
Testing transformer:with-vulnerabilities...
✗ Medium severity vulnerability found in openssl/libcrypto1.1
Description: Inadequate Encryption Strength
Info: https://snyk.io/vuln/SNYK-ALPINE315-OPENSSL-2941810
Introduced through: openssl/libcrypto1.1@1.1.1n-r0, openssl/libssl1.1@1.1.1n-r0, apk-tools/apk-tools@2.12.7-r3, libretls/libretls@3.3.4-r3, python2/python2@2.7.18-r4
From: openssl/libcrypto1.1@1.1.1n-r0
From: openssl/libssl1.1@1.1.1n-r0 > openssl/libcrypto1.1@1.1.1n-r0
From: apk-tools/apk-tools@2.12.7-r3 > openssl/libcrypto1.1@1.1.1n-r0
and 6 more...
Fixed in: 1.1.1q-r0
✗ High severity vulnerability found in ncurses/ncurses-terminfo-base
Description: Out-of-bounds Read
Info: …
```

fix: docker vulnerabilities

---

package-lock.json

Bumped the versions of Node dependencies to fix vulnerabilities.
Before:
```
Testing transformer:with-vulnerabilities...
✗ Medium severity vulnerability found in openssl/libcrypto1.1
Description: Inadequate Encryption Strength
Info: https://snyk.io/vuln/SNYK-ALPINE315-OPENSSL-2941810
Introduced through: openssl/libcrypto1.1@1.1.1n-r0, openssl/libssl1.1@1.1.1n-r0, apk-tools/apk-tools@2.12.7-r3, libretls/libretls@3.3.4-r3, python2/python2@2.7.18-r4
From: openssl/libcrypto1.1@1.1.1n-r0
From: openssl/libssl1.1@1.1.1n-r0 > openssl/libcrypto1.1@1.1.1n-r0
From: apk-tools/apk-tools@2.12.7-r3 > openssl/libcrypto1.1@1.1.1n-r0
and 6 more...
Fixed in: 1.1.1q-r0
✗ High severity vulnerability found in ncurses/ncurses-terminfo-base
Description: Out-of-bounds Read
Info: …
```

fix: vulnerabilities in node dependencies

---

Dockerfile
buildspec.dev.yml
buildspec.master.yml
buildspec.saas.yml
buildspec.saasdev.yml
buildspec.yml
versionedRouter.js

> add commit id and version in health endpoint
> Fix [#1]()

feat: add commit id and version in health endpoint

---

util/eventValidation.js
versionedRouter.js

> adding message type optional check in tp source config
> Fix [#1]()

fix(trackingplan): adding message type optional check in tp source config

---

cdk/v2/handler.js
cdk/v2/utils.js
versionedRouter.js

Addressed a couple of bugs:
- Send flow type for creating workflow engine instance
- I/O processing is made async
N/A

fix: address async and flow type issues in cdk 2.0 handler

---

__tests__/data/fb_custom_audience.json
__tests__/data/fb_custom_audience_router.json
v0/destinations/fb_custom_audience/config.js

feat(integration): fb custom audience - upgrade v14 to v15

---

__tests__/data/engage.json
__tests__/data/engage_router_input.json
__tests__/data/engage_router_output.json
v0/destinations/engage/utils.js

> Changed the Config Property Name from lists to listIds as received from CP
> Fix [#1]()

 fix(integration): Engage

---

util/fetch.js

> await to capture fetchError thrown by fetch call
> Fix [#1]()

chore(node-fetch): capture fetchError thrown by fetch call

---

__tests__/data/klaviyo.json
__tests__/data/klaviyo_router_output.json
v0/destinations/klaviyo/transform.js

>Adding custom traits support in profile updation request
> Fix [#1]()

feat/(klaviyo): adding custom traits support in profile updation request

---

util/fetch.js
util/trackingPlan.js

> capture status code thrown by fetch call
> Fix [#1]()

chore(node-fetch): capture fetchError status code thrown by fetch call

---

v0/sources/refiner/transform.js

- [✅ ] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- [ ✅] "Ready for review" label attached to the PR and reviewers mentioned in a comment

fix: refiner source

---

__tests__/data/algolia_input.json
__tests__/data/algolia_output.json
__tests__/data/algolia_router_input.json
__tests__/data/algolia_router_output.json
cdk/v2/destinations/algolia/rtWorkflow.yaml
cdk/v2/destinations/algolia/trackEventWorkflow.yaml
package-lock.json
package.json
v0/destinations/algolia/transform.js

Comparison test was failing for algolia cdk version due to stat tag mismatch so made changes to workflow to fix it.
Aslo added test cases.
- [] Lint rules pass locally

fix: error stat issue for algolia

---

__tests__/data/facebook_pixel_input.json
__tests__/data/facebook_pixel_output.json
__tests__/data/fb_output.json
__tests__/data/ga4.json
__tests__/data/zendesk_input.json
__tests__/data/zendesk_output.json
v0/destinations/facebook_pixel/transform.js
v0/destinations/facebook_pixel/utils.js
v0/destinations/ga/transform.js
v0/destinations/ga4/transform.js
v0/destinations/zendesk/transform.js
v0/util/index.js

Fixing errors caught in bugsnag.
> Fix [#1]()

fix: fixing errors caught by bugsnag

---

CODEOWNERS

Cleaned up CODEOWNERS file.
- Brought CDK directory into integrations team's scope and took out adapters directory.
N/A

chore: clean up CODEOWNERS file

---

v0/destinations/azure_event_hub/transform.js
v0/destinations/confluent_cloud/transform.js

Fixed lodash cloneDeep imports.
N/A

fix: incorrect lodash cloneDeep import

---

CHANGELOG.md
package-lock.json
package.json
v0/destinations/azure_event_hub/transform.js
v0/destinations/confluent_cloud/transform.js

chore: sync master to saas

---

package-lock.json
package.json

Upgraded the rudder-workflow-engine dependency to latet.
This package version has a slightly performant jsonata module bundled within it.
N/A

feat: integrate latest version of workflow engine

---

.github/workflows/pr-builds.yml
.github/workflows/saas-builds.yml

> convert slash to dot to get valid docker image name
> Fix [#1]()

fix(transformation): convert slash to dot to get valid docker image name

---

__tests__/data/shopify_source_input.json
__tests__/data/shopify_source_output.json
v0/sources/shopify/config.js

Bug fix for fixing the typo in topic mapping for track events in the shopify source transformation
> Fix [#1]()

fix: typo in topic mapping for shopify source

---

v0/destinations/marketo/util.js

Adding log in Marketo for ensuring cache eviction
> Fix [#1]()

fix: (marketo) - adding log for cache eviction

---

v0/destinations/marketo/util.js
v0/sources/shopify/config.js

chore: sync master to saas 

---

v0/destinations/marketo/util.js

Fixing wrong import of logger 
> Fix [#1]()

fix: (marketo) logger import

---

v0/destinations/campaign_manager/networkHandler.js
v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
v0/destinations/google_adwords_offline_conversions/networkHandler.js
v0/destinations/google_adwords_offline_conversions/utils.js
v0/destinations/google_adwords_remarketing_lists/networkHandler.js
v0/destinations/pardot/networkHandler.js
v0/destinations/snapchat_custom_audience/networkHandler.js

Remove disable destination category from OAuth Destinations so that disable destination flow doesn't occur
> Fix [#1]()

fix: remove disable destination category for OAuth destinations

---

__tests__/data/olark_source.json
__tests__/olark_source.test.js
v0/sources/olark/groupMapping.json
v0/sources/olark/trackMapping.json
v0/sources/olark/transform.js
v0/sources/olark/util.js

- Olark source transformer development
> Fix [#1]()

feat: onboard olark source

---

v0/destinations/braze/config.js
v0/destinations/braze/transform.js

> Subscription Group support in braze
> Fix [#1]()

feat: added subscription group in braze

---

v0/destinations/awin/utils.js

> Handling empty object(`params`) in Awin(cloud-mode destination)
> Fix [#1]()

fix(destination): empty params fix in awin

---

.github/workflows/master-bulids.yml

> add master build action
> Fix [#1]()

chore(ci): add master build action

---

src/util/eventValidation.js
src/util/trackingPlan.js
test/__tests__/eventValidation.test.js

> Added tests with removal of track and global config
> Linting changes applied to trackingPlan and eventVlaidation js files
> Lowercase check on sendViolatedEventsTo, value `procErrors` to `procerrors`
> Fix [#1]()

chore(trackingplan): added tests with no track or global config

---

src/versionedRouter.js
test/__tests__/data/proxy_output.json

Addressed the failures in `proxy.test.js` test script.
N/A

test: fix generic proxy test suite failures

---

src/v0/util/regulation-api.js

Replaced old error types with new in the regulation API utils.
N/A

refactor: use new error types

---

src/v0/destinations/ga360/transform.js
src/v0/destinations/gainsight/transform.js
src/v0/destinations/gainsight/util.js
src/v0/destinations/gainsight_px/transform.js
src/v0/destinations/gainsight_px/util.js
src/v0/destinations/google_cloud_function/util.js
src/v0/destinations/googlepubsub/transform.js
test/__tests__/data/ga360_output.json
test/__tests__/data/google_cloud_function_router_output.json

feat: refactor new error types (ga360, gainsight, gainsight_px, google_cloud_function, googlepubsnub)

---

src/constants/destinationCanonicalNames.js
src/v0/destinations/ga4/transform.js

Reverts rudderlabs/rudder-transformer#1617

feat: onboard ga4 hybrid mode

---

src/v0/destinations/lambda/transform.js
src/v0/destinations/leanplum/transform.js
src/v0/destinations/lytics/transform.js
src/v0/destinations/mailchimp/transform.js
src/v0/destinations/mailchimp/utils.js
src/v0/destinations/mailmodo/transform.js
test/__tests__/data/mailchimp_batch_output.json
test/__tests__/data/mailchimp_output.json
test/__tests__/data/mailchimp_router_output.json
test/__tests__/data/mailmodo.json
test/__tests__/data/mailmodo_router_output.json

feat: new error types for destinations(mailmodo, mailchimp, lytics, leanplum, lambda)

---

src/v0/destinations/personalize/transform.js
src/v0/destinations/pinterest_tag/transform.js
src/v0/destinations/pinterest_tag/utils.js
src/v0/destinations/posthog/transform.js
src/v0/destinations/profitwell/transform.js
src/v0/destinations/profitwell/utils.js
test/__tests__/data/personalize_output.json
test/__tests__/data/pinterest_tag_output.json
test/__tests__/data/profitwell_output.json

feat: new error types for destinations(profitwell, posthog, postgres, pinterest_tag, personalize)

---

src/v0/destinations/ometria/networkResponseHandler.js
src/v0/destinations/ometria/transform.js
src/v0/destinations/one_signal/transform.js
src/v0/destinations/one_signal/util.js
src/v0/destinations/pardot/networkHandler.js
src/v0/destinations/pardot/transform.js
src/v0/destinations/persistiq/transform.js
src/v0/destinations/persistiq/util.js
test/__tests__/data/one_signal.json
test/__tests__/data/pardot_router_output.json
test/__tests__/data/persistiq.json
test/__tests__/data/persistiq_router.json

feat: new error types for destinations(persistiq, pardot, one_signal, ometria, mssql)

---

src/v0/destinations/keen/transform.js
src/v0/destinations/kissmetrics/transform.js
src/v0/destinations/klaviyo/transform.js
src/v0/destinations/klaviyo/util.js
src/v0/destinations/kochava/transform.js
src/v0/destinations/kustomer/transform.js
src/v0/destinations/kustomer/util.js
test/__tests__/data/keen_output.json
test/__tests__/data/klaviyo.json

feat: new error types for destinations(kustomer, kochava, klaviyo, kissmetrics, keen)

---

src/v0/destinations/redis/transform.js
src/v0/destinations/refiner/transform.js
src/v0/destinations/revenue_cat/transform.js
src/v0/destinations/rockerbox/transform.js
test/__tests__/data/refiner.json
test/__tests__/data/revenue_cat_output.json
test/__tests__/data/rockerbox.json

feat: new error types for destinations (rockerbox, revenue_cat, redis, refiner)

---

src/v0/destinations/splitio/transform.js
src/v0/destinations/statsig/transform.js
src/v0/destinations/tiktok_ads/transform.js
test/__tests__/data/splitio_output.json
test/__tests__/data/tiktok_ads_output.json

feat: new error types for destinations (tiktok_ads, statsig, splitio, snowflake) 

---

.github/workflows/master-bulids.yml
.github/workflows/pr-builds.yml
.github/workflows/saas-builds.yml
buildspec.dev.yml
buildspec.master.yml
buildspec.saas.yml
buildspec.saasdev.yml
buildspec.yml
package-lock.json
package.json

Revamped NPM scripts in `package.json`.
- script names as per NPM convention
- Test scripts for versioned router and test router were redundantly executed previously in multiple npm scripts.
- Added some dev dependencies (to be used later).
> Fix [#1]()

chore: revamp npm scripts

---

src/v0/sources/gainsightpx/transform.js
src/v0/sources/iterable/transform.js
src/v0/sources/mailmodo/transform.js
src/v0/sources/monday/transform.js
src/v0/sources/shopify/transform.js
src/v0/sources/shopify/util.js

feat: new error types for sources (gainsightpx, iterable, mailmodo, monday, shopify) 

---

src/v0/destinations/webhook/transform.js
src/v0/destinations/woopra/transform.js
src/v0/destinations/wootric/transform.js
src/v0/destinations/wootric/util.js
src/v0/destinations/yahoo_dsp/transform.js
src/v0/destinations/yahoo_dsp/util.js
src/v0/destinations/zendesk/transform.js
test/__tests__/data/woopra.json
test/__tests__/data/woopra_router_output.json
test/__tests__/data/wootric.json
test/__tests__/data/wootric_router_output.json
test/__tests__/data/yahoo_dsp_output.json
test/__tests__/data/zendesk_output.json

feat: new error types for destinations (webhook, wootric, woopra, yahoo_dsp, zendesk)

---

src/v0/destinations/marketo/networkHandler.js
src/v0/destinations/marketo/transform.js
src/v0/destinations/marketo/util.js
src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js
src/v0/destinations/marketo_bulk_upload/fileUpload.js
src/v0/destinations/marketo_bulk_upload/poll.js
src/v0/destinations/marketo_bulk_upload/transform.js
src/v0/destinations/marketo_bulk_upload/util.js
src/v0/destinations/marketo_static_list/networkHandler.js
src/v0/destinations/marketo_static_list/transform.js
src/v0/destinations/marketo_static_list/util.js
test/__tests__/data/marketo_bulk_upload_fileUpload_output.json
test/__tests__/data/marketo_bulk_upload_output.json
test/__tests__/data/marketo_bulk_upload_poll_output.json
test/__tests__/data/marketo_router_output.json
test/__tests__/data/marketo_static_list.json
test/__tests__/data/marketo_static_list_proxy_output.json
test/__tests__/data/marketo_static_list_router_output.json

feat: new error types for destinations(marketo, marketo_static_list, marketo_bulk_upload)

---

src/v0/util/index.js

fix: heap test cases

---

src/cdk/dcm_floodlight/transform.js
test/__tests__/data/dcm_floodlight_output.json
test/__tests__/data/june_router_output.json

feat: refactor-dcm_floodlight-cdk-errorTypes

---

src/adapters/utils/networkUtils.js
src/v0/destinations/azure_event_hub/transform.js
src/v0/destinations/braze/networkHandler.js
src/v0/destinations/clevertap/networkHandler.js
src/v0/destinations/confluent_cloud/transform.js
src/v0/destinations/facebook_pixel/networkHandler.js
src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
src/v0/destinations/kafka/transform.js
src/v0/destinations/marketo/networkHandler.js
src/v0/destinations/marketo/util.js
src/v0/destinations/marketo_static_list/networkHandler.js
src/v0/destinations/pardot/networkHandler.js
src/v0/destinations/salesforce/networkHandler.js
src/v0/destinations/salesforce/transform.js
src/v0/destinations/salesforce/utils.js
src/v0/destinations/snapchat_custom_audience/networkHandler.js
test/__tests__/data/braze_proxy_output.json
test/__tests__/data/clevertap_proxy_output.json
test/__tests__/data/facebook_pixel_proxy_output.json
test/__tests__/data/google_adwords_enhanced_conversions_proxy_output.json
test/__tests__/data/google_adwords_remarketing_lists_proxy_output.json
test/__tests__/data/marketo_proxy_output.json
test/__tests__/data/marketo_static_list_proxy_output.json
test/__tests__/data/pardot_proxy_output.json
test/__tests__/data/salesforce_proxy_output.json
test/__tests__/data/snapchat_custom_audience_proxy_output.json

fix: proxy test cases

---

jest.config.js
src/cdk/autopilot/transform.js
src/util/errorNotifier/bugsnag.js
src/v0/destinations/af/transform.js
src/v0/destinations/autopilot/transform.js
src/v0/destinations/facebook_pixel/transform.js
src/v0/sources/customerio/transform.js
src/warehouse/identity.js
src/warehouse/index.js
src/warehouse/util.js
src/warehouse/v1/util.js
test/__tests__/warehouse.test.js

Replaced all the leftover instances of previous error types.
N/A

chore: refactor all instances of previous error types

---

src/v0/destinations/tiktok_ads/transform.js
src/v0/destinations/trengo/transform.js
src/v0/destinations/user/transform.js
src/v0/destinations/userlist/transform.js
src/v0/destinations/vero/transform.js
src/v0/destinations/webengage/transform.js
src/v0/destinations/webhook/transform.js
src/v0/destinations/woopra/transform.js
src/v0/destinations/yahoo_dsp/transform.js
src/v0/destinations/zendesk/transform.js
src/v0/util/index.js
test/__tests__/data/woopra_router_output.json

feat: router tranform refacor for destinations (batch - 1)

---

src/v0/destinations/salesforce/transform.js
src/v0/destinations/sendgrid/transform.js
src/v0/destinations/serenytics/transform.js
src/v0/destinations/sfmc/transform.js
src/v0/destinations/shynet/transform.js
src/v0/destinations/signl4/transform.js
src/v0/destinations/singular/transform.js
src/v0/destinations/slack/transform.js
src/v0/destinations/snapchat_conversion/transform.js
src/v0/destinations/snapchat_custom_audience/transform.js
src/v0/destinations/splitio/transform.js
test/__tests__/data/signl4_router_output.json
test/__tests__/data/slack_router_output.json

feat: router tranform refacor for destinations (batch - 2)

---

src/v0/destinations/active_campaign/transform.js
src/v0/destinations/adj/transform.js
src/v0/destinations/adobe_analytics/transform.js
src/v0/destinations/af/transform.js
src/v0/destinations/airship/transform.js
src/v0/destinations/algolia/transform.js
src/v0/destinations/am/transform.js
src/v0/destinations/appcues/transform.js
src/v0/destinations/attentive_tag/transform.js
src/v0/destinations/autopilot/transform.js
src/v0/destinations/awin/transform.js
src/v0/destinations/blueshift/transform.js
src/v0/destinations/branch/transform.js
src/v0/destinations/braze/transform.js
src/v0/destinations/campaign_manager/transform.js
src/v0/destinations/candu/transform.js
src/v0/destinations/canny/transform.js
src/v0/destinations/clevertap/transform.js
src/v0/destinations/clickup/transform.js
src/v0/destinations/custify/transform.js

feat: refactor router transformer - 1

---

src/v0/destinations/customerio/transform.js
src/v0/destinations/delighted/transform.js
src/v0/destinations/drip/transform.js
src/v0/destinations/engage/transform.js
src/v0/destinations/eventbridge/transform.js
src/v0/destinations/facebook_offline_conversions/transform.js
src/v0/destinations/facebook_pixel/transform.js
src/v0/destinations/factorsai/transform.js
src/v0/destinations/fb/transform.js
src/v0/destinations/firehose/transform.js

feat: refactor router transformer - 2

---

src/v0/destinations/freshmarketer/transform.js
src/v0/destinations/freshsales/transform.js
src/v0/destinations/ga/transform.js
src/v0/destinations/ga360/transform.js
src/v0/destinations/gainsight/transform.js
src/v0/destinations/gainsight_px/transform.js
src/v0/destinations/google_adwords_enhanced_conversions/transform.js
src/v0/destinations/google_adwords_offline_conversions/transform.js
src/v0/destinations/google_adwords_remarketing_lists/transform.js
src/v0/destinations/google_cloud_function/transform.js

feat: refactor router transformer - 3

---

src/cdk/v2/bindings/default.js
src/cdk/v2/destinations/algolia/procWorkflow.yaml
src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
src/cdk/v2/utils.js
src/controllers/destinationProxy.js
src/v0/destinations/active_campaign/util.js
src/v0/destinations/autopilot/transform.js
src/v0/destinations/braze/networkHandler.js
src/v0/destinations/canny/util.js
src/v0/destinations/custify/transform.js
src/v0/destinations/delighted/transform.js
src/v0/destinations/drip/transform.js
src/v0/destinations/engage/transform.js
src/v0/destinations/eventbridge/transform.js
src/v0/destinations/fb_custom_audience/transform.js
src/v0/destinations/ga/networkHandler.js
src/v0/destinations/ga360/transform.js
src/v0/destinations/ga4/networkHandler.js
src/v0/destinations/gainsight_px/transform.js
src/v0/destinations/gainsight_px/util.js
src/v0/destinations/google_adwords_enhanced_conversions/transform.js
src/v0/destinations/marketo/transform.js
src/v0/destinations/snapchat_custom_audience/transform.js
src/v0/destinations/trengo/transform.js
src/v0/util/index.js
src/versionedRouter.js
test/__tests__/data/delighted_output.json
test/__tests__/data/google_adwords_enhanced_conversions_output.json

Fixed all the instances of incorrect usage of error types.
Also, removed all the usages of `TRANSFORMER_METRIC` as it is already removed.
N/A

fix: incorrect usages of error types

---

src/versionedRouter.js

Supressing these logs prevent any sensitive data leaking to logs.
Supressing these logs prevent any sensitive data leaking to logs.
> Fix [#1]()

chore: suppress cdk v2 comparison logs

---

src/versionedRouter.js

Supressing these logs prevent any sensitive data leaking to logs.
Saas <- Master
> Fix [#1]()

chore: sync master with rudder-saas

---

Dockerfile
Dockerfile-no-func

Upgraded the [base node image version](https://hub.docker.com/layers/library/node/14.21.1-alpine3.15/images/sha256-931c71420abf7c3e0e04b8669e3e105d65bcd68703cb129a6a16ce68876964ae?context=explore) as per the reported Snyk vulnerability.
https://app.snyk.io/org/subbu-utx/project/49a042b5-9abe-4ccd-889e-9d719cbeca7d?utm_campaign=vuln_alert&utm_medium=email&utm_source=Project
N/A

fix: upgrade base node image in dockerfiles

---

src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
src/v0/util/errorTypes/abortedError.js
src/v0/util/errorTypes/base.js
src/v0/util/errorTypes/invalidAuthTokenError.js
src/v0/util/errorTypes/networkError.js
src/v0/util/errorTypes/retryableError.js
src/v0/util/errorTypes/transformationError.js
src/v0/util/errorTypes/unauthorizedError.js
src/versionedRouter.js
test/__tests__/data/google_adwords_enhanced_conversions_proxy_output.json
test/__tests__/data/google_adwords_offline_conversions_proxy_output.json
test/__tests__/data/pardot_proxy_output.json

fix: add parsed response in network error

---

src/v0/destinations/facebook_pixel/networkHandler.js
src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
test/__tests__/data/facebook_pixel_proxy_output.json
test/__tests__/data/google_adwords_remarketing_lists_proxy_output.json

fix: destinations network error responses

---

src/versionedRouter.js

> error property population
> Fix [#1]()

fix(trackingplan): error message population

---

CHANGELOG.md
Dockerfile
Dockerfile-no-func
buildspec.saas.yml
package-lock.json
package.json
src/versionedRouter.js

chore(release): sync master to rudder-saas

---

src/v0/destinations/af/deleteUsers.js
src/v0/destinations/am/deleteUsers.js
src/v0/destinations/braze/deleteUsers.js
src/v0/destinations/clevertap/deleteUsers.js
src/v0/destinations/engage/deleteUsers.js
src/v0/destinations/intercom/deleteUsers.js
src/v0/destinations/mp/deleteUsers.js
src/v0/destinations/sendgrid/deleteUsers.js
test/__tests__/deleteUsers/data/af/handler_output.json
test/__tests__/deleteUsers/data/am/handler_input.json
test/__tests__/deleteUsers/data/am/handler_output.json
test/__tests__/deleteUsers/data/braze/handler_input.json
test/__tests__/deleteUsers/data/braze/handler_output.json
test/__tests__/deleteUsers/data/clevertap/handler_output.json
test/__tests__/deleteUsers/data/engage/handler_output.json
test/__tests__/deleteUsers/data/intercom/handler_input.json
test/__tests__/deleteUsers/data/intercom/handler_output.json
test/__tests__/deleteUsers/data/mp/handler_output.json

- adding consistent error handling to all deletion flows
- returning destination level status to caller
- adding integration names to message to better debug at bugsnag
- adding error response (network failures) to error message for better visibility at bugsnag
> Fix [#1]()

fix: update to add robust error handling

---

src/v0/destinations/salesforce/transform.js
test/__mocks__/data/salesforce/response.json
test/__tests__/data/salesforce_router_input.json
test/__tests__/data/salesforce_router_output.json

Adding URL encoding of email before user lookup call. 
> Fix [#1]()

fix: encode email with encodeUriComponent before searching

---

src/v0/sources/pagerduty/data/eventMapping.json
src/v0/sources/pagerduty/data/trackMapping.json
src/v0/sources/pagerduty/transform.js
test/__tests__/data/pagerduty_source.json
test/__tests__/pagerduty.test.js

feat: onboard pagerduty source

---

src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
src/v0/destinations/pinterest_tag/data/pinterestCustomConfig.json
test/__tests__/data/pinterest_tag_input.json
test/__tests__/data/pinterest_tag_output.json
test/__tests__/data/pinterest_tag_router_batch_output.json
test/__tests__/data/pinterest_tag_router_input.json
test/__tests__/data/pinterest_tag_router_output.json

> Add LDP Support 
- Add new field properties.optOutType
- For Limited Data Processing user need to pass properties.optOutType = LDP
- properties.optOutType mapped to custom_data.opt_out_type in Pinterest (opt_out_type can accept comma separated values)
> Fix [#1]()

feat(pinterest): add ldp support

---

src/v0/sources/appcenter/transform.js
test/__tests__/data/appcenter_source_input.json
test/__tests__/data/appcenter_source_output.json

> Incorporating the test event scenario send by appcenter's new feature of verifying the URL.
> Fix [#1]() 
https://github.com/rudderlabs/rudder-transformer/issues/1724

feat: appcenter updated to support test events

---

src/v0/destinations/zendesk/config.js
src/v0/destinations/zendesk/transform.js

Signed-off-by: Sai Sankeerth <sanpj2292@github.com>
Hot-fix PR for zendesk global variable
> Fix [#1]()

fix(zendesk): get rid of global variable

---

src/v0/destinations/ga4/transform.js
src/v0/util/index.js

feat: clientId support added for ga4 hybrid mode

---

src/v0/destinations/tiktok_ads/transform.js
test/__tests__/data/tiktok_ads_input.json

Setting content_type to product by default.
> Fix [#1]()

fix: set content_type product by default

---

src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js

https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63bd5b2803ad1e0008a3cc51?event_id=63bd5b2800a374e00f6b0000&i=wh&m=nw
> Fix [#1]()

fix(google_adwords_enhanced_conversions): proper error throw in gaec

---

src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
src/v0/destinations/salesforce/utils.js

Bugsnag errors fix for Sprint-31
- https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63a67990dcaa2500086ad048?event_id=63a6799000a2ec03dd930000&i=wh&m=nw&pivot_tab=event
- https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63a67990dcaa2500086ad048?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open
- https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/637c6cae6726d5000802a34e?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open
- https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63a0c906c8addc000866d037?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open
> Fix [#1]()

fix: bugsnag error fixes for salesforce, garl, gaoc

---

src/constants/index.js
src/v0/destinations/am/config.js
src/v0/destinations/am/transform.js

Removed the destination-specific event type from global constants.
N/A

refactor: clean up event types constant

---

src/v0/destinations/iterable/transform.js
test/__tests__/data/iterable_router_output.json

fix: iterable alias call is separated from identify batching

---

src/v0/util/errorTypes/configurationError.js
test/__tests__/data/facebook_offline_conversions_router.json
test/__tests__/data/google_adwords_offline_conversions.json
test/__tests__/data/google_cloud_function_router_output.json
test/__tests__/data/mautic_router_output.json
test/__tests__/data/sfmc_router_output.json
test/__tests__/data/snapchat_conversion_router_output.json
test/__tests__/deleteUsers/data/af/handler_output.json
test/__tests__/deleteUsers/data/am/handler_output.json
test/__tests__/deleteUsers/data/braze/handler_output.json
test/__tests__/deleteUsers/data/clevertap/handler_output.json
test/__tests__/deleteUsers/data/engage/handler_output.json
test/__tests__/deleteUsers/data/intercom/handler_output.json
test/__tests__/deleteUsers/data/mp/handler_output.json
test/__tests__/deleteUsers/data/sendgrid/handler_output.json

Convert all the configuration errors to abortable.
N/A

fix: change destination configuration errors to abortable

---

CODEOWNERS

> Added a code owner from services team
> Fix [#1]()

chore(owner): added a code owner

---

src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
src/v0/destinations/google_adwords_offline_conversions/transform.js
test/__tests__/data/google_adwords_offline_conversions.json
test/__tests__/data/google_adwords_offline_conversions_proxy_input.json
test/__tests__/data/google_adwords_offline_conversions_proxy_output.json

> We are incorporating 2 fixes in this PR.
1. This timestamp format [issue](https://github.com/rudderlabs/rudder-transformer/issues/1621) is related to wrong timestamp moment format being used for minutes and seconds.
2. We are checking for customVariable but it is not a required field. We should not make that API call if custom variable are not present.
> Fix [#1]()

fix(integration): gaoc - fix timestamp format, allow calls without custom var

---

src/v0/util/index.js
test/__tests__/data/active_campaign_router_input.json
test/__tests__/data/active_campaign_router_output.json

- For formattingType domainUrlV2, we are not handling invalid url. We used the isValidUrl function already present & handle accordingly
Bugsnag: [https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63bde73412f50500089f36e0?filters[event.since]=all&filters[error.status]=for_review](https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63bde73412f50500089f36e0?filters%5Bevent.since%5D=all&filters%5Berror.status%5D=for_review)
> Fix [#1]()

fix(active_campaign): handle bad url string while formatting with domainUrlV2

---

src/versionedRouter.js

Log only non matching keys so that it won't voilate privacy concerns.
> Fix [#1]()

chore: add logging for cdk v2 for debugging comparison failures

---

src/v0/destinations/mp/transform.js

fix: typecast userId, anonymousId to string

---

src/v0/destinations/rockerbox/transform.js
test/__tests__/data/rockerbox.json

> We are adding functionality to support custom properties to be mapped here and sent over to Rockerbox for Track events. This will essentially allow the user to map their event properties to the respective custom property over at Rockerbox.
> Fix [#1]()

feat(integration): rockerbox - add support for custom properties mapping

---

CHANGELOG.md
package-lock.json
package.json
src/v0/destinations/rockerbox/transform.js
src/v0/destinations/salesforce/transform.js
src/v0/destinations/salesforce/utils.js
src/v0/destinations/singular/transform.js
src/v0/util/index.js
src/versionedRouter.js
test/__mocks__/data/salesforce/proxy_response.json
test/__tests__/__integration_util_test__/isHybridModeEnabled.test.js
test/__tests__/data/active_campaign_router_input.json
test/__tests__/data/active_campaign_router_output.json
test/__tests__/data/ga4.json
test/__tests__/data/rockerbox.json
test/__tests__/data/salesforce_proxy_input.json
test/__tests__/data/salesforce_proxy_output.json
test/__tests__/data/singular_router_input.json
test/__tests__/data/singular_router_output.json

Rudder-saas <- Master
> Fix [#1]()

chore: sync master to rudder-saas

---

buildspec.saas.yml

- fix: codebuild issue
> Fix [#1]()

fix: codebuild for rudder saas

---

src/v0/destinations/am/transform.js
test/__tests__/data/am_input.json
test/__tests__/data/am_output.json

> #1830 is continue
> Fix [#1]()

fix: amplitude check for actionKey before accessing it 

---

package-lock.json
package.json
test/integrations/destinations/canny/data.js
test/integrations/destinations/canny/data.json
test/integrations/destinations/testTypes.d.ts
test/integrations/integrations.test.js
test/integrations/testUtils.js

Refactor the test suite for component testing of the integrations.
N/A

refactor: unit test suite for integrations

---

test/__tests__/__integration_util_test__/data/extractCustomFields.json
test/__tests__/__integration_util_test__/v0_utilities.test.js

> Added unit tests for `extractCustomFields` function
> Fix [#1]()

test: add unit tests for extractCustomFields function

---

src/v0/destinations/ga4/data/GA4CommonConfig.json
test/__tests__/data/ga4.json

- event is failing to ga4 if user_id parameter is int
- in this pr we are converting userId to string so that it will not fail
> Fix [#1]()

fix: ga4 userId issue

---

src/v0/destinations/sendgrid/util.js
src/v0/destinations/zendesk/transform.js

> Fix bugsnag errors
> 
- https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63dd11bcab17c30008b71a08?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open
- https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/63dd3cd445464d0008320ef0?event_id=63ea057d00ad36ed038c0000&i=wh&m=oc

fix: bugsnag errors

---

src/v0/sources/shopify/transform.js
test/__tests__/data/shopify_source_output.json

> shopify token present for `orders_updated` event
> Fix [#1]()

fix: order_token updated in shopify

---

src/v0/destinations/klaviyo/config.js
src/v0/destinations/klaviyo/transform.js
src/v0/destinations/klaviyo/util.js
src/v0/sources/shopify/transform.js
test/__tests__/data/klaviyo.json
test/__tests__/data/klaviyo_router_output.json
test/__tests__/data/shopify_source_output.json

> sync develop-master
> Fix [#1]()

chore: sync develop-master

---

src/v0/destinations/snapchat_conversion/util.js

fix incorrect logger import in snapchat conversion destination
> Fix [#1]()

fix: incorrect logger import

---

src/controllers/destination.ts
src/helpers/serviceSelector.ts
src/interfaces/DestinationService.ts
src/routes/utils/constants.js
src/services/comparator.ts
src/services/destination/cdkV1Integration.ts
src/services/destination/cdkV2Integration.ts
src/services/destination/nativeIntegration.ts
src/types/index.ts
src/util/utils.js

feat: onboard comparator logic

---

features.json
src/constants/destinationCanonicalNames.js
src/v0/destinations/courier/config.js
src/v0/destinations/courier/transform.js
test/__mocks__/axios.js
test/__mocks__/courier.mock.js
test/__tests__/courier.test.js
test/__tests__/data/courier.json
test/__tests__/data/courier_router.json

> Onboarding new destination courier integration
> Fix [#1]()

feat(new integration): onboard courier

---

.github/workflows/master-bulids.yml
.github/workflows/saas-builds.yml

We are including the `latest` image for transformer through this PR
> Fix [#1]()

feat: include latest image of transformer

---

Dockerfile
Dockerfile-no-func
Dockerfile-ut-func

Sped up the docker builds by replacing `npm install` with `npm ci`.
Observed that the builds are at least **15%** faster!
N/A

chore(ci): improve build time with npm ci

---

features.json
src/v0/destinations/customerio/config.js
src/v0/destinations/customerio/data/customerIoGroup.json
src/v0/destinations/customerio/transform.js
src/v0/destinations/customerio/util.js
test/__tests__/customerio.test.js
test/__tests__/data/customerio_input.json
test/__tests__/data/customerio_output.json
test/__tests__/data/customerio_router_input.json
test/__tests__/data/customerio_router_output.json

- added group call support for customerio destination
- moved customerio destination from processor to router
- added batching support for group call
- max batch size : 1000
> Fix [#1]()

feat: added customerio group call support

---

.github/workflows/master-bulids.yml
.github/workflows/saas-builds.yml
Dockerfile
Dockerfile-no-func
Dockerfile-ut-func
features.json
package-lock.json
package.json
src/util/customTransforrmationsStore-v1.js
src/util/ivmFactory.js
src/v0/destinations/customerio/config.js
src/v0/destinations/customerio/data/customerIoGroup.json
src/v0/destinations/customerio/transform.js
src/v0/destinations/customerio/util.js
test/__tests__/customerio.test.js
test/__tests__/data/customerio_input.json
test/__tests__/data/customerio_output.json
test/__tests__/data/customerio_router_input.json
test/__tests__/data/customerio_router_output.json
test/__tests__/user_transformation.test.js

> sync dvelop-master
> Fix [#1]()

chore: sync dvelop-master

---

.github/workflows/housekeeping.yml
.github/workflows/master-bulids.yml
.github/workflows/release-please.yml
CONTRIBUTING.md
README.md
buildspec.master.yml

As `master` got renamed to `main`, some more clean ups had to be done.
N/A

chore: replace references of master with main

---

features.json
src/constants/destinationCanonicalNames.js
src/v0/destinations/courier/config.js
src/v0/destinations/courier/transform.js
test/__mocks__/axios.js
test/__mocks__/courier.mock.js
test/__tests__/courier.test.js
test/__tests__/data/courier.json
test/__tests__/data/courier_router.json

Onboard destination Courier
> Fix [#1]()

feat: onboard courier destination (#1844)

---

src/v0/destinations/active_campaign/transform.js

Added check before iterating stored event array for Active campaign
> Fix [#1]()

fix(active-campaign): add check before iterating stored event array

---

src/util/utils.js

chore: add stat to collect violations per event

---

CHANGELOG.md
package-lock.json
package.json
src/cdk/v1/vitally/config.yaml
src/constants/destinationCanonicalNames.js
src/util/customTransformer-faas.js
src/util/customTransformer.js
src/util/customTransformerFactory.js
src/util/ivmFactory.js
src/util/openfaas/faasApi.js
src/util/openfaas/index.js
src/util/parser.js
src/util/utils.js
src/v0/destinations/active_campaign/transform.js
src/v0/util/index.js
src/versionedRouter.js
test/__tests__/data/vitally_input.json
test/__tests__/data/vitally_output.json
test/__tests__/user_transformation.integration.test.js
test/__tests__/user_transformation.test.js
test/__tests__/utilities/test-utils.js
test/__tests__/vitally.test.js

> sync develop-main
> Fix [#1]()

chore: sync develop-main

---

.prettierignore
test/integrations/destinations/awin/data.js
test/integrations/destinations/canny/data.js
test/integrations/destinations/discord/processor/data.js
test/integrations/destinations/discord/router/data.js
test/integrations/destinations/factorsai/data.js
test/integrations/destinations/persistiq/processor/data.js
test/integrations/destinations/persistiq/router/data.js
test/integrations/destinations/s3/data.js
test/integrations/sources/moengage/data.js

Update unit tests in the new format for destination (awin)
> Fix [#1]()

chore:  update unit tests in new format (awin, persistIq, discord, factorsai, s3)

---

src/index.js
src/util/cluster.js
src/util/utils.js

Added a new handler on the process to catch segmentation faults and log them.
N/A

feat: log process memory errors

---

src/util/customTransformer.js
src/util/ivmFactory.js

> configurable env for isolate vm memory
> One customer is using heavy libraries 10 * ~5MB
> Increasing memory until figuring out root cause for 128MB exhaustion
> Fix [#1]()

chore: increase isolate vm memory

---

src/v0/destinations/moengage/config.js
src/v0/destinations/moengage/data/MoEngageAliasConfig.json
src/v0/destinations/moengage/transform.js
test/__tests__/data/moengage_input.json
test/__tests__/data/moengage_output.json

> moenagae alias call support
> Fix [#1]()

feat: moenagae alias call support

---

src/v0/destinations/google_adwords_enhanced_conversions/config.js
src/v0/destinations/google_adwords_offline_conversions/config.js
src/v0/destinations/google_adwords_remarketing_lists/config.js
test/__mocks__/data/google_adwords_remarketing_lists/proxy_response.json
test/__tests__/data/google_adwords_enhanced_conversions_output.json
test/__tests__/data/google_adwords_enhanced_conversions_proxy_input.json
test/__tests__/data/google_adwords_enhanced_conversions_router_output.json
test/__tests__/data/google_adwords_offline_conversions.json
test/__tests__/data/google_adwords_offline_conversions_proxy_input.json
test/__tests__/data/google_adwords_offline_conversions_router_output.json
test/__tests__/data/google_adwords_remarketing_lists_output.json
test/__tests__/data/google_adwords_remarketing_lists_proxy_input.json
test/__tests__/data/google_adwords_remarketing_lists_router_output.json
test/__tests__/google_adwords_offline_conversions.test.js

chore: upgrading google-api versions to v13

---

src/controllers/destinationProxy.js
src/index.js
src/metricsRouter.js
src/middleware.js
src/util/customTransformer-faas.js
src/util/customTransformer-lambda.js
src/util/customTransformer-v1.js
src/util/customTransformer.js
src/util/customTransforrmationsStore-v1.js
src/util/customTransforrmationsStore.js
src/util/ivmFactory.js
src/util/lambda/index.js
src/util/prometheus.js
src/util/stats.js
src/util/statsd.js
src/util/trackingPlan.js
src/util/utils.js
src/v0/destinations/facebook_pixel/transform.js
src/v0/destinations/marketo/transform.js
src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js
src/v0/destinations/marketo_bulk_upload/fileUpload.js
src/v0/destinations/marketo_bulk_upload/poll.js
src/v0/destinations/marketo_bulk_upload/util.js
src/v0/sources/shopify/transform.js
src/v0/util/index.js
src/versionedRouter.js

Chore.prometheus1

---

src/v0/destinations/braze/config.js
src/v0/destinations/braze/transform.js
test/__tests__/data/braze_input.json
test/__tests__/data/braze_output.json

> refactor code custom attribute operations
> Fix [#1]()

chore(braze): refactor code custom attribute operations

---

src/util/customTransformer-faas.js
src/util/customTransformer-lambda.js
src/util/customTransformer-v1.js
src/util/customTransformer.js
src/util/utils.js
src/versionedRouter.js

chore(transformation): stats for ut

---

src/util/customTransformer-faas.js
src/util/customTransformer-lambda.js
src/util/customTransformer-v1.js
src/util/customTransformer.js
src/util/utils.js
src/versionedRouter.js

Reverts rudderlabs/rudder-transformer#1958

chore(transformation): revert stats for ut

---

.github/workflows/housekeeping.yml

chore: fix token in housekeeping workflow

---

.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml

chore: fix syntax issues in reusable workflow jobs

---

.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml

chore: fix workflow file path

---

.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml
codecov.yml

chore: report coverage only on push

---

.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml

chore: fix syntax issue in workflow conditionals

---

src/v0/destinations/tiktok_ads_offline_events/transform.js
test/__tests__/data/tiktok_ads_offline_events.json

https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/6419c9ff8a80c30008334192?event_id=6419c9ff00b9f7ecd1170000&i=wh&m=oc
> Fix [#1]()

fix: tik-tok ads offline events email array issue

---

src/v0/destinations/ga4/transform.js
test/__tests__/data/ga4.json

- updated the structure of user_properties
- GA4 is expecting every user_property as object
> Fix [#1]()

fix: ga4 user_properties structure

---

.github/workflows/publish-new-release.yml
package.json

chore: fix tag naming convention

---

.github/workflows/prepare-for-staging-deploy.yml

chore: fix typo in staging deploy workflow

---

.dockerignore
.github/workflows/build-pr-artifacts.yml
.github/workflows/draft-new-release.yml
.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml
.github/workflows/prepare-for-prod-rollback.yml
.github/workflows/prepare-for-staging-deploy.yml
.github/workflows/publish-new-release.yml
Dockerfile
package.json

chore: optimized github actions

---

.github/workflows/prepare-for-staging-deploy.yml

chore: fix staging workflow

---

src/util/customTransformer-faas.js
src/util/customTransformer-lambda.js
src/util/customTransformer-v1.js
src/util/customTransformer.js
src/util/utils.js
src/versionedRouter.js

chore: stats to user transformer

---

src/v0/destinations/monday/util.js
test/__mocks__/axios.js
test/__mocks__/data/monday/response.json
test/__mocks__/monday.mock.js
test/__tests__/data/monday.json

https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/641df34a9945c00007375e9a?event_id=641df34a00ba5a4d3c420000&i=wh&m=nw
> Fix [#1]()

fix(monday):  axios call empty response issue

---

src/v0/destinations/rockerbox/data/RockerboxTrackConfig.json
src/v0/destinations/rockerbox/transform.js
test/__tests__/data/rockerbox.json
test/__tests__/data/rockerbox_router_output.json

Make email as non-required field for rockerbox destination
> Fix [#1]()

fix(rockerbox): make email as non-required field

---

src/v0/destinations/gainsight_px/transform.js
test/__tests__/data/gainsight_px_input.json
test/__tests__/data/gainsight_px_output.json

https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/642245a1d802040008336b17?event_id=642245a100ba5d787ceb0000&i=wh&m=nw
> Fix [#1]()

fix(gainsignt_px): undefined attributes issue

---

src/v0/sources/customerio/transform.js

Updating logic of getting event name from the received event.
> Fix [#1]()

fix(customerio): update logic of getting event name

---

package-lock.json
package.json
src/v0/sources/customerio/transform.js

Bumping new version
> Fix [#1]()

chore: bump new version

---

src/util/errorNotifier/bugsnag.js

fix: add the missing git commit sha of the source to bugsnag

---

src/v0/destinations/customerio/config.js
src/v0/destinations/customerio/transform.js
test/__tests__/data/customerio_input.json
test/__tests__/data/customerio_output.json

- previously we were only filtering group calls based on default endpoint where as we missed EU centre endpoint, added fix for that in this pr
> Fix [#1]()

fix(customerio): group call filter logic

---

src/constants/destinationCanonicalNames.js

> Add canonical names for Adobe analytics
> Fix [#1]()

fix: add canonicals for adobe analytics

---

src/v0/destinations/tiktok_ads_offline_events/transform.js
test/__tests__/data/tiktok_ads_offline_events.json

- added support of phone numbers as an array
> Fix [#1]()

feat(tiktok_ads_offline_conversions): support of multiple phone numbers

---

src/cdk/v2/destinations/webhook/procWorkflow.yaml

fix(cdk v2): webhook destination can accept payload without message type

---

src/v0/destinations/mp/transform.js
test/__tests__/data/mp_input.json
test/__tests__/data/mp_output.json

> Added simplified api in page/screen/group and revenue event.
> Fix [#1]()

feat(mixpanel): add simplified api in page/screen/group/revenue event

---

.github/workflows/create-hotfix-branch.yml
.github/workflows/draft-new-release.yml

chore: give access to @sandeepdsvs and @shrouti1507 for triggering Github actions

---

.github/workflows/publish-new-release.yml

chore: fix typo in slack notification step

---

src/v0/sources/shopify/util.js
test/__tests__/data/redis/shopify_source.json

> Mapping default value for userId in case no anonymousId is there
> Fix [#1]()

fix: shopify anon id default val

---

src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
src/v0/destinations/pinterest_tag/utils.js
test/__tests__/data/pinterest_tag_input.json
test/__tests__/data/pinterest_tag_output.json

feat(pinterest): passing unkown event in v3

---

src/index.ts
src/routes/metricsRouter.js
src/routes/misc.ts
src/util/cluster.js

Transformer when running in cluster mode is not shutting down gracefully. This pr fixes the issue.

fix: gracefulshutdown

---

src/v0/destinations/attentive_tag/transform.js
test/__tests__/data/attentive_tag_input.json
test/__tests__/data/attentive_tag_output.json

Ecom events user object fix in the output. `externalIdentifiers` object is expected at inside user object, and were sent at root level.
> Fix [#1]()

fix(attentive_tag): ecom events user object fix

---

.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml
.github/workflows/report-code-coverage.yml

chore: fix sending secrets to reusable workflows

---

src/v0/destinations/ga4/data/GA4TrackPageCommonParamsConfig.json
test/__tests__/data/ga4.json

feat(ga4): common page call information(page, url, title) support in track call

---

.github/workflows/build-pr-artifacts.yml
.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml
.github/workflows/prepare-for-staging-deploy.yml

feat: checkout code for generating tags

---

.github/workflows/build-pr-artifacts.yml
.github/workflows/prepare-for-dev-deploy.yml
.github/workflows/prepare-for-prod-deploy.yml
.github/workflows/prepare-for-staging-deploy.yml

Reverts rudderlabs/rudder-transformer#2153

revert: checkout code for generating tags

---

src/services/userTransform.ts
src/util/prometheus.js

Adds 
a. missing labels to the prometheus metrics
b. new metric to the metrics array
c. inc -> histogram for histogram metric type
> Fix [#1]()

fix: prometheus metrics errors

---

src/v0/destinations/snapchat_conversion/data/CheckoutStartedConfig.json
src/v0/destinations/snapchat_conversion/data/OrderCompletedConfig.json
src/v0/destinations/snapchat_conversion/data/PaymentInfoEnteredConfig.json
src/v0/destinations/snapchat_conversion/data/ProductAddedConfig.json
src/v0/destinations/snapchat_conversion/data/ProductAddedToWishlistConfig.json
src/v0/destinations/snapchat_conversion/data/ProductListViewedConfig.json
src/v0/destinations/snapchat_conversion/data/ProductViewedConfig.json
src/v0/destinations/snapchat_conversion/data/ProductsSearchedConfig.json
src/v0/destinations/snapchat_conversion/data/PromotionClickedConfig.json
src/v0/destinations/snapchat_conversion/data/PromotionViewedConfig.json
src/v0/destinations/snapchat_conversion/data/SignupConfig.json
src/v0/destinations/snapchat_conversion/data/SnapchatCommonConfig.json
test/__tests__/data/snapchat_conversion.json

> snap converstion number_item property mapping
> Fix [#1]()

fix: snap converstion number_item prop

---

.github/workflows/prepare-for-staging-deploy.yml

chore: fix staging deploy action docker image template

---

src/adapters/network.js

> https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=rudderlabs_rudder-transformer&open=AYf-93ma5PXobXY4iNDB
> Fix [#1]()

docs: update JSDoc comment for handleHttpRequest function

---

package-lock.json
package.json

We have upgraded transformer-cdk v1 to 1.4.6(some vulnerability fixes are done in this version)
> Fix [#1]()

chore: upgrade transformer cdk v1 to 1.4.6

---

package-lock.json
package.json

Upgraded CDK v1 to latest version (v1.4.9)
> Fix [#1]()

chore: upgrade cdk to v1.4.9

---

src/v0/destinations/mailchimp/data/mailchimpTrackEventConfig.json
src/v0/destinations/mailchimp/transform.js
test/__tests__/data/mailchimp_input.json
test/__tests__/data/mailchimp_output.json

> mailchip track event name length
> Fix [#1]()

fix: mailchip track event name length

---

src/v0/destinations/mp/config.js
src/v0/destinations/mp/deleteUsers.js
test/deleteUsers/data/mp/handler_input.json
test/deleteUsers/data/mp/handler_output.json
test/deleteUsers/data/mp/nw_client_data.json

Reverts rudderlabs/rudder-transformer#2152

revert: mixpanel deletion api feature

---

src/util/prometheus.js
src/util/redis/redisConnector.test.js
src/util/redis/testData/shopify_source.json
src/v0/sources/shopify/transform.js
src/v0/sources/shopify/util.js
test/__tests__/data/shopify.json
test/__tests__/integration/data_scenarios/source/failure.json

Fix for handling the carts_create events for shopify source

fix: shopify idenity stitch

---

src/v0/destinations/braze/util.js

fix: braze dedup

---

src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
src/v0/destinations/pinterest_tag/data/pinterestUserConfig.json
src/v0/destinations/pinterest_tag/utils.js
test/__tests__/data/pinterest_tag_input.json
test/__tests__/data/pinterest_tag_output.json

> Fix [null] assignment to **ge** parameter
> Fix [#1]()

fix: pinterest ge parameter
